### ISSUE TITLE
[Bug]: New error message "load collection timeout "is not user friendly

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19310] opened 2022-09-21 02:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master(5141e05)
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Error message now:
```
<MilvusException: (code=-1, message=wait for loading collection timeout)> 
```
Error message before:
```
error = {ct.err_code: 1, ct.err_msg: f"no enough nodes to create replicas"}
```

### Expected Behavior

The error message become more user friendly.

### Steps To Reproduce

The error message before is more helpful to understand the failed reason.
The case may help.
```python
    @pytest.mark.tags(CaseLabel.L2)
    def test_load_replica_greater_than_querynodes(self):
        """
        target: test load with replicas that greater than querynodes
        method: load with 3 replicas (2 querynode)
        expected: Verify load successfully and 1 available replica
        """
        # create, insert
        self._connect()
        collection_w = self.init_collection_wrap()
        partition_w = self.init_partition_wrap(collection_w)
        partition_w.insert(cf.gen_default_list_data())
        assert partition_w.num_entities == ct.default_nb

        # load with 2 replicas
        error = {ct.err_code: 1, ct.err_msg: f"no enough nodes to create replicas"}
        partition_w.load(replica_number=3, check_task=CheckTasks.err_res, check_items=error)
```

**Comment by binbinlv** [comment] 2022-09-21 02:43
@NicoYuan1986 This is because error code and error message changed.

**Comment by binbinlv** [comment] 2022-09-21 02:47
@NicoYuan1986 but you need to check whether the error message is user friendly. If not, the title should be changed first.

**Comment by binbinlv** [comment] 2022-09-21 03:20
This is maybe duplicate of #19317 
@yah01 
could you please help to confirm? Thanks.

**Comment by yah01** [comment] 2022-09-21 03:27
> This is maybe duplicate of #19317 @yah01 could you please help to confirm? Thanks.

Same as #19317 , but load may timeout with many different reasons, we will keep the "load timeout" error, for case of more replicas than QueryNodes, we will check this and return "no enough nodes to create replicas"

**Comment by yah01** [comment] 2022-09-21 03:27
> This is maybe duplicate of #19317 @yah01 could you please help to confirm? Thanks.

Same as #19317 , but load may timeout with many different reasons, we will keep the "load timeout" error, for case of more replicas than QueryNodes, we will check this and return "no enough nodes to create replicas"

**Comment by yah01** [comment] 2022-09-21 03:28
> This is maybe duplicate of #19317 @yah01 could you please help to confirm? Thanks.

Same as #19317 , but load may timeout with many different reasons, we will keep the "load timeout" error, for case of more replicas than QueryNodes, we will check this and return "no enough nodes to create replicas"

**Closed** 2022-10-13 02:22 UTC
Labels: kind/bug
