### ISSUE TITLE
Search returns error while error log output nothing

### ISSUE THREAD

**Issue by qingfengshiran** [milvus-io/milvus#4915] opened 2021-04-09 08:38 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
CPU 

- Milvus version (master or released version)
milvusdb/milvus:1.0.0-cpu-d030521-1ea92e

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`
[Debuglog.log](https://github.com/milvus-io/milvus/files/6284290/Debuglog.log)

```yaml
paste-file-content-here
```

**Screenshots**
<img width="948" alt="image" src="https://user-images.githubusercontent.com/42227773/114153510-f5319480-9951-11eb-9c7d-9ff3cabe487c.png">
status.OK()返回false
**Additional context**

**Comment by shengjun1985** [comment] 2021-04-09 11:06
Can the error always occur?
And what's the error returned?

**Comment by qingfengshiran** [comment] 2021-04-09 11:36
> Can the error always occur?---yes
> And what's the error returned?---status.OK() return false and then following log will not output，

**Comment by shengjun1985** [comment] 2021-04-09 11:42
Can you output the error message or error code of the "status"?

**Comment by qingfengshiran** [comment] 2021-04-09 11:54
> Can you output the error message or error code of the "status"?

status  Status(code=1, message='Failed to load index file: DISK2CPU : Failed to load index from /var/lib/milvus/db/tables/test_test/1617942961108930000/1617944672477729000')

but I have check my disk:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/42227773/114176033-3b482180-996d-11eb-9fd9-9f2c42f595f7.png">
From my docker
<img width="753" alt="image" src="https://user-images.githubusercontent.com/42227773/114176111-5450d280-996d-11eb-8e39-17bac21736f5.png">
this file is exist

**Comment by shengjun1985** [comment] 2021-04-10 01:43
It looks like the issue #4778 which is fixed in branch 1.x.

**Comment by qingfengshiran** [comment] 2021-04-10 02:31
> It looks like the issue #4778 which is fixed in branch 1.x.
> 
> Before the next release, could you checkout that branch and compile it locally?
> Please refer to: [Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)

ok, I will have a try to build it locally

**Comment by qingfengshiran** [comment] 2021-04-10 03:25
> It looks like the issue #4778 which is fixed in branch 1.x.
> 
> Before the next release, could you checkout that branch and compile it locally?
> Please refer to: [Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)

<img width="923" alt="image" src="https://user-images.githubusercontent.com/42227773/114256965-56f40c00-99ef-11eb-828a-d5bc4c517a43.png">
按照docker镜像编译，总是出现这个问题。。

**Comment by yhmo** [comment] 2021-04-12 02:11
> > It looks like the issue #4778 which is fixed in branch 1.x.
> > Before the next release, could you checkout that branch and compile it locally?
> > Please refer to: [Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)
> 
> <img alt="image" width="923" src="https://user-images.githubusercontent.com/42227773/114256965-56f40c00-99ef-11eb-828a-d5bc4c517a43.png">
> 
> 按照docker镜像编译，总是出现这个问题。。

Try disable promethus:

`build.sh -t Debug -e`

**Comment by yhmo** [comment] 2021-04-13 01:36
> > Can you output the error message or error code of the "status"?
> 
> status Status(code=1, message='Failed to load index file: DISK2CPU : Failed to load index from /var/lib/milvus/db/tables/test_test/1617942961108930000/1617944672477729000')
> 
> but I have check my disk:
> <img alt="image" width="952" src="https://user-images.githubusercontent.com/42227773/114176033-3b482180-996d-11eb-9fd9-9f2c42f595f7.png">
> From my docker
> <img alt="image" width="753" src="https://user-images.githubusercontent.com/42227773/114176111-5450d280-996d-11eb-8e39-17bac21736f5.png">
> this file is exist

For the 'Failed to load index file: DISK2CPU : Failed to load index from /var/lib/milvus/db/tables/test_test/1617942961108930000/1617944672477729000', did you check the error log in /milvus/logs/xxx.error.log ?

**Comment by qingfengshiran** [comment] 2021-04-13 02:09
> > > Can you output the error message or error code of the "status"?
> > 
> > 
> > status Status(code=1, message='Failed to load index file: DISK2CPU : Failed to load index from /var/lib/milvus/db/tables/test_test/1617942961108930000/1617944672477729000')
> > but I have check my disk:
> > <img alt="image" width="952" src="https://user-images.githubusercontent.com/42227773/114176033-3b482180-996d-11eb-9fd9-9f2c42f595f7.png">
> > From my docker
> > <img alt="image" width="753" src="https://user-images.githubusercontent.com/42227773/114176111-5450d280-996d-11eb-8e39-17bac21736f5.png">
> > this file is exist
> 
> For the 'Failed to load index file: DISK2CPU : Failed to load index from /var/lib/milvus/db/tables/test_test/1617942961108930000/1617944672477729000', did you check the error log in /milvus/logs/xxx.error.log ?

Yes，but I have not find any error for that moment

**Comment by boanz** [comment] 2021-04-14 07:35
I also have this issue, but it doesn't come up very often.
![image](https://user-images.githubusercontent.com/34409364/114669191-3223cf80-9d34-11eb-8120-3823c5a52e71.png)
I found another issue. Using the Python SDK to execute query requests, the client sometimes throws an exception. The error log does not show the relevant error. I don't know if this error is related to the above issue.
<img width="979" alt="截屏2021-04-14 下午3 27 35" src="https://user-images.githubusercontent.com/34409364/114670764-f25de780-9d35-11eb-9dbc-fbea6b35fd01.png">
When will version v1.1 be released? Looking forward to the new version.

**Environment details**
Milvus version: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
Python SDK version: 1.0.0

**Comment by yhmo** [comment] 2021-04-14 09:38
> I also have this issue, but it doesn't come up very often.
> ![image](https://user-images.githubusercontent.com/34409364/114669191-3223cf80-9d34-11eb-8120-3823c5a52e71.png)
> I found another issue. Using the Python SDK to execute query requests, the client sometimes throws an exception. The error log does not show the relevant error. I don't know if this error is related to the above issue.
> ![image](https://user-images.githubusercontent.com/34409364/114673760-1e2e9c80-9d39-11eb-94ae-3cf39acbebbc.png)
> 
> When will version v1.1 be released? Looking forward to the new version.
> 
> **Environment details**
> Milvus version: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
> Python SDK version: 1.0.0

The #4778 has same error message with this issue, the 4778 is for mishards, we have already reproduce it on mishards.
But we could not reproduce the error on single milvus server. I guess the fix can avoid the error on single milvue server, but no evidence to prove it.
I suppose the v1.1 can be released in couple of days.

**Comment by shengjun1985** [comment] 2021-05-14 07:56
@qingfengshiran @boanz
Milvus v1.1.0 is released. Please upgrade.
However, if this bug still occurs in the new edition, please continue to contact our community.
Thank you.

**Closed by shengjun1985** 2021-05-14 07:56 UTC
Labels: kind/bug, severity/major
