### ISSUE TITLE
c++ SDK CORE

### ISSUE THREAD

**Issue by khw934** [milvus-io/milvus#4575] opened 2021-01-05 15:01 UTC
![image](https://user-images.githubusercontent.com/35864027/103661511-c6e69680-4fa9-11eb-9187-9c82f8857efb.png)

cocde：

![image](https://user-images.githubusercontent.com/35864027/103661595-dc5bc080-4fa9-11eb-9198-d75dc142865d.png)

![image](https://user-images.githubusercontent.com/35864027/103661664-f0072700-4fa9-11eb-94e9-a467d3d96fea.png)

**Comment by fishpenguin** [comment] 2021-01-06 02:08
Did you use milvus-0.11.0 sdk and server?

**Comment by khw934** [comment] 2021-01-06 02:21
> Did you use milvus-0.11.0 sdk and server?


How to check the version of the SDK

**Comment by fishpenguin** [comment] 2021-01-06 02:28
C++ sdk is in milvus repo, so the version of C++ sdk is the same with milvus server.

**Comment by khw934** [comment] 2021-01-06 02:31
> C++ sdk is in milvus repo, so the version of C++ sdk is the same with milvus server.

Do you think this problem is caused by the inconsistency between the SDK version and the server version?

Is there a function that can get the version of SDK?

**Comment by fishpenguin** [comment] 2021-01-06 02:34
I just want to know the version of C++ sdk and milvus server, so I can try to reproduce and solve the bug.

**Comment by khw934** [comment] 2021-01-06 02:36
> I just want to know the version of C++ sdk and milvus server, so I can try to reproduce and solve the bug.

I use C + + SDK version is 11, the server version is milvusdb/ milvus:0.11.0-cpu-d101620-4c44c0

![image](https://user-images.githubusercontent.com/35864027/103722508-17421080-500b-11eb-9fd9-0f4c40d7df19.png)

**Comment by khw934** [comment] 2021-01-06 02:39
I suggest adding a function to the SDK to get the version number

**Comment by fishpenguin** [comment] 2021-01-06 02:58
In line memcpy(bin_data.data(), data, size1) in function BuildVectors, you allocate size1 / 8 uint8_t type data in bin_data, and then you memcpy size1 to bin_data.

**Comment by khw934** [comment] 2021-01-06 07:30
> In line memcpy(bin_data.data(), data, size1) in function BuildVectors, you allocate size1 / 8 uint8_t type data in bin_data, and then you memcpy size1 uint8_t type data to bin_data. You should write memcpy(bin_data.data(), data, size1 / 8).


This is an example of project code, and there is no size / 8

![image](https://user-images.githubusercontent.com/35864027/103741360-e1655200-5033-11eb-96da-4a23479bb190.png)

**Comment by fishpenguin** [comment] 2021-01-06 08:01
This is a bug when get binary data from TopkQueryResult that there shouldn't use grpc_vector_data.binary_data().size() / 8, We will fix this bug in milvus-0.11.1.

**Comment by khw934** [comment] 2021-01-06 11:01
> This is a bug when get binary data from TopkQueryResult that there shouldn't use grpc_vector_data.binary_data().size() / 8, We will fix this bug in milvus-0.11.1.


Why size / 8? The vector can't copy only part of it





![image](https://user-images.githubusercontent.com/35864027/103761345-7aef2c80-5051-11eb-9a3d-319f6da0e374.png)

**Comment by shengjun1985** [comment] 2021-01-07 02:06
uint8_t has 8 bit, so the size of one binary vector is (dim / 8).
It is different with float vectors. The size of one float vector is (dim * sizeof(float)).

We have found that something is wrong in the 0.11.0 example, and we will fix them in 0.11.1.
Do you expect to use binary vector or float vector?
However, You can correct your code by the above principle.

**Comment by khw934** [comment] 2021-01-07 03:01
> uint8_t has 8 bit, so the size of one binary vector is (dim / 8).
> It is different with float vectors. The size of one float vector is (dim * sizeof(float)).
> 
> We have found that something is wrong in the 0.11.0 example, and we will fix them in 0.11.1.
> Do you expect to use binary vector or float vector?
> However, You can correct your code by the above principle.

I currently use a commercial version of the face recognition SDK to extract feature values and store them in Milvus. At present, the SDK returns an unsigned char array. Can I only use binary vector? The GDB screenshot is as follows


![image](https://user-images.githubusercontent.com/35864027/103845692-8422dc80-50d7-11eb-8383-ce0b3972b508.png)


What we extract is Euler distance vector, and the search effect with Milvus is not very good. Is there a way to optimize it

**Comment by shengjun1985** [comment] 2021-01-07 04:06
It looks like Euclidean distance (L2).
Usually, these data can not be directly used for binary storage.
So you need to check their documents to see how these unsigned char is transferred to float.

And here is [distance metrics](https://milvus.io/docs/v0.11.0/metric-floating.md) supported by Milvus.
To use L2, you need to convert them to float before storing.

**Comment by khw934** [comment] 2021-01-07 05:22
> It looks like Euclidean distance (L2).
> Usually, these data can not be directly used for binary storage.
> So you need to check their documents to see how these unsigned char is transferred to float.
> 
> And here is [distance metrics](https://milvus.io/docs/v0.11.0/metric-floating.md) supported by Milvus.
> To use L2, you need to convert them to float before storing.



I converted binary to float through this convenience. I don't know if it's normal. Can you help me?? Maybe the manufacturer of this algorithm has done encryption


![image](https://user-images.githubusercontent.com/35864027/103854415-56e02980-50eb-11eb-8424-21f2e2897e36.png)

**Comment by shengjun1985** [comment] 2021-01-07 05:52
The first two values seem pretty strange. But I don't know what they are.
You'd better refer to their DOC.

**Comment by khw934** [comment] 2021-01-07 05:59
> The first two values seem pretty strange. But I don't know what they are.
> You'd better refer to their DOC.



I think the first two values are very strange. I used the company's SDK for testing. At present, it is free to use, and their documents do not provide corresponding interfaces. It's convenient for you to take a look at it?? It's been a long time, thank you!!


https://www.arcsoft.com.cn/

**Comment by JackLCL** [comment] 2021-01-07 07:11
This is not within the scope of our support, you'd better contact ArcSoft's technical support staff.

**Comment by khw934** [comment] 2021-01-07 07:13
> This is not within the scope of our support, you'd better contact ArcSoft's technical support staff.

Thank you very much. Now there is a solution

**Comment by shengjun1985** [comment] 2021-01-07 08:35
Thank you for your concern and support for our project.
If you have more questions, please continue to contact our community.

**Closed by shengjun1985** 2021-01-07 08:35 UTC
Labels: Bug, sdk/c++
