### ISSUE TITLE
My Error:  CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by junjya** [milvus-io/milvus#302] opened 2019-11-12 12:20 UTC
This is CMakeError.log: 
Determining if the pthread_create exist failed with the following output:
Change Dir: /data2/develop/milvus/core/cmake_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3f86e/fast"
/usr/bin/make -f CMakeFiles/cmTC_3f86e.dir/build.make CMakeFiles/cmTC_3f86e.dir/build
make[1]: Entering directory '/data2/develop/milvus/core/cmake_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3f86e.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_3f86e.dir/CheckSymbolExists.c.o   -c /data2/develop/milvus/core/cmake_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_3f86e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3f86e.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_3f86e.dir/CheckSymbolExists.c.o  -o cmTC_3f86e 
CMakeFiles/cmTC_3f86e.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_3f86e.dir/build.make:97: recipe for target 'cmTC_3f86e' failed
make[1]: *** [cmTC_3f86e] Error 1
make[1]: Leaving directory '/data2/develop/milvus/core/cmake_build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_3f86e/fast' failed
make: *** [cmTC_3f86e/fast] Error 2

File /data2/develop/milvus/core/cmake_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**How to solve this problem???**

**Comment by yhmo** [comment] 2019-11-12 12:39
I am not sure about the root cause of this error. However It seems doesn't block build process. 
So please go ahead to run ./build.sh to build milvus project.

**Comment by cydrain** [comment] 2019-11-18 02:53
Seems harmless, close it.

**Closed by cydrain** 2019-11-18 02:53 UTC
Labels: bug, good first issue
