### ISSUE TITLE
Milvus hangs after a period of use， recover after restarting the milvus container

### ISSUE THREAD

**Issue by JamesIsHuang** [milvus-io/milvus#4204] opened 2020-11-10 02:25 UTC
![image](https://user-images.githubusercontent.com/12915720/98619835-fc228f80-233e-11eb-846c-b68bf55143c0.png)
error log:
[2020-11-09 17:55:31,007][ERROR][SERVER][TakeToExecute][reqsched_thread] Request failed with code: Error: Failed to load bloom filter: Failed to read bloom filter from file: /var/lib/milvus/db/tables/thash_collection_test/1603790125182266000/bloom_filter. Too many open files
[2020-11-09 22:24:18,525][ERROR][SERVER][Release][milvus_server] Could not open file for release: /var/lib/milvus/wal/lock, Too many open files
[2020-11-09 22:24:18,542][ERROR][SERVER][Release][webserv_thread] Could not open file for release: /var/lib/milvus/wal/lock, Too many open files

**Comment by del-zhenwu** [comment] 2020-11-10 02:32
How can we reproduce this issue, any detail operations you provided will be helpful

**Comment by JamesIsHuang** [comment] 2020-11-10 02:37
After running for a month, this problem suddenly appeared, and now it appears twice. And the amount of data is not large。
![image](https://user-images.githubusercontent.com/12915720/98620675-b666c680-2340-11eb-8f05-f7994efe5091.png)

**Comment by JamesIsHuang** [comment] 2020-11-10 02:38
> How can we reproduce this issue, any detail operations you provided will be helpful
After running for a month, this problem suddenly appeared, and now it appears twice. And the amount of data is not large。
![image](https://user-images.githubusercontent.com/12915720/98620763-dbf3d000-2340-11eb-8821-fc0ea8a15990.png)

**Comment by shengjun1985** [comment] 2020-11-10 02:44
> Too many open files

It may be the same as issue #3951
But I did not reproduce it last time.
What is your Milvus version?

**Comment by JamesIsHuang** [comment] 2020-11-10 02:46
> > Too many open files
> 
> It may be the same as issue #3951
> But I did not reproduce it last time.
> What is your Milvus version?

milvus:0.10.3-cpu-d091720-f962e8

**Comment by JamesIsHuang** [comment] 2020-11-10 02:50
> > > Too many open files
> > 
> > 
> > It may be the same as issue #3951
> > But I did not reproduce it last time.
> > What is your Milvus version?
> 
> milvus:0.10.3-cpu-d091720-f962e8

config:
***************Config in file***************

version: 0.5
cluster:
  enable: false
  role: rw
general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/
network:
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal
cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection: ~
gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
metric:
  enable: false
  address: 127.0.0.1
  port: 9091

cpu info:
***************CPU***************

processor       : 7
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7571
stepping        : 2
microcode       : 0x800126c
cpu MHz         : 2199.898
cache size      : 512 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 4399.79
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

**Comment by JamesIsHuang** [comment] 2020-11-10 03:32
Client error：
2020-11-09 09:44:43,315 ERROR [http-nio-8081-exec-66] [i.g.i.ManagedChannelOrphanWrapper] - *~*~*~ Channel ManagedChannelImpl{logId=91085, target=10.104.137.200:19530} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:517)
        at io.milvus.client.MilvusGrpcClient.<init>(MilvusGrpcClient.java:63)
        at coretechmars.thash.service.SearchService.getSimilarity(SearchService.java:56)
        at coretechmars.thash.controller.api.SearchController.getSimilarity_aroundBody0(SearchController.java:32)
        at coretechmars.thash.controller.api.SearchController$AjcClosure1.run(SearchController.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
        at com.trendmicro.mars.japm.aspect.MarsTracingAdvice.invoke(MarsTracingAdvice.java:118)
        at coretechmars.thash.controller.api.SearchController.getSimilarity(SearchController.java:27)
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

**Comment by JamesIsHuang** [comment] 2020-11-10 03:37
The client error message that first appeared on November 6：
2020-11-06 01:00:15,562 ERROR [http-nio-8081-exec-316] [i.m.client.AbstractMilvusGrpcClient] - Command RPC failed:
Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.ConnectTimeoutException: connection timed out: /10.104.137.200:19530
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:575)
        at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at co.elastic.apm.agent.impl.async.SpanInScopeRunnableWrapper.run(SpanInScopeRunnableWrapper.java:64)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concur

**Comment by JamesIsHuang** [comment] 2020-11-10 05:48
> > Too many open files
> 
> It may be the same as issue #3951
> But I did not reproduce it last time.
> What is your Milvus version?

![image](https://user-images.githubusercontent.com/12915720/98632856-487bc880-235b-11eb-9fb3-9d4334f92242.png)
It seems to be the same problem, have you located the cause?

**Comment by shengjun1985** [comment] 2020-11-10 06:19
I am not sure whether they are the same problem.
But that issue seems to be solved.
https://github.com/milvus-io/milvus/issues/4079#issuecomment-716263968

**Comment by JamesIsHuang** [comment] 2020-11-10 06:39
> I am not sure whether they are the same problem.
> But that issue seems to be solved.
> [#4079 (comment)](https://github.com/milvus-io/milvus/issues/4079#issuecomment-716263968)

Please continue to pay attention to this issue, we need to use it in a production environment

**Comment by yhmo** [comment] 2020-11-10 07:06
@JamesIsHuang 
For production environment, we strongly recommend use MySQL as meta backend, as you can see at Milvus start, there is a warning message "WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!".

For the "Too many opened files" issue, firstly check you system file open limit by this command:
`ulimit -n`
The default value is 1024, it is too small for large dataset. You can try change the limit to a large value.

If you encounter this error in milvus, don't be hurry restart milvus process. Use these command to check how many files opened by milvus:

Firstly get milvus process id:
`ps -ef|grep milvus_server`
Cmd line will return something like: "xxxx  xxx xx 0 06:57 pts/0    00:00:00 /var/lib/milvus/bin/milvus_server -c /var/lib/milvus/conf/server_config.yaml"
Now we know the milvus PID is xxx

Install "lsof" tool:
`yum install lsof`

Use lsof to check how many files are opened by milvus:
`lsof -p [milvus PID]|wc -l`

**Comment by JamesIsHuang** [comment] 2020-11-10 08:55
> ulimit -n

I have switched to mysql, and then I adjusted the limit to the upper limit。I will observe milvus for a while

**Comment by JamesIsHuang** [comment] 2020-11-10 08:56
> @JamesIsHuang
> For production environment, we strongly recommend use MySQL as meta backend, as you can see at Milvus startup, there is a warning message "WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!".
> 
> For the "Too many opened files" issue, firstly check you system file open limit by this command:
> `ulimit -n`
> The default value is 1024, it is too small for large dataset. You can try change the limit to a large value.
> 
> If you encounter this error again, don't be hurry restart milvus process. Use these command to check how many files opened by milvus:
> 
> * Firstly login into docker container:
>   `docker exec -it [milvus container id] bash`
> * get milvus process id:
>   `ps -ef|grep milvus_server`
>   Cmd line will return something like: "xxxx  xxx xx 0 06:57 pts/0    00:00:00 /var/lib/milvus/bin/milvus_server -c /var/lib/milvus/conf/server_config.yaml"
>   Now we know the milvus PID is xxx
> * Install "lsof" tool:
>   `yum install lsof`
> * Use lsof to check how many files are opened by milvus:
>   `lsof -p [milvus PID]|wc -l`

I have switched to mysql, and then I adjusted the limit to the upper limit。I will observe milvus for a while

**Comment by shengjun1985** [comment] 2020-12-01 02:24
Inactive, close.

**Comment by JamesIsHuang** [comment] 2020-12-11 07:55
When I set ulimit to 65535, but the number of open files exceeds 65535, causing milvus hangs. How to solve this problem

**Comment by JamesIsHuang** [comment] 2020-12-11 07:56
> @JamesIsHuang
> For production environment, we strongly recommend use MySQL as meta backend, as you can see at Milvus startup, there is a warning message "WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!".
> 
> For the "Too many opened files" issue, firstly check you system file open limit by this command:
> `ulimit -n`
> The default value is 1024, it is too small for large dataset. You can try change the limit to a large value.
> 
> If you encounter this error again, don't be hurry restart milvus process. Use these command to check how many files opened by milvus:
> 
> * Firstly login into docker container:
>   `docker exec -it [milvus container id] bash`
> * get milvus process id:
>   `ps -ef|grep milvus_server`
>   Cmd line will return something like: "xxxx  xxx xx 0 06:57 pts/0    00:00:00 /var/lib/milvus/bin/milvus_server -c /var/lib/milvus/conf/server_config.yaml"
>   Now we know the milvus PID is xxx
> * Install "lsof" tool:
>   `yum install lsof`
> * Use lsof to check how many files are opened by milvus:
>   `lsof -p [milvus PID]|wc -l`

When I set ulimit to 65535, but the number of open files exceeds 65535, causing milvus hangs. How to solve this problem

**Comment by yhmo** [comment] 2020-12-11 08:29
@JamesIsHuang 
In the config file server_config.yaml, it the metric set to enable?
```
metric:
  enable: true
```

**Comment by JamesIsHuang** [comment] 2020-12-11 08:39
> @JamesIsHuang
> In the config file server_config.yaml, it the metric set to enable?
> 
> ```
> metric:
>   enable: true
> ```

![image](https://user-images.githubusercontent.com/12915720/101881430-5ed1aa00-3bcf-11eb-9c42-9831700b8817.png)
![image](https://user-images.githubusercontent.com/12915720/101881497-7a3cb500-3bcf-11eb-9abe-941c625aca9a.png)

**Comment by yhmo** [comment] 2020-12-11 09:16
Could you provide more information:
- How many vectors in the database, how many dimension for each vector
- The parameters to create the collection: indefx_file_size, metric_type
- The parameters of index
- What kind of sdk(pyhton/java/go/http)
- The steps of client

**Comment by JamesIsHuang** [comment] 2020-12-11 09:29
已经贴过了，在上面

**Comment by JamesIsHuang** [comment] 2020-12-11 09:30
> Could you provide more information:
> 
> * How many vectors in the database, how many dimension for each vector
> * The parameters to create the collection: indefx_file_size, metric_type
> * The parameters of index
> * What kind of sdk(pyhton/java/go/http)
> * The steps of client

@yhmo Already posted, look up

**Comment by yhmo** [comment] 2020-12-11 11:25
Could not reproduce it with this script:

```
import sys
import time
import numpy as np
import random

from milvus import Milvus, IndexType, Status
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 192
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 1024,
                    'metric_type':MetricType.HAMMING
                    }

INDEX_TYPE = IndexType.IVF_FLAT

INDEX_PARAM = {'nlist': 2048}
NQ = 1
TOPK = 10
SEARCH_PARAM = {'nprobe': 32}

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def handle_status(status):
    if status.code != Status.SUCCESS:
        print(status)
        sys.exit(2)

def create_collection():
    print(COLLECTION_PARAM)
    status = MILVUS.create_collection(COLLECTION_PARAM)
    print(COLLECTION_NAME, "created")

def count_collection():
    status, row_count = MILVUS.count_entities(collection_name=COLLECTION_NAME)
    print(COLLECTION_NAME, "row count =", row_count)

def flush_collection():
    status = MILVUS.flush(collection_name_array=[COLLECTION_NAME])
    print(COLLECTION_NAME, "flushed")


def create_index():
    print("create index...")
    time_start = time.time()
    status = MILVUS.create_index(COLLECTION_NAME, index_type=INDEX_TYPE, params=INDEX_PARAM)
    time_end = time.time()
    print(status)
    print("create index time cost:", time_end - time_start, 'sec')
    return status


def gen_binary_vectors(num):
    raw_vectors = []
    binary_vectors = []
    for i in range(num):
        raw_vector = [random.randint(0, 1) for i in range(COLLECTION_DIMENSION)]
        raw_vectors.append(raw_vector)
        binary_vectors.append(bytes(np.packbits(raw_vector, axis=-1).tolist()))
    return binary_vectors

def add_vec_to_milvus(vec_list, vector_ids=None, tag=None):
    status, ids = MILVUS.insert(collection_name=COLLECTION_NAME, records=vec_list, ids=vector_ids, partition_tag=tag)
    handle_status(status=status)
    #print(ids)
    return ids

def print_result(results):
    print("query results for each vector:")
    for each_query in results:
        print("topk result:")
        for each_score in each_query:
            print("id = ", each_score.id, " distance = ", each_score.distance)

def search():
    query_vectors = gen_binary_vectors(NQ)
    status, results = MILVUS.search(collection_name=COLLECTION_NAME, query_records=query_vectors,
                                    top_k=TOPK, params=SEARCH_PARAM)
    handle_status(status)
    print_result(results)

def main(argv):
    create_collection()

    repeat = 162
    for i in range(repeat):
        print("No.", i)
        vec_list = gen_binary_vectors(10000)
        add_vec_to_milvus(vec_list=vec_list)

    flush_collection()
    count_collection()
    create_index()
    for i in range(100000000):
        print('No.', i)
        search()


if __name__ == "__main__":
    main(sys.argv[1:])
```

Firstly start milvus container:
```
docker pull milvusdb/milvus:0.10.3-cpu-d091720-f962e8
docker run -it -d -p 19530:19530 milvusdb/milvus:0.10.3-cpu-d091720-f962e8
docker exec -it [container_id] bash
```
Run the script:

`python3 test.py`

In the container, install lsof tool and monitor open files handler count:

```
yum install lsof
while true; lsof|wc -l; done
```

**Comment by yhmo** [comment] 2020-12-21 06:43
Test the above script on Alibaba Cloud for 7 hours. Use "lsof | wc -l" to detect open file handlers, the number of handlers grow to 4000+ after all insert() done, and stable at 4200~4300 for 7 hours.

**Comment by yhmo** [comment] 2020-12-24 07:24
Not able to reproduce now, close it.

**Closed by yhmo** 2020-12-24 07:24 UTC
Labels: Bug, Bug | Severity | S2

**Comment by kaicong12** [comment] 2023-09-18 04:55
Got the same issue too, Milvus client hangs after a month of usage and it worked again when I restarted the server. Any fixes to this yet?
