### ISSUE TITLE
[Bug]: Indexing stuck for hours 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21319] opened 2022-12-20 06:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.1
segment maxsize changed to 2GB
```

### Current Behavior

Indexing stuck even all the collection were loaded successfully.

checking the meta log, it seems that one of segments keeps compacting to a new segment, and all the other index tasks are in queue.

### Expected Behavior

index tasks completed after a few mins, as there are no new inserting.

### Steps To Reproduce

```markdown
1. insert about 90 million data into 10 collections one by one
2. create index for each collection after the collection complete insert
3. load the collection
```

### Milvus Log

[bw_etcd_ALL.221220-110252.bak.gz](https://github.com/milvus-io/milvus/files/10265888/bw_etcd_ALL.221220-110252.bak.gz)
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10265889/milvus-log.tar.gz)
[bw_etcd_ALL.221220-142433.bak.gz](https://github.com/milvus-io/milvus/files/10265900/bw_etcd_ALL.221220-142433.bak.gz)

**Comment by xige-16** [comment] 2022-12-20 12:32
Params.SegmentCompactableProportion < Params.SegmentSmallProportion, triggering a large number of single compaction

**Comment by dzqoo** [comment] 2022-12-20 14:17
When I change the smallProportion from 0.9 to 0.5 ,every collection starts loading.BUT some table is stucked.
As you see in this pic：
<img width="364" alt="acc67c1914909b4d4fdf0f531d185aa" src="https://user-images.githubusercontent.com/8862305/208687567-b37a9613-87ae-4368-b024-09ee8c15950a.png">
Here is all the logs：
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10269163/milvus-log.tar.gz)
[bw_etcd_ALL.221220-221312.bak.gz](https://github.com/milvus-io/milvus/files/10269169/bw_etcd_ALL.221220-221312.bak.gz)

**Comment by xiaofan-luan** [comment] 2022-12-20 14:32
the log is too short and  I can't see the root cause. 
[2022/12/20 14:06:35.745 +00:00] [WARN] [meta/coordinator_broker.go:158] ["No such segment in DataCoord"] [segments="[438152968761545031]"]
Seems that this segment does not exist but querycoord is always trying to load it.
For a simple fix you can restart querycoord and it should be recovered. the rootcause remained to be investigate

**Comment by dzqoo** [comment] 2022-12-21 00:51
> the log is too short and I can't see the root cause. [2022/12/20 14:06:35.745 +00:00] [WARN] [meta/coordinator_broker.go:158] ["No such segment in DataCoord"] [segments="[438152968761545031]"] Seems that this segment does not exist but querycoord is always trying to load it. For a simple fix you can restart querycoord and it should be recovered. the rootcause remained to be investigate

Yes,restart querycoord  is worked!

**Comment by xiaofan-luan** [comment] 2022-12-22 07:53
Close the issue for now, thanks !

**Closed by xiaofan-luan** 2022-12-22 07:53 UTC
Labels: kind/bug, triage/accepted, priority/prod-blocked
