### ISSUE TITLE
Milvus lost segment file suddenly in 0.10.3

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4609] opened 2021-01-13 05:28 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

Today ,milvus can not supply service, we found the following in the milvus-error.log.

[2021-01-13 11:23:58,498][ERROR][SERVER][EraseFromCache][milvus_server] Empty key cannot be erased from cache
[2021-01-13 11:23:59,500][ERROR][SERVER][EraseFromCache][milvus_server] Empty key cannot be erased from cache
[2021-01-13 11:24:00,502][ERROR][SERVER][EraseFromCache][milvus_server] Empty key cannot be erased from cache
[2021-01-13 11:24:01,504][ERROR][SERVER][EraseFromCache][milvus_server] Empty key cannot be erased from cache
[2021-01-13 11:24:02,506][ERROR][SERVER][EraseFromCache][milvus_server] Empty key cannot be erased from cache
[2021-01-13 11:24:03,257][ERROR][ENGINE][GetCollectionFilePath][reqsched_thread] Collection file doesn't exist: /var/lib/milvus/db/tables/politician/1603357529351471000/1603357529996731000 in path: /var/lib/milvus/db for collection: politician
[2021-01-13 11:24:03,259][ERROR][SERVER][OnExecute][reqsched_thread] [search][0] Query fail: Collection file doesn't exist: /var/lib/milvus/db/tables/politician/1603357529351471000/1603357529996731000
[2021-01-13 11:24:03,259][ERROR][SERVER][TakeToExecute][reqsched_thread] Request failed with code: Error: Collection file doesn't exist: /var/lib/milvus/db/tables/politician/1603357529351471000/1603357529996731000

And I found there are two segment records in mysql.
![image](https://user-images.githubusercontent.com/17443614/104410292-ff3a3600-55a2-11eb-8f0a-6ee3d6fb880c.png)

But there is only one file on disk
![image](https://user-images.githubusercontent.com/17443614/104410331-11b46f80-55a3-11eb-83c6-5b6970188b5a.png)

**Steps/Code to reproduce behavior**

**Expected behavior**
We did not do any remove file operations.

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment] 2021-01-13 06:17
@yu-hailong Could you send me the debug.log(in recent days)?

**Comment by yu-hailong** [comment] 2021-01-13 10:51
> @yu-hailong Could you send me the debug.log(in recent days)?

debug.log file size == 0

![image](https://user-images.githubusercontent.com/17443614/104442660-54d90780-55d0-11eb-923e-733c74277030.png)

**Comment by yhmo** [comment] 2021-01-14 03:04
All the debug.log files size is 0, did you change the log level in the server_config.yaml?
```
logs:
  level: debug
```

I notice there are lot of debug.log generated on Jan 13th 2021, did you restart milvus 17 times?

**Comment by yu-hailong** [comment] 2021-01-14 03:19
> All the debug.log files size is 0, did you change the log level in the server_config.yaml?
> 
> ```
> logs:
>   level: debug
> ```
> 
> I notice there are lot of debug.log generated on Jan 13th 2021, did you restart milvus 17 times?

We did health check script, while milvus can not supply service, it will try to restart it .
So there are many debug files.

**Comment by yhmo** [comment] 2021-01-14 06:24
Milvus only delete files that marked as 'delete'. If a file is marked as 'delete', we will see the 'file_type = 4' in the meta table: TableFiles. 

In the source code, there is only one place to delete segment file from disk, in the src/db/meta/MySQLMetaImpl.cpp in the MySQLMetaImpl::CleanUpFilesWithTTL(), the function firstly find out all segment files whose 'file_type = 4 or 7'; for 'file_type = 7', clean the segment file data from cache; for 'file_type = 4', remove it from disk if no tasks using it.

From your mysql, we can see the missed file's 'file_type' is 3 or 7, there is no reason for milvus to delete it.

**Comment by yu-hailong** [comment] 2021-01-14 06:59
> Milvus only delete files that marked as 'delete'. If a file is marked as 'delete', we will see the 'file_type = 4' in the meta table: TableFiles.
> 
> In the source code, there is only one place to delete segment file from disk, in the src/db/meta/MySQLMetaImpl.cpp in the MySQLMetaImpl::CleanUpFilesWithTTL(), the function firstly find out all segment files whose 'file_type = 4 or 7'; for 'file_type = 7', clean the segment file data from cache; for 'file_type = 4', remove it from disk if no tasks using it.
> 
> From your mysql, we can see the missed file's 'file_type' is 3 or 7, there is no reason for milvus to delete it.

I do think ,in common case, the file will not be deleted.
I think maybe it is a bug which be hidden deeply.

The problem happened when we deleted other collections in the same milvus.
I don't know the delete operation is relate to the problem or not.

**Comment by yhmo** [comment] 2021-01-14 07:08
You mean after you delete other collections in same milvus, the milvus stop service, and you restart milvus and found the segment file is missed?

Could you provide more detail steps? So we can do more test to try reproduce.

**Comment by yu-hailong** [comment] 2021-01-14 07:31
We have two ENV: k8s  and pysical machine.
Online service, we deployed on pysical machine, and backup service is deployed on K8s. 
They use the same metadata, so while online service down, we can change it to k8s quickly.

Yesterday, we do some test on K8S ENV: we create a collection named "example", and insert, query and drop collections.
and the metadata will be wrote to the same mysql.

And then we found the milvus service on pysical machine is down and segment data of the collection "politician" is lost.

**Comment by yhmo** [comment] 2021-01-14 09:03
About 'use the same metadata', you said there are two milvus servers use same mysql, that means the two milvus use same uri like this?

```
general:
  timezone: UTC+8
  meta_uri: mysql://root:123456@127.0.0.1:3306/milvus
```

**Comment by yhmo** [comment] 2021-01-14 09:03
About 'use the same metadata', you said there are two milvus servers use same mysql, that means the two milvus use same uri like this?

```
general:
  timezone: UTC+8
  meta_uri: mysql://root:123456@127.0.0.1:3306/milvus
```

**Comment by yu-hailong** [comment] 2021-01-14 10:36
> About 'use the same metadata', you said there are two milvus servers use same mysql, that means the two milvus use same uri in server_config.yaml like this?
> 
> ```
> general:
>   timezone: UTC+8
>   meta_uri: mysql://root:123456@127.0.0.1:3306/milvus
> ```
Yes.

**Comment by yhmo** [comment] 2021-01-15 11:09
I could not reproduce it by the following steps:
1. start milvus_server_1, using mysql uri: mysql://root:123456@127.0.0.1:3306/milvus
2. start milvus_server_2, using same mysql uri: mysql://root:123456@127.0.0.1:3306/milvus
3. use python client to connect server_1 and create a collection named 'aaa', insert some data, create two segments
4. use python client continually search 'aaa' by server_1
5. use python client to connect server_2 and create a collection named 'bbb', insert some data, do search, drop 'bbb'

result:
server_1 still work. segment files of 'aaa' no change. Seems no problem. Is any step different to yours?


By the way, it is danger to using same metadata uri for multiple milvus servers with "write" privilege. They will affect each other when meta is changed. For example, server_1 is searching 'aaa', server_2 drop 'aaa', then server_1 will report error "collection aaa doesn't exist".

**Comment by yu-hailong** [comment] 2021-01-19 02:44
> By the way, it is danger to using same metadata uri for multiple milvus servers with "write" privilege. They will affect each other when meta is changed.

OK, Thank you for you suggestion, we will avoid the usage like that.

**Closed** 2021-01-19 07:40 UTC
Labels: help wanted
