### ISSUE TITLE
NotConnectError:  Cannot check server version: Error occurred. Deadline exceeded

### ISSUE THREAD

**Issue by Chisdo** [milvus-io/milvus#6268] opened 2021-07-02 04:29 UTC
**Describe the bug**
<img width="1181" alt="Screen Shot 2021-07-02 at 11 27 09" src="https://user-images.githubusercontent.com/36720318/124217483-00e4bf80-db2b-11eb-9607-1f6ea2ae1405.png">
I keep inserting streaming data into several collections from Kafka. Firstly, everything going well. One night later, I find the lag in Kafka. Then get the error showed in the picture. The 'docker ps -a' shows both Mishards and Milvus-GPU are working. But the error just keeps continuously showing. While, after restarting the Milvus and Mishards, the error just gets disappeared. 

**Steps/Code to reproduce behavior**
No idea...

**Expected behavior**
Solve the error without restarting the Milvus each time. 

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
GTX1070 * 2 on wr-Milvus
Memory 256G
CPU: forget the type, may have around 12 ~ 24 core Server-level CPU

- Milvus version (master or released version)
- Mishards v1.1.0 with updating [#5191](https://github.com/milvus-io/milvus/discussions/5191) 
- wr-Milvus v1.1.0 with GTX1070 * 2
- ro-Milvus v1.1.0

**Configuration file**
Similar to default configure file

**Screenshots**
<img width="1181" alt="Screen Shot 2021-07-02 at 11 27 09" src="https://user-images.githubusercontent.com/36720318/124217483-00e4bf80-db2b-11eb-9607-1f6ea2ae1405.png">

**Additional context**
1. I restart the wr-Milvus and the Mishards and data can be inserted into Milvus now. But the insertion speed might decrease a little bit [not sure yet]. 
2. I have three assumptions about the issue:
   a. I inserted batched data into 6 collections simultaneously. And each collection is inserted by several threads. Is the number of inserted collections too much for Milvus?
   b. Sometimes, the connections to the Milvus may not be closed by Pymilvus code. Hence, is there any possibility that the Milvus crueshed due to current connections exceeded the number of maximum connections?
   c. Is there any possible that the GPU crushed and cause the Milvus crushed?

**Comment by yhmo** [comment] 2021-07-06 08:01
I think this error is caused by #5398, which was fixed in v1.1.1 by pr #5362. It is a random crash with tiny chance. When this bug occurs, the milvus server could crashed or hang, and client connection will time out or lost connection.

**Comment by Chisdo** [comment] 2021-07-07 03:05
> I think this error is caused by #5398, which was fixed in v1.1.1 by pr #5362. It is a random crash with tiny chance. When this bug occurs, the milvus server could crashed or hang, and client connection will time out or lost connection.

Thx for reply. After restarting the Mishards and Milvus, everything has been working well so far. I will watch the problem later.

**Comment by shengjun1985** [comment] 2021-07-15 06:27
Many bugs are fixed in the latest release. Please update.
And if you meet more problems, please continue to contact our community.

**Closed by shengjun1985** 2021-07-15 06:27 UTC
Labels: kind/support, triage/needs-infomation
