### ISSUE TITLE
Error raised when query on an empty collection

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6053] opened 2021-06-24 02:24 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
entity/test_query.py::TestQueryBase::test_query_empty_collection 
-------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------
[2021-06-24 10:17:35-ERROR-pymilvus.client.grpc_handler]: 
Addr [10.98.0.8:19530] query
Excepted error: error_code
	{'API start': '2021-06-24 10:17:35.359782', 'RPC start': '2021-06-24 10:17:35.360373', 'Exception': '2021-06-24 10:17:35.385363'} (grpc_handler.py:77)
FAILED                                                                                                                                                                              [100%]

======================================================================================== FAILURES =========================================================================================
________________________________________________________________________ TestQueryBase.test_query_empty_collection ________________________________________________________________________

self = <test_query.TestQueryBase object at 0x7fae62e40be0>, connect = <pymilvus.client.stub.Milvus object at 0x7fae62e408d0>, collection = 'test_XoU9uYyc'

    def test_query_empty_collection(self, connect, collection):
        """
        target: test query empty collection
        method: query on a empty collection
        expected: todo
        """
        connect.load_collection(collection)
>       res = connect.query(collection, default_term_expr)

entity/test_query.py:192: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py:63: in handler
    raise e
/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py:51: in handler
    return func(self, *args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py:40: in inner
    return func(self, *args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py:1117: in query
    return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
/usr/local/lib/python3.6/dist-packages/pymilvus/client/grpc_handler.py:78: in handler
    raise e
/usr/local/lib/python3.6/dist-packages/pymilvus/client/grpc_handler.py:55: in handler
    return func(self, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pymilvus.client.grpc_handler.GrpcHandler object at 0x7fae62e407f0>, collection_name = 'test_XoU9uYyc', expr = 'int64 in [0, 1, 2, 3, 4]', output_fields = None
partition_names = None, timeout = None

    @error_handler()
    def query(self, collection_name, expr, output_fields=None, partition_names=None, timeout=None):
        request = Prepare.query_request(collection_name, expr, output_fields, partition_names)
        future = self._stub.Query.future(request, wait_for_ready=True, timeout=timeout)
        response = future.result()
        if response.status.error_code != Status.SUCCESS:
>           raise BaseException(response.error_code, response.reason)
E           AttributeError: error_code

/usr/local/lib/python3.6/dist-packages/pymilvus/client/grpc_handler.py:1035: AttributeError
------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------
[2021-06-24 10:17:35-ERROR-pymilvus.client.grpc_handler]: 
Addr [10.98.0.8:19530] query
Excepted error: error_code
	{'API start': '2021-06-24 10:17:35.359782', 'RPC start': '2021-06-24 10:17:35.360373', 'Exception': '2021-06-24 10:17:35.385363'} (grpc_handler.py:77)

```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment] 2021-06-25 02:07
I'm working on it

**Comment by fishpenguin** [comment] 2021-06-25 03:18
Cannot reproduce, please check again.

**Comment by del-zhenwu** [comment] 2021-06-25 06:26
still existed.

**Comment by fishpenguin** [comment] 2021-06-25 08:45
Fixed in [pr6112](https://github.com/milvus-io/milvus/pull/6112)

**Closed** 2021-06-25 09:58 UTC
Labels: kind/bug, sdk/python
