### ISSUE TITLE
[Bug]: Flush hangs after upgrade milvus image version

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#12050] opened 2021-11-18 02:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211118-cdf8e79
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: enableCompaction: true
```

### Current Behavior

1. Deploy cluster milvus by milvus-operator with image `master-20211117-9bd3664`
```
spec:
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
  components:
    image: harbor.zilliz.cc/milvus/milvus:master-20211117-9bd3664
    proxy:
      serviceType: LoadBalancer
  config:
    queryNode:
      gracefulTime: 0
    dataCoord:
      enableCompaction: true
      compaction:
        retentionDuration: 20
```
2. Run many compact cases (I don't remember exactly)
3. Update milvus image to `master-20211118-cdf8e79` with old pulsar, etcd, minio
4. Run test case: test_compact_twice
```
    def test_compact_twice(self):
        """
        target: test compact twice
        method: 1.create with shard_num=1
                2.insert and flush twice (two segments)
                3.compact
                4.insert new data
                5.compact
        expected: Merge into one segment
        """
        # init collection with one shard, insert into two segments
        collection_w = self.collection_insert_two_segments_one_shard(prefix, tmp_nb)

        # first compact two segments
        collection_w.compact()
        collection_w.wait_for_compaction_completed()
        c_plans1 = collection_w.get_compaction_plans()[0]
        log.debug(c_plans1.plans[0].target)

        # insert new data
        df = cf.gen_default_dataframe_data(tmp_nb)
        collection_w.insert(df)
        log.debug(collection_w.num_entities)

        # second compact
        collection_w.compact()
        collection_w.wait_for_compaction_completed(timeout=50)
        collection_w.get_compaction_state()
        c_plans2 = collection_w.get_compaction_plans()[0]
```
5. Flush hangs
```
[2021-11-18 10:20:56,277 - DEBUG - ci_test]: (api_response) : {"name": "compact_eKnmGuwY", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": ......  (api_request.py:21)
[2021-11-18 10:20:56,330 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [    int64  float                                       float_vector
0       0    0.0  [0.01219940339844082, 0.08034323428948997, 0.0...
1       1    1.0  [0.12618596402505441, 0.029534926185413462, 0....
2       2    2.0  [0.00664321760966571, 0.11359982644345441, 0.1...
3       3    3.0  [0.087195......, kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-18 10:20:56,664 - DEBUG - ci_test]: (api_response) : (insert count: 100, delete count: 0, upsert count: 0, timestamp: 429182695927709697)  (api_request.py:21)
[2021-11-18 10:30:56,604 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [    int64  float                                       float_vector
0     100  100.0  [0.15384677188553952, 0.11424562599174572, 0.0...
1     101  101.0  [0.07941402198130659, 0.06670384891565809, 0.1...
2     102  102.0  [0.15301805802243318, 0.1524939109463086, 0.12...
3     103  103.0  [0.010934......, kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-18 10:30:56,779 - DEBUG - ci_test]: (api_response) : (insert count: 100, delete count: 0, upsert count: 0, timestamp: 429182853253431298)  (api_request.py:21)
```
**Server logs after upgrade:**
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7559521/milvus_logs.tar.gz)

### Anything else?

**Pod name:**
```
mic-compact-etcd-0                                         1/1     Running       0          22h
mic-compact-etcd-1                                         1/1     Running       0          22h
mic-compact-etcd-2                                         1/1     Running       0          22h
mic-compact-milvus-datacoord-6d85b7ddc-dlnzb               1/1     Running       0          4m58s
mic-compact-milvus-datanode-558944bdf8-pgpj5               1/1     Running       0          5m6s
mic-compact-milvus-indexcoord-5654dffdc6-5gh7s             1/1     Running       0          4m58s
mic-compact-milvus-indexnode-554975c7d9-qxrzl              1/1     Running       0          5m6s
mic-compact-milvus-proxy-59b5b48568-kfgvt                  1/1     Running       0          5m6s
mic-compact-milvus-querycoord-59569b9f4c-zqchs             1/1     Running       0          5m2s
mic-compact-milvus-querynode-f58d584c9-cfbls               1/1     Running       0          5m6s
mic-compact-milvus-rootcoord-5866478f99-n2cv4              1/1     Running       0          5m2s
mic-compact-minio-0                                        1/1     Running       0          22h
mic-compact-minio-1                                        1/1     Running       0          22h
mic-compact-minio-2                                        1/1     Running       0          22h
mic-compact-minio-3                                        1/1     Running       0          22h
mic-compact-pulsar-bookie-0                                1/1     Running       0          22h
mic-compact-pulsar-bookie-1                                1/1     Running       0          22h
mic-compact-pulsar-bookie-init-l5sh2                       0/1     Completed     0          22h
mic-compact-pulsar-broker-0                                1/1     Running       0          22h
mic-compact-pulsar-broker-1                                1/1     Running       0          22h
mic-compact-pulsar-proxy-0                                 1/1     Running       0          22h
mic-compact-pulsar-proxy-1                                 1/1     Running       0          22h
mic-compact-pulsar-pulsar-init-5psds                       0/1     Completed     0          22h
mic-compact-pulsar-recovery-0                              1/1     Running       0          22h
mic-compact-pulsar-toolset-0                               1/1     Running       0          22h
mic-compact-pulsar-zookeeper-0                             1/1     Running       0          22h
mic-compact-pulsar-zookeeper-1                             1/1     Running       0          22h
mic-compact-pulsar-zookeeper-2                             1/1     Running       0          22h
```

**Comment by yanliang567** [comment] 2021-11-18 06:55
/assign @sunby 
@sunby  please help to take a look at this issue

/unassign

**Comment by sunby** [comment] 2021-11-18 07:08
From rootcoord log, producing timetick to pulsar timeout.

**Comment by ThreadDao** [comment] 2021-11-18 07:17
Maybe not because of upgrade image, but because of compact. Refer to this issue #12075  for details.

**Comment by sunby** [comment] 2021-11-22 01:53
@ThreadDao I will close this issue and relate it to #12075

**Comment by binbinlv** [comment] 2021-11-22 07:02
@sunby @ThreadDao is the root cause for this issue same with #12075? If yes, please close this one, thanks.

**Closed** 2021-11-22 07:16 UTC
Labels: kind/bug, priority/critical-urgent, triage/accepted
