### ISSUE TITLE
Server crashed during creating index when running level-1 cases

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3608] opened 2020-09-04 13:16 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
test_index.py::TestIndexBase::test_create_index_partition[get_simple_index3] 
-------------------------------- live log setup --------------------------------
[2020-09-04 10:47:24-INFO-root]: {'index_type': 'IVF_SQ8_HYBRID', 'metric_type': 'L2', 'params': {'nlist': 128}} (test_index.py:38)
PASSED                                                                   [ 15%]
test_index.py::TestIndexBase::test_create_index_partition[get_simple_index4] 
-------------------------------- live log setup --------------------------------
[2020-09-04 10:47:29-INFO-root]: {'index_type': 'IVF_PQ', 'metric_type': 'L2', 'params': {'nlist': 128, 'm': 16}} (test_index.py:38)
-------------------------------- live log call ---------------------------------
[2020-09-04 10:49:27-ERROR-milvus.client.grpc_handler]: RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1599216567.508006303","description":"Error received from peer ipv4:10.97.76.162:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2020-09-04 10:47:33.885231', 'RPC start': '2020-09-04 10:47:33.886465', 'RPC error': '2020-09-04 10:49:27.508998'} (grpc_handler.py:58)
FAILED                                                                   [ 15%]
test_index.py::TestIndexBase::test_create_index_partition[get_simple_index5] 
-------------------------------- live log setup --------------------------------
[2020-09-04 10:50:08-INFO-root]: {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}} (test_index.py:38)
PASSED            
```
**Steps/Code to reproduce behavior**
http://internal.zilliz.com:18080/jenkins/job/milvus-ci/job/PR-3604/2/artifact/_artifacts/centos7/gpu/milvus_gpu_mysql_dev_test.log

```
_________ TestIndexBase.test_create_index_partition[get_simple_index4] _________

self = <test_index.TestIndexBase object at 0x7fd0c85dfa90>
connect = <milvus.client.stub.Milvus object at 0x7fd0da817e10>
collection = 'index_vAjqNXte'
get_simple_index = {'index_type': 'IVF_PQ', 'metric_type': 'L2', 'params': {'m': 16, 'nlist': 128}}

    @pytest.mark.timeout(BUILD_TIMEOUT)
    def test_create_index_partition(self, connect, collection, get_simple_index):
        '''
        target: test create index interface
        method: create collection, create partition, and add entities in it, create index
        expected: return search success
        '''
        connect.create_partition(collection, tag)
        ids = connect.insert(collection, entities, partition_tag=tag)
        connect.flush([collection])
>       connect.create_index(collection, field_name, get_simple_index)

test_index.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.6/site-packages/milvus/client/stub.py:35: in inner
    return func(self, *args, **kwargs)
/usr/local/lib/python3.6/site-packages/milvus/client/stub.py:452: in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py:59: in handler
    raise e
/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py:42: in handler
    return func(self, *args, **kwargs)
/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py:465: in create_index
    status = future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	de...6.162:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
timeout = None

    def result(self, timeout=None):
        """Returns the result of the computation or raises its exception.
    
        See grpc.Future.result for the full API contract.
        """
        with self._state.condition:
            timed_out = _common.wait(self._state.condition.wait,
                                     self._is_complete,
                                     timeout=timeout)
            if timed_out:
                raise grpc.FutureTimeoutError()
            else:
                if self._state.code is grpc.StatusCode.OK:
                    return self._state.response
                elif self._state.cancelled:
                    raise grpc.FutureCancelledError()
                else:
>                   raise self
E                   grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
E                   	status = StatusCode.UNAVAILABLE
E                   	details = "Socket closed"
E                   	debug_error_string = "{"created":"@1599216567.508006303","description":"Error received from peer ipv4:10.97.76.162:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
E                   >

/usr/local/lib/python3.6/site-packages/grpc/_channel.py:625: _MultiThreadedRendezvous
------------------------------ Captured log setup ------------------------------
[2020-09-04 10:47:29-INFO-root]: {'index_type': 'IVF_PQ', 'metric_type': 'L2', 'params': {'nlist': 128, 'm': 16}} (test_index.py:38)
----------------------------- Captured stderr call -----------------------------
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1599216567.508006303","description":"Error received from peer ipv4:10.97.76.162:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2020-09-04 10:47:33.885231', 'RPC start': '2020-09-04 10:47:33.886465', 'RPC error': '2020-09-04 10:49:27.508998'}
------------------------------ Captured log call -------------------------------
[2020-09-04 10:49:27-ERROR-milvus.client.grpc_handler]: RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1599216567.508006303","description":"Error received from peer ipv4:10.97.76.162:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2020-09-04 10:47:33.885231', 'RPC start': '2020-09-04 10:47:33.886465', 'RPC error': '2020-09-04 10:49:27.508998'} (grpc_handler.py:58)
```
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment] 2020-09-07 02:26
**CANNOT reproduce the bug**
After running the same case for a full night, nothing went wrong. Maybe it's fixed by other PRs

**Closed** 2020-09-14 06:07 UTC
Labels: Bug, Bug | Severity | S1, Priority | P1
