### ISSUE TITLE
[Bug]: `test_search_binary_with_pagination` e2e test is not stable

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#22168] opened 2023-02-14 06:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 33de788
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

test case failed

### Expected Behavior

test case shall pass stably

### Milvus Log

```
[2023-02-14T03:44:40.467Z]         # 3. search with offset+limit

[2023-02-14T03:44:40.467Z]         search_binary_param = {"metric_type": "JACCARD", "params": {"nprobe": 10}}

[2023-02-14T03:44:40.467Z]         res = collection_w.search(binary_vectors[:default_nq], "binary_vector", search_binary_param,

[2023-02-14T03:44:40.467Z]                                   default_limit + offset)[0]

[2023-02-14T03:44:40.467Z]     

[2023-02-14T03:44:40.467Z]         assert res[0].distances == sorted(res[0].distances)

[2023-02-14T03:44:40.467Z]         assert search_res[0].distances == sorted(search_res[0].distances)

[2023-02-14T03:44:40.467Z]         assert search_res[0].distances == res[0].distances[offset:]

[2023-02-14T03:44:40.467Z] >       assert set(search_res[0].ids) == set(res[0].ids[offset:])

[2023-02-14T03:44:40.467Z] E       assert {1, 275, 1233...70, 1852, ...} == {1, 275, 1233...70, 1852, ...}

[2023-02-14T03:44:40.467Z] E         Extra items in the left set:

[2023-02-14T03:44:40.467Z] E         2428

[2023-02-14T03:44:40.467Z] E         Extra items in the right set:

[2023-02-14T03:44:40.467Z] E         2720

[2023-02-14T03:44:40.467Z] E         Full diff:

[2023-02-14T03:44:40.467Z] E         - {2720, 1, 1252, 2670, 1233, 275, 1876, 1270, 2008, 1852}

[2023-02-14T03:44:40.468Z] E         ?  ------

[2023-02-14T03:44:40.468Z] E         + {1, 1252, 2670, 1233, 275, 1876, 1270, 2008, 2428, 1852}

[2023-02-14T03:44:40.468Z] E         ?     
```

### Anything else?

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22161/1/pipeline/145

**Comment by yanliang567** [comment] 2023-02-14 07:55
/assign @XuanYang-cn @NicoYuan1986 
please help to check if there is an issue 

/unassign

**Comment by XuanYang-cn** [comment] 2023-02-21 09:06
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22290/4/pipeline/

**Comment by NicoYuan1986** [comment] 2023-02-23 02:19
start to reproduce in nightly.

**Comment by NicoYuan1986** [comment] 2023-02-27 02:41
Failed frequently recently.

**Comment by XuanYang-cn** [comment] 2023-02-28 03:37
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22052/49/pipeline/145/

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22420/6/pipeline/110

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22420/4/pipeline/145

**Comment by XuanYang-cn** [comment] 2023-03-01 10:41
```
[2023-03-01T10:05:07.376Z]         try:

[2023-03-01T10:05:07.376Z]             assert 0 == len(unique_a-unique_b)

[2023-03-01T10:05:07.376Z]             assert set(search_res[0].ids) == set(res[0].ids[offset:])

[2023-03-01T10:05:07.376Z]         except Exception:

[2023-03-01T10:05:07.376Z]             print(f"ids: {search_res[0].ids}")

[2023-03-01T10:05:07.376Z]             print(f"distances: {search_res[0].distances}")

[2023-03-01T10:05:07.376Z]             print("===========")

[2023-03-01T10:05:07.376Z]             print(f"pagination ids: {res[0].ids[offset:]}")

[2023-03-01T10:05:07.376Z]             print(f"pagination distances: {res[0].distances[offset:]}")

[2023-03-01T10:05:07.376Z]         finally:

[2023-03-01T10:05:07.376Z] >           assert set(search_res[0].ids) == set(res[0].ids[offset:])

[2023-03-01T10:05:07.376Z] E           assert {84, 447, 737...86, 1588, ...} == {84, 177, 447...86, 1588, ...}

[2023-03-01T10:05:07.376Z] E             Extra items in the left set:

[2023-03-01T10:05:07.376Z] E             737

[2023-03-01T10:05:07.376Z] E             Extra items in the right set:

[2023-03-01T10:05:07.376Z] E             177

[2023-03-01T10:05:07.376Z] E             Full diff:

[2023-03-01T10:05:07.376Z] E             - {1827, 869, 1286, 2888, 177, 84, 1845, 1588, 1723, 447}

[2023-03-01T10:05:07.376Z] E             ?                         -----

[2023-03-01T10:05:07.376Z] E             + {737, 1827, 869, 1286, 2888, 84, 1845, 1588, 1723, 447}

[2023-03-01T10:05:07.376Z] E             ?  +++++

[2023-03-01T10:05:07.376Z] 

[2023-03-01T10:05:07.376Z] testcases/test_search.py:3963: AssertionError

[2023-03-01T10:05:07.376Z] ------------------------------ Captured log setup ------------------------------

[2023-03-01T10:05:07.376Z] [2023-03-01 10:04:46 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:39)

[2023-03-01T10:05:07.376Z] [2023-03-01 10:04:46 - INFO - ci_test]: [setup_method] Start setup test case test_search_binary_with_pagination. (client_base.py:40)

[2023-03-01T10:05:07.376Z] ----------------------------- Captured stdout call -----------------------------

[2023-03-01T10:05:07.376Z] ids: [2888, 84, 1723, 1845, 1588, 869, 1827, 447, 1286, 737]

[2023-03-01T10:05:07.377Z] distances: [0.5757575631141663, 0.5760869383811951, 0.5760869383811951, 0.5760869383811951, 0.5760869383811951, 0.5760869383811951, 0.5769230723381042, 0.5769230723381042, 0.5773195624351501, 0.5773195624351501]

[2023-03-01T10:05:07.377Z] ===========

[2023-03-01T10:05:07.377Z] pagination ids: [2888, 84, 1723, 1845, 1588, 869, 1827, 447, 1286, 177]

[2023-03-01T10:05:07.377Z] pagination distances: [0.5757575631141663, 0.5760869383811951, 0.5760869383811951, 0.5760869383811951, 0.5760869383811951, 0.5760869383811951, 0.5769230723381042, 0.5769230723381042, 0.5773195624351501, 0.5773195624351501]
```

**Comment by NicoYuan1986** [comment] 2023-03-02 02:17
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/298/pipeline/143

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/298/pipeline/187

**Comment by NicoYuan1986** [comment] 2023-03-08 10:50
Error: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22630/1/pipeline/110

**Comment by NicoYuan1986** [comment] 2023-03-10 07:54
Update: 
Delete the ids check of binary search result. Because check the result 'distance' is enough to ensure the binary search. And it won't break the design of search pagination accuracy.

**Comment by XuanYang-cn** [comment] 2023-03-20 03:16
@NicoYuan1986 Is this still an issue?

**Comment by NicoYuan1986** [comment] 2023-03-21 03:56
> @NicoYuan1986 Is this still an issue?

No. I think we can close the issue now.

**Comment by XuanYang-cn** [comment] 2023-03-24 02:30
close this issue for no reproduction.

**Closed by XuanYang-cn** 2023-03-24 02:30 UTC
Labels: kind/bug, priority/critical-urgent, ci/e2e
