### ISSUE TITLE
Milvus should be highly available.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#3532] opened 2020-08-31 09:14 UTC
As title.

**Comment by shengjun1985** [comment] 2020-09-02 01:38
Can you describe in detail what kind of disaster you expect Milvus will still be available?

**Comment by JackLCL** [comment] 2020-09-02 02:21
The most basic high availability should have such functions:
When a Milvus node goes down due to various unexpected reasons, it should be able to switch to another standby Milvus node within an acceptable time and restore to the state before the downtime.

**Comment by sahuang** [comment] 2020-09-02 05:13
Looks like a duplicate of #3358 . Only one feature request needs to be opened as an issue.

**Comment by XuPeng-SH** [comment] 2020-09-02 07:27
Duplicate issue of #3358

**Closed** 2020-09-02 07:27 UTC
Labels: type/new-feature
