### ISSUE TITLE
[Bug]: testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_multi_numpy_files is not stable

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#28209] opened 2023-11-07 02:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 33f17ae
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

case may fail due to hits != search limit

### Expected Behavior

case shall passes stably

### Milvus Log

```
search_results_check: limit(topK) searched (0) is not equal with expected (1)
```

### Anything else?

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28199/6/pipeline

**Comment by xiaofan-luan** [comment] 2023-11-07 02:10
/assign @yhmo 
please help on it

**Comment by weiliu1031** [comment] 2023-11-07 02:53
https://github.com/milvus-io/milvus/pull/28182

**Comment by SimFG** [comment] 2023-11-07 03:52
I also encountered this error many times. My pr: https://github.com/milvus-io/milvus/pull/28181

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28181/5/pipeline

**Comment by yanliang567** [comment] 2023-11-08 01:21
we just xfail the test to unblock e2e for now. @yhmo could you please take a look into the root cause?
/assign @yhmo 
/unassign

**Comment by zhuwenxing** [comment] 2023-11-10 08:56
@yah01 

failed job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28231/5/pipeline/

This test case still failed, but the error was load timeout
```
[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:35 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 50.191041231155396 (utility_wrapper.py:152)

[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:35 - INFO - ci_test]: bulk insert state:True (test_bulk_insert.py:909)

[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:35 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:35 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:35 - INFO - ci_test]:  collection entities: 1500 (test_bulk_insert.py:912)

[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:35 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-10T06:38:57.657Z] [2023-11-10 06:23:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:23:36 - DEBUG - ci_test]: (api_request)  : [index_building_progress] args: ['bulk_ins_parkey_LtfYfaR8', '', 'default'], kwargs: {} (api_request.py:62)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:23:36 - DEBUG - ci_test]: (api_response) : {'total_rows': 1500, 'indexed_rows': 1500, 'pending_index_rows': 0}  (api_request.py:37)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:23:36 - DEBUG - ci_test]: index states: {'total_rows': 1500, 'indexed_rows': 1500, 'pending_index_rows': 0} (utility_wrapper.py:201)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:23:36 - INFO - ci_test]: index build completed (utility_wrapper.py:203)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:23:36 - INFO - ci_test]: wait for load finished and be ready for search (test_bulk_insert.py:918)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:23:36 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {'_refresh': True} (api_request.py:62)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:26:37 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: bulk_ins_parkey_LtfYfaR8)>, <Time:{'RPC start': '2023-11-10 06:23:36.846829', 'RPC error': '2023-11-10 06:26:37.207226'}> (decorators.py:128)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:26:37 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:26:37 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: bulk_ins_parkey_LtfYfaR8)>, <Time:{'RPC start': '2023-11-10 06:23:36.837963', 'RPC error': '2023-11-10 06:26:37.207651'}> (decorators.py:128)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:26:37 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-10T06:38:57.658Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-10T06:38:57.658Z]     res = func(*args, **_kwargs)

[2023-11-10T06:38:57.658Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-10T06:38:57.658Z]     return func(*arg, **kwargs)

[2023-11-10T06:38:57.658Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 420, in load

[2023-11-10T06:38:57.658Z]     conn.load_collection(

[2023-11-10T06:38:57.658Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-10T06:38:57.658Z]     raise e from e

[2023-11-10T06:38:57.658Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-10T06:38:57.658Z]     return func(*args, **kwargs)

[2023-11-10T06:38:57.658Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-10T06:38:57.658Z]     return func(self, *args, **kwargs)

[2023-11-10T06:38:57.658Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-10T06:38:57.658Z]     raise MilvusException(

[2023-11-10T06:38:57.658Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: bulk_ins_parkey_LtfYfaR8)>

[2023-11-10T06:38:57.658Z]  (api_request.py:45)

[2023-11-10T06:38:57.658Z] [2023-11-10 06:26:37 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: bulk_ins_parkey_LtfYfaR8)> (api_request.py:46)
```

**Comment by yhmo** [comment] 2023-11-23 07:11
There are too many test cases for bulkinsert+partition_key. Each case creates 10 bulkinsert tasks to import a file with 100~200 rows. The default num_partitions is 64 for partition_key. So, each task will generate 64 tiny segments. There are 10 cases, each case 10 tasks, each task 64 tiny segment, totally there are 6400 tiny segments generated. And all these segment row count is less than 1024, no need to build index, and take part in compaction. There will be lots of compaction tasks generated. It costs too much time to process these compaction tasks. Eventually, some cases are timeout after waiting 5 minutes for their segments to be ready and cases fail.

Specifying the num_partitions to a small value can avoid this problem.

[2023-11-21T03:41:16.187Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_json_file[int_scalar-True-True] PASSED [ 54%]
[2023-11-21T03:41:42.796Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_json_file[int_scalar-False-True] PASSED [ 57%]
[2023-11-21T03:42:04.694Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_json_file[string_scalar-True-True] PASSED [ 60%]
[2023-11-21T03:42:31.205Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_json_file[string_scalar-False-True] PASSED [ 63%]
[2023-11-21T03:43:38.876Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_multi_numpy_files[10-150-13-True] XPASS [ 66%]
[2023-11-21T03:49:00.357Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_multi_numpy_files[10-150-13-False] XFAIL [ 69%]
[2023-11-21T03:53:51.811Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_csv_file[int_scalar-True] FAILED [ 72%]
[2023-11-21T03:58:58.283Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_csv_file[int_scalar-False] FAILED [ 75%]
[2023-11-21T04:02:04.696Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_csv_file[string_scalar-True] PASSED [ 78%]
[2023-11-21T04:02:26.608Z] testcases/test_bulk_insert.py::TestBulkInsert::test_partition_key_on_csv_file[string_scalar-False] PASSED [ 81%]

**Comment by yanliang567** [comment] 2023-11-23 07:36
@yhmo I don;t quite understand your comments. For one test as example, I think the 64 tiny segments will not do compaction as they are too small to trigger a compaction action, and they are not be compacted with each other as they belongs to different partitions.

**Comment by XuanYang-cn** [comment] 2023-11-23 09:06
10-tasks means import 10 times, each time there's going to be 64 segment, one for each partition; but after 10 tasks, each partition would have 10 small segments.

**Comment by yhmo** [comment] 2023-12-18 02:22
This case has been stable recently. Close this issue.

**Closed by yhmo** 2023-12-18 02:22 UTC
Labels: kind/bug, triage/accepted, ci/e2e, ci/bug
