### ISSUE TITLE
[Bug]: call has_partition failed

### ISSUE THREAD

**Issue by slayermm1122** [milvus-io/milvus#23311] opened 2023-04-10 01:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.2.4
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`col` is a collection variable in my code. I tried to call `col.has_partition(XYZ)` or `utiltiy.has_partition(col, XYZ)`, they both give me RPC erros like below:

> RPC error: [list_partitions], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
>         debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}">)>, <Time:{'RPC start': '2023-04-10 09:28:47.807496', 'RPC error': '2023-04-10 09:28:47.956257'}>

> RPC error: [has_partition], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
>         debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}">)>, <Time:{'RPC start': '2023-04-10 09:28:47.807378', 'RPC error': '2023-04-10 09:28:47.956580'}>

as well as a grpc error belwo:

> Traceback (most recent call last):
>   File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 50, in handler
>     return func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 337, in list_partitions
>     response = rf.result()
>                ^^^^^^^^^^^
>   File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/grpc/_channel.py", line 797, in result
>     raise self
> grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
>         debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}"

### Expected Behavior

I simpliy wish to use `has_partition` to check if the there is partition named XYZ, and if not, use `create_partition` to create one. here is my code:

col is a collection variable
XYZ is the name of the partition
```
    if not utility.has_partition(col,XYZ):
        utility.create_partition(col,XYZ)
```
or
if not col.has partition(XYZ)
    col.create_partition(XYZ)

### Milvus Log

PC error: [list_partitions], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}">)>, <Time:{'RPC start': '2023-04-10 09:28:47.807496', 'RPC error': '2023-04-10 09:28:47.956257'}>
RPC error: [has_partition], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}">)>, <Time:{'RPC start': '2023-04-10 09:28:47.807378', 'RPC error': '2023-04-10 09:28:47.956580'}>
Traceback (most recent call last):
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 337, in list_partitions
    response = rf.result()
               ^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/grpc/_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yanli1122/xiaozha/main.py", line 267, in <module>
    if not utility.has_partition(col,conversationId):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/orm/utility.py", line 419, in has_partition
    return _get_connection(using).has_partition(collection_name, partition_name, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 306, in has_partition
    check_pass_param(collection_name=collection_name, partition_name=partition_name)
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/client/check.py", line 365, in check_pass_param
    checker.check(key, value)
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/client/check.py", line 353, in check
    _raise_param_error(key, value)
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/client/check.py", line 253, in _raise_param_error
    raise ParamError(message=f"`{param_name}` value {param_value} is illegal")
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 132, in __repr__
    'partitions': self.partitions,
                  ^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 721, in partitions
    partition_strs = conn.list_partitions(self._name, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanli1122/xiaozha/venv/lib/python3.11/site-packages/pymilvus/decorators.py", line 56, in handler
    raise MilvusException(message=str(e)) from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:34.111.118.90:443 {created_time:"2023-04-10T09:28:47.952055+08:00", grpc_status:2, grpc_message:"it\'s a deny api, fullMethod:/milvus.proto.milvus.MilvusService/ShowPartitions"}"
>)>

### Anything else?

I am following this page: [(https://milvus.io/docs/create_partition.md)] and this page: [(https://milvus.io/docs/check_partition.md)]

**Comment by congqixia** [comment] 2023-04-10 02:07
Hi @slayermm1122 
Thanks for you feedback. Quick question: which Milvus version did you use when you meet this problem?

**Comment by xiaofan-luan** [comment] 2023-04-10 17:56
you have to make sure pymilvus and milvus on the same version I guess, sorry about it

**Comment by yanliang567** [comment] 2023-04-11 02:12
/assign @slayermm1122 
could u please double check the milvus and pymilvus versions?

/unassign

**Comment by xiaofan-luan** [comment] 2023-04-11 07:49
I don't think you are using pymilvus v2.2.4 because Milvus is not using ShowPartitions.
please check your pymilvus version

**Comment by slayermm1122** [comment] 2023-04-11 12:46
thanks for everybody's response. I am a super novice to milvus; to be honest i don't even know the diff b/w milvus and pymilvus. The reason why i said im using pymilvus v2.2.4 is because I saw `pvmilvus` and `pymilvus-2.2.4.dist-info` in the lib folder when I write python code. however when i run `pip show pymilvus`. I saw this error: 

> WARNING: Package(s) not found: pymilvus

then I try run: 
`pip install pymilvus==2.2.4`

i got a huge list error ended up with

> × Encountered error while trying to install package.
> ╰─> grpcio
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.

Can anybody help me :) thanks

**Comment by donjpierce** [comment] 2023-04-17 09:31
@slayermm1122 I think I ran into your issue this week as well. I believe this is a versioning issue as others have hinted at.

The issue is that your Milvus database instance, whether it's being hosted in the cloud or locally, is not at the most recent version that supports querying with pymilvus 2.2.6. 

In my case, the issues with grpcio (same error you showed) went away when I downgraded to pymilvus 2.2.4. Meaning that my Milvus server works well with 2.2.4. I'm using Zilliz cloud to host Milvus, so my Milvus server is managed, I don't have control over what version of pymilvus will be compatible. Turns out they are behind by a few sub versions which is not unreasonable.

I encountered this issue when install google-cloud-pubsub and protobuf, which both require very recent versions of grpcio, which incidentally bumped my pymilvus to a too-recent version. After uninstalling the pubsub and GCP packages, I was able to install pymilvus 2.2.4 and get everything working again.

> i got a huge list error ended up with
> 
> > × Encountered error while trying to install package.
> > ╰─> grpcio
> > note: This is an issue with the package mentioned above, not pip.
> > hint: See above for output from the failure.
> 
> Can anybody help me :) thanks

This is a classic python versioning issue. pip is not able to resolve your dependencies, because your project conflicts with pymilvus 2.2.4. 

I would uninstall gprcio completely, then ask pip to install 2.2.4. If you're still having versioning issues, I would delete your entire environment and start over, installing the packages you need one at a time, starting with pymilvus 2.2.4. I would lock that version in using a virtual environment that reads from a Pipfile or pyproject.toml so that pip doesn't change it in the future.

**Comment by XuanYang-cn** [comment] 2023-04-27 07:55
@slayermm1122 @donjpierce 
**about pymilvus version:**
pymilvus 2.2.6 is a buggy version, and has already been yanked at pypi. 
`pymilvus2.2.7` is the lowest version that supports `python3.11`, Please use `pymilvus>=2.2.7` to avoid grpcio problem.

**about partition:**
ShowParitions are denied as design, this's a bug in pymilvus, we didn't clean out all the usage of "ShowPartitions", I'll make sure that's fixed at `pymilvus==2.2.8`

/unassign @slayermm1122

**Comment by XuanYang-cn** [comment] 2023-04-27 09:52
@slayermm1122 `has_partition` and `create_partition` works fine, **stop printing `Collection` object will avoid the exception before the latest pymilvus releases** 

Related bug will be fixed:
https://github.com/milvus-io/pymilvus/blob/04b0d775b31687e4f7aa7afedd3af1156c415704/pymilvus/orm/collection.py#L131
```python
    def __repr__(self):
        _dict = {
            'name': self.name,
            'partitions': self.partitions,
            'description': self.description, # this code raised the exception.
            'schema': self._schema,
        }
        r = ["<Collection>:\n-------------\n"]
        s = "<{}>: {}\n"
        for k, v in _dict.items():
            r.append(s.format(k, v))
        return "".join(r)
.....
    @property
    def partitions(self, **kwargs) -> List[Partition]:
        conn = self._get_connection()
        partition_strs = conn.list_partitions(self._name, **kwargs) # ShowPartitions  RPC is denied.
        partitions = []
        for partition in partition_strs:
            partitions.append(Partition(self, partition, construct_only=True))
        return partitions
```

**Comment by mk-cupist** [comment] 2023-05-04 06:06
I get the same error when trying to create partition with `zilliz` and `pymilvus 2.2.8`
```
RPC error: [has_partition], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "it's a deny api, fullMethod:[/milvus.proto.milvus.MilvusService/HasPartition](https://vscode-remote+ssh-002dremote-002b100-002e97-002e245-002e47.vscode-resource.vscode-cdn.net/milvus.proto.milvus.MilvusService/HasPartition)"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:######### {grpc_message:"it\'s a deny api, fullMethod:[/milvus.proto.milvus.MilvusService/HasPartition](https://vscode-remote+ssh-####vscode-cdn.net/milvus.proto.milvus.MilvusService/HasPartition)", grpc_status:2, created_time:"2023-05-04T06:01:02.67318112+00:00"}"
>)>, <Time:{'RPC start': '2023-05-04 06:01:02.519854', 'RPC error': '2023-05-04 06:01:02.673502'}>
```

**Comment by mk-cupist** [comment] 2023-05-04 06:19
I get the same error when trying to create partition with `zilliz`, `pymilvus 2.2.8`, and `python 3.10.10`
```
RPC error: [has_partition], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "it's a deny api, fullMethod:[/milvus.proto.milvus.MilvusService/HasPartition](https://vscode-remote+ssh-###vscode-resource.vscode-cdn.net/milvus.proto.milvus.MilvusService/HasPartition)"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:######### {grpc_message:"it\'s a deny api, fullMethod:[/milvus.proto.milvus.MilvusService/HasPartition](https://vscode-remote+ssh-####vscode-cdn.net/milvus.proto.milvus.MilvusService/HasPartition)", grpc_status:2, created_time:"2023-05-04T06:01:02.67318112+00:00"}"
>)>, <Time:{'RPC start': '2023-05-04 06:01:02.519854', 'RPC error': '2023-05-04 06:01:02.673502'}>
```

**Comment by yanliang567** [comment] 2023-05-04 08:49
> I get the same error when trying to create partition with `zilliz`, `pymilvus 2.2.8`, and `python 3.10.10`
> 
> ```
> RPC error: [has_partition], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
> 	status = StatusCode.UNKNOWN
> 	details = "it's a deny api, fullMethod:[/milvus.proto.milvus.MilvusService/HasPartition](https://vscode-remote+ssh-###vscode-resource.vscode-cdn.net/milvus.proto.milvus.MilvusService/HasPartition)"
> 	debug_error_string = "UNKNOWN:Error received from peer ipv4:######### {grpc_message:"it\'s a deny api, fullMethod:[/milvus.proto.milvus.MilvusService/HasPartition](https://vscode-remote+ssh-####vscode-cdn.net/milvus.proto.milvus.MilvusService/HasPartition)", grpc_status:2, created_time:"2023-05-04T06:01:02.67318112+00:00"}"
> >)>, <Time:{'RPC start': '2023-05-04 06:01:02.519854', 'RPC error': '2023-05-04 06:01:02.673502'}>
> ```
As far as I know, partition is not enabled yet in zilliz cloud. please contact to support@zilliz.com for more details

**Comment by XuanYang-cn** [comment] 2023-05-22 08:25
should be fixed, closing this issue

feel free to reopen this is anything similar happened again
/close

**Closed by XuanYang-cn** 2023-05-22 08:25 UTC
Labels: kind/bug, triage/accepted
