### ISSUE TITLE
dimension influence the  precision of Euclidean distance？

### ISSUE THREAD

**Issue by DonghaiYu** [milvus-io/milvus#3043] opened 2020-07-28 04:25 UTC
i put a 91 dimension vector in milvus, with 90 value in 0 ~ 1, but 1 in 0 ~ 1100; when i search , the difference on the 90 dims can not reflect in the distance result.
data: [0 ~ 1, ....] (90) + [1100] 
search: [0 ~ 1, ....] (90, different with data) + [1100] 
got distance result : 0.0

**Comment by tinkerlin** [comment] 2020-07-28 08:07
Please describe the problem clearly, I can't understand what you say above.

**Comment by DonghaiYu** [comment] 2020-07-28 08:41
> Please describe the problem clearly, I can't understand what you say above.

for example:
I put a vector [0.21964286, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.399, 0.39592856, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.35935715, 0.22657143, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.33657143, 0.19528571, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.23842858, 0.0, 0.0, 0.0, 0.0, 0.0, 0.26414287, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.34942856, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11000000] 
in milvus
then query Euclidean distance use query vector: [0.21071428, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.43285716, 0.40492857, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2795714, 0.19628571, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.27207142, 0.14571428, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.20942858, 0.0, 0.0, 0.0, 0.0, 0.0, 0.31464285, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.22535715, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11000000]
got the result which distance between them is 0.0.

when I change all 11000000 to 110,  distance change to 0.033203125

**Comment by sawyer7246** [comment] 2020-07-28 09:21
Hi~
I have encountered a similar issue here.  
When I have vectors with a large variance (column-wise), like [0.1, 0.1, 0.1, 100000], the distance in query results turn out to be very unpredictable in decimal digits. 
Reproduction case:
Say, I have [0.1, 0.1, 0.1, 10000], [0.1, 0.1, 0.1, 20000], [0.1, 0.1, 0.1, 50000] in the database.
Then I use [0.2, 0.2, 0.2, 10000/20000/50000] as my query vectors.
I thought the top-1 candidate should have the same distance. 
However, it gets worse when I increase the variance. 

Thanks : )

**Comment by tinkerlin** [comment] 2020-07-28 11:16
The way to solve this problem is to normlize the data and use distance calculation methods IP instead.

**Comment by shengjun1985** [comment] 2020-07-29 04:08
@DonghaiYu
I have tested your sample data. No matter what calculation method is selected, the result is 0.033993.
Would you like to provide more information, such as Milvus version, index_type, CPU or GPU, query number (nq), lscpu and so on?

Here is my test code.

    #include "stdio.h"
    #include "faiss/utils/distances.h"
    #include "faiss/utils/distances_avx.h"
    #include "faiss/utils/distances_avx512.h"

    using namespace faiss;

    int main() {
        float xb[] = {0.21964286, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.399, 0.39592856,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.35935715,
                  0.22657143, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.33657143, 0.19528571,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.23842858, 0.0, 0.0, 0.0, 0.0, 0.0, 0.26414287, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.34942856, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11000000};

        float xq[] = {0.21071428, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.43285716, 0.40492857,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2795714,
                  0.19628571, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.27207142, 0.14571428, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.20942858, 0.0, 0.0, 0.0, 0.0, 0.0, 0.31464285, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.22535715, 0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11000000};

        int d = sizeof(xb) / sizeof(float);

        float dis = fvec_L2sqr_avx(xb, xq, d);
        printf("fvec_L2sqr_avx %lf \n", dis);

        dis = fvec_L2sqr_avx512(xb, xq, d);
        printf("fvec_L2sqr_avx512 %lf \n", dis);

        dis = fvec_L2sqr_sse(xb, xq, d);
        printf("fvec_L2sqr_sse %lf \n", dis);

        return 0;
    }

**Comment by DonghaiYu** [comment] 2020-07-29 09:08
@shengjun1985 
milvus: 0.8.0 cpu版本
index_type: ivf_sq8 
nq：10
lscpu: 
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
Stepping:              7
CPU MHz:               2200.000
BogoMIPS:              4400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              16896K
NUMA node0 CPU(s):     0-47
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local ibpb ibrs stibp dtherm ida arat pln pts pku ospke spec_ctrl intel_stibp arch_capabilities
```

**Comment by shengjun1985** [comment] 2020-07-29 10:05
@DonghaiYu
IVF_SQ8 may be the cause.
If you are particularly concerned about the distance value, you'd batter choose an uncompressed index type such as IVF_FLAT.

The following page roughly introduces the principles of various indexes.
https://www.milvus.io/docs/v0.10.1/index.md
(CN: https://www.milvus.io/cn/docs/v0.10.1/index.md)
Please pay attention to the introduction
“However, scalar quantization results in a loss of accuracy during searching vectors.”

**Comment by shengjun1985** [comment] 2020-07-29 11:45
@DonghaiYu
I am sorry to make a mistake.
In version 0.8.0, if the dimension (yours is 91) was not a multiple of 4, fvec_L2sqr_avx512() would not be used to calculate the distance.
And We adjusted this strategy after version 0.10.0.
Please try the latest version (0.10.1) to solve this problem.

**Comment by shengjun1985** [comment] 2020-07-29 11:52
＠sawyer7246
Would you like to provide your Milvus version, index_type, CPU or GPU, query number (nq), lscpu and so on?

**Comment by shengjun1985** [comment] 2020-07-30 02:01
@DonghaiYu
Execuse me, can you tell me why your last dimension is different from the others?
Is it a manual label used to distinguish different types?
If it's truth, why not create multiple collections or partitions to solve it?
Thank you.

**Comment by DonghaiYu** [comment] 2020-07-30 02:11
@shengjun1985 
yes, we want to use the last dimension to separate data set. But we find milvus of v0.8.0 can not support high concurrency when use multiple partitions.

**Comment by shengjun1985** [comment] 2020-08-06 04:14
You provided a lot of useful information
The question mentioned here should have been answered.
Please allow me to close the issue.
If you have more confusion, please continue to contact our community.
Thank you very much.

**Closed by shengjun1985** 2020-08-06 04:14 UTC
Labels: question
