### ISSUE TITLE
[Bug]: [Nightly] Search failed showing "Invalid shard leader" with panic "concurrent map iteration and map write"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17888] opened 2022-06-29 02:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 4ae1ca2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev87
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed showing "Invalid shard leader" with panic "concurrent map iteration and map write"

### Expected Behavior

No errors

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/622/nodes/157/steps/178/log/?start=0
```

### Milvus Log

1.milvus log:
[artifacts-milvus-distributed-pulsar-master-622-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/622/artifact/artifacts-milvus-distributed-pulsar-master-622-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_eCmMawfn
3. Test case failed time:
[2022-06-28T19:16:26.365Z] [gw0] [ 55%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_load_flush_load[3000-500-128-True-True] 

4. Test case error:
```
[2022-06-28T20:07:22.229Z] self = <test_search.TestCollectionSearch object at 0x7f8ab74aeb38>, nb = 3000
[2022-06-28T20:07:22.229Z] nq = 500, dim = 128, auto_id = True, _async = True
[2022-06-28T20:07:22.229Z] 
[2022-06-28T20:07:22.229Z]     @pytest.mark.tags(CaseLabel.L1)
[2022-06-28T20:07:22.229Z]     def test_search_load_flush_load(self, nb, nq, dim, auto_id, _async):
[2022-06-28T20:07:22.229Z]         """
[2022-06-28T20:07:22.229Z]         target: test search when load before flush
[2022-06-28T20:07:22.229Z]         method: 1. insert data and load
[2022-06-28T20:07:22.229Z]                 2. flush, and load
[2022-06-28T20:07:22.229Z]                 3. search the collection
[2022-06-28T20:07:22.229Z]         expected: search success with limit(topK)
[2022-06-28T20:07:22.229Z]         """
[2022-06-28T20:07:22.229Z]         # 1. initialize with data
[2022-06-28T20:07:22.229Z]         collection_w = self.init_collection_general(prefix, auto_id=auto_id, dim=dim)[0]
[2022-06-28T20:07:22.229Z]         # 2. insert data
[2022-06-28T20:07:22.229Z]         insert_ids = cf.insert_data(collection_w, nb, auto_id=auto_id, dim=dim)[3]
[2022-06-28T20:07:22.229Z]         # 3. load data
[2022-06-28T20:07:22.229Z]         collection_w.load()
[2022-06-28T20:07:22.229Z]         # 4. flush and load
[2022-06-28T20:07:22.229Z]         collection_w.num_entities
[2022-06-28T20:07:22.229Z]         collection_w.load()
[2022-06-28T20:07:22.229Z]         # 5. search
[2022-06-28T20:07:22.229Z]         vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
[2022-06-28T20:07:22.229Z]         collection_w.search(vectors[:nq], default_search_field,
[2022-06-28T20:07:22.229Z]                             default_search_params, default_limit,
[2022-06-28T20:07:22.229Z]                             default_search_exp, _async=_async,
[2022-06-28T20:07:22.229Z]                             check_task=CheckTasks.check_search_results,
[2022-06-28T20:07:22.229Z]                             check_items={"nq": nq,
[2022-06-28T20:07:22.229Z]                                          "ids": insert_ids,
[2022-06-28T20:07:22.229Z]                                          "limit": default_limit,
[2022-06-28T20:07:22.229Z] >                                        "_async": _async})
[2022-06-28T20:07:22.229Z] 
[2022-06-28T20:07:22.229Z] testcases/test_search.py:1136: 
[2022-06-28T20:07:22.229Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-06-28T20:07:22.229Z] utils/wrapper.py:33: in inner_wrapper
[2022-06-28T20:07:22.229Z]     result = func(*args, **kwargs)
[2022-06-28T20:07:22.229Z] base/collection_wrapper.py:153: in search
[2022-06-28T20:07:22.229Z]     timeout=timeout, **kwargs).run()
[2022-06-28T20:07:22.229Z] check/func_check.py:56: in run
[2022-06-28T20:07:22.229Z]     result = self.check_search_results(self.response, self.func_name, self.check_items)
[2022-06-28T20:07:22.229Z] check/func_check.py:205: in check_search_results
[2022-06-28T20:07:22.229Z]     search_res = search_res.result()
[2022-06-28T20:07:22.229Z] /usr/local/lib/python3.6/site-packages/pymilvus/orm/future.py:30: in result
[2022-06-28T20:07:22.229Z]     return self.on_response(self._f.result())
[2022-06-28T20:07:22.229Z] /usr/local/lib/python3.6/site-packages/pymilvus/client/asynch.py:185: in result
[2022-06-28T20:07:22.229Z]     self.exception()
[2022-06-28T20:07:22.229Z] /usr/local/lib/python3.6/site-packages/pymilvus/client/asynch.py:242: in exception
[2022-06-28T20:07:22.229Z]     raise self._exception
[2022-06-28T20:07:22.229Z] /usr/local/lib/python3.6/site-packages/pymilvus/client/asynch.py:232: in done
[2022-06-28T20:07:22.229Z]     self._results = self.on_response(self._response)
[2022-06-28T20:07:22.229Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-06-28T20:07:22.229Z] 
[2022-06-28T20:07:22.229Z] self = <pymilvus.client.asynch.ChunkedSearchFuture object at 0x7f8ab77fc6a0>
[2022-06-28T20:07:22.229Z] response = [status {
[2022-06-28T20:07:22.229Z]   error_code: UnexpectedError
[2022-06-28T20:07:22.229Z]   reason: "Invalid shard leader"
[2022-06-28T20:07:22.229Z] }
[2022-06-28T20:07:22.229Z] ]
[2022-06-28T20:07:22.229Z] 
[2022-06-28T20:07:22.229Z]     def on_response(self, response):
[2022-06-28T20:07:22.229Z]         for raw in response:
[2022-06-28T20:07:22.229Z]             if raw.status.error_code != 0:
[2022-06-28T20:07:22.229Z] >               raise MilvusException(raw.status.error_code, raw.status.reason)
[2022-06-28T20:07:22.229Z] E               pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
```

3. Panic time: [2022/06/28 19:16:21.339 +00:00]
5. panic from the following log
mdp-622-n-milvus-querynode-5d4d5b56f9-jt5zp_milvus-ci_querynode-824191fc95be761d5465bb6b2cd2ae68e6f73f0fdb38e518480ddf30c4921562.log
```
fatal error: concurrent map iteration and map write



goroutine 127451 [running]:

runtime.throw(0x2e40475, 0x26)

        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0005b15a0 sp=0xc0005b1570 pc=0x639e72

runtime.mapiternext(0xc0005b1690)

        /usr/local/go/src/runtime/map.go:858 +0x54c fp=0xc0005b1620 sp=0xc0005b15a0 pc=0x6124ec

runtime.mapiterinit(0x2b6b1c0, 0xc0048945d0, 0xc0005b1690)

        /usr/local/go/src/runtime/map.go:848 +0x1c5 fp=0xc0005b1640 sp=0xc0005b1620 pc=0x611ea5

github.com/milvus-io/milvus/internal/querynode.SegmentsStatus.Clone(0xc0048945d0, 0xc0005b1788, 0x3)

        /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster_version.go:46 +0x85 fp=0xc0005b1700 sp=0xc0005b1640 pc=0x1fda3a5

github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).applySegmentChange(0xc00408b200, 0xc003c65b60, 0xc003015e40, 0x1, 0x1, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:621 +0xf4 fp=0xc0005b17b8 sp=0xc0005b1700 pc=0x1fd6954

github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).HandoffSegments(0xc00408b200, 0xc003c65b60, 0xc0005b1c88, 0x2d79240)

        /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:561 +0x4b1 fp=0xc0005b1c00 sp=0xc0005b17b8 pc=0x1fd5c11

github.com/milvus-io/milvus/internal/querynode.(*ShardClusterService).HandoffVChannelSegments(0xc00013ff40, 0xc001aec2a0, 0x2d, 0xc003c65b60, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster_service.go:154 +0xc5 fp=0xc0005b1ea8 sp=0xc0005b1c00 pc=0x1fd9a85

github.com/milvus-io/milvus/internal/querynode.(*QueryNode).handleSealedSegmentsChangeInfo(0xc00053cb40, 0xc003b2aac0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:376 +0x25e fp=0xc0005b1fd0 sp=0xc0005b1ea8 pc=0x20074be

runtime.goexit()

        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005b1fd8 sp=0xc0005b1fd0 pc=0x674601

created by github.com/milvus-io/milvus/internal/querynode.(*QueryNode).watchChangeInfo

        /go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:359 +0x56b



goroutine 1 [chan receive, 20 minutes]:

github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000d1c050, 0xc000012000, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:523 +0x47c

github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000d14000, 0xc000050090, 0x3, 0x3, 0xc00006a2a0)

        /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:111 +0x496

github.com/milvus-io/milvus/cmd/milvus.RunMilvus(0xc000050090, 0x3, 0x3)

        /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x162

main.main()

        /go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x45



goroutine 21135 [select]:

go.etcd.io/etcd/client/v3.(*watchGrpcStream).serveSubstream(0xc000563520, 0xc001212d10, 0xc0000c76e0)

        /go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.0/watch.go:803 +0x253

created by go.etcd.io/etcd/client/v3.(*watchGrpcStream).run

        /go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.0/watch.go:554 +0x1579



goroutine 243 [select]:

google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000c973b0, 0x1, 0x0, 0x0, 0x0, 0x0)

        /go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0xff

google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000e75440, 0x0, 0x0)

        /go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x1dd

google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0006fe000)

        /go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x7b

created by google.golang.org/grpc/internal/transport.newHTTP2Client

        /go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x132e
```

**Comment by congqixia** [comment] 2022-06-29 16:12
@binbinlv shall be fixed with #17903 , could you please verify?

**Comment by binbinlv** [comment] 2022-06-30 06:59
OK， verifying.

**Comment by binbinlv** [comment] 2022-07-11 02:31
It is not reproduced for long time, fixed.

**Comment by NicoYuan1986** [comment] 2022-08-30 02:11
Recently, the issue appears again.
1.milvus:master(1527aee)    pymilvus:2.2.0.dev23

2. nightly:https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/67/pipeline/155

3. milvus log:
case: TestCollectionSearch.test_search_after_different_index_with_params[8-False-True-RHNSW_PQ-params7]
collection name: search_collection_Ttcvb4MG
failed time: [2022-08-29T19:13:06.419Z] [gw4] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-False-True-RHNSW_PQ-params7] 
log: [artifacts-milvus-distributed-kafka-nightly-67-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/67/artifact/artifacts-milvus-distributed-kafka-nightly-67-pymilvus-e2e-logs.tar.gz)

```
[2022-08-29T19:56:38.352Z] self = <pymilvus.client.asynch.ChunkedSearchFuture object at 0x7fe7627b61c0>
[2022-08-29T19:56:38.352Z] response = [status {
[2022-08-29T19:56:38.352Z]   error_code: UnexpectedError
[2022-08-29T19:56:38.352Z]   reason: "Invalid shard leader"
[2022-08-29T19:56:38.352Z] }
[2022-08-29T19:56:38.352Z] ]
[2022-08-29T19:56:38.352Z] 
[2022-08-29T19:56:38.352Z]     def on_response(self, response):
[2022-08-29T19:56:38.352Z]         for raw in response:
[2022-08-29T19:56:38.352Z]             if raw.status.error_code != 0:
[2022-08-29T19:56:38.352Z] >               raise MilvusException(raw.status.error_code, raw.status.reason)
[2022-08-29T19:56:38.352Z] E               pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
```

**Comment by congqixia** [comment] 2022-08-30 02:39
Hi @NicoYuan1986 , this issue was originally caused by concurrent map read/write, which was fixed long time ago.
`Invalid shard leader` shall have some different root cause. Please open a new issue so that we could separate this problem

**Closed by congqixia** 2022-08-30 02:39 UTC
Labels: kind/bug, priority/critical-urgent, triage/accepted

**Comment by NicoYuan1986** [comment] 2022-08-30 02:40
> Hi @NicoYuan1986 , this issue was originally caused by concurrent map read/write, which was fixed long time ago. `Invalid shard leader` shall have some different root cause. Please open a new issue so that we could separate this problem

OK!
