### ISSUE TITLE
Could not open hwmon directory

### ISSUE THREAD

**Issue by ThomWright** [milvus-io/milvus#3262] opened 2020-08-14 16:14 UTC
**Describe the bug**
Every time metrics are requested, I see `Could not open hwmon directory` in the errors logs.

**Steps/Code to reproduce behavior**
- deploy Milvus on GKE (Google Kubernetes Engine) using the [helm chart](https://github.com/milvus-io/milvus-helm)
- look in the error log file

**Expected behavior**
No errors logged.

**Environment details**
- Hardware/Software conditions: GKE - Kubernetes 1.15
- Method of installation: Docker (`0.10.1-cpu-d072020-bd02b1`)
- Milvus version: 0.10.1
- Milvus configuration: `metric: enable: true` - not sure what else is relevant

**Screenshots**
N/A

**Additional context**
Log I see:

```
[2020-08-14 15:39:11,950][ERROR][SERVER][CPUTemperature][metric_thread] Could not open hwmon directory
```

The `/sys/class/hwmon` directory simply does not exist in our deployment.

**Comment by fishpenguin** [comment] 2020-08-28 06:31
/sys/class/hwmon is used to get the CPU temperature of linux system. So what's the system in your deployment?

**Comment by ThomWright** [comment] 2020-08-28 09:33
Google Kubernetes Engine (Kubernetes 1.15), the nodes are running Google's Container-Optimized OS:

https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#cos

https://cloud.google.com/container-optimized-os

**Comment by fishpenguin** [comment] 2020-09-03 03:18
So far we have not used GKE to do testing, and have not find the same problem in our own system and machine. Later we will try to deploy milvus on GKE and figure out the problem.

**Comment by ThomWright** [comment] 2020-09-03 08:47
Also, as I said in #3176, why is it necessary for Milvus to inspect the CPU temperature? Could this not be left to other monitoring tools?

**Comment by fishpenguin** [comment] 2020-09-04 01:50
It's not necessary, we just consider that  CPU temperature may be one of the factors affecting milvus performance. So we expose the CPU temperature in prometheus. However, users can use other tools to get the temperature.

**Comment by fishpenguin** [comment] 2020-09-04 01:52
Also, this CPU temperature issue won't affect the operation of milvus at all.

**Comment by fishpenguin** [comment] 2020-09-18 02:54
No more comments, I close this issue.

**Closed by fishpenguin** 2020-09-18 02:54 UTC
Labels: Bug | Severity | S2, question

**Comment by ThomWright** [comment] 2020-09-18 08:50
Uh, what? Why? What was I supposed to comment?

>Also, this CPU temperature issue won't affect the operation of milvus at all.

No, but it's very noisy in the error logs. How am I supposed to find _real_ errors when it's clogged up with _not real_ errors?

>Later we will try to deploy milvus on GKE and figure out the problem.

Has this happened?

Alternatively instead of spending time debugging and fixing something which isn't necessary, just turn it off? Or silence the error. Or... something?

**Comment by fishpenguin** [comment] 2020-09-25 08:17
We haven't deployed milvus on GKE and tried to figure out this problem, because we haven't reproduced this problem on our testing machine, and we think it doesn't matters.
However If you really think this problem matters a lot, you can reopen this issue, and give some suggestions, or propose a pull request to help to solve it.
And for the noisy in error logs, I will consider to put the log into warning instead of error.
