### ISSUE TITLE
Wrong row count returned after vectors insert with multithreads

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2321] opened 2020-05-13 02:02 UTC
**Describe the bug**
Occurs in occasionally.
```
[2020-05-12T17:43:27.427Z] =================================== FAILURES ===================================

[2020-05-12T17:43:27.702Z] __________ TestAddBase.test_collection_add_rows_count_multi_threading __________

[2020-05-12T17:43:27.710Z] 

[2020-05-12T17:43:27.710Z] self = <test_add_vectors.TestAddBase object at 0x7f43a37aa7f0>

[2020-05-12T17:43:27.710Z] args = {'handler': 'GRPC', 'ip': 'milvus-ci-0-9-0-2-single-centos7-cpu.milvus.svc.cluster.local', 'port': 19530}

[2020-05-12T17:43:27.710Z] 

[2020-05-12T17:43:27.710Z]     @pytest.mark.level(2)

[2020-05-12T17:43:27.710Z]     @pytest.mark.timeout(30)

[2020-05-12T17:43:27.710Z]     def test_collection_add_rows_count_multi_threading(self, args):

[2020-05-12T17:43:27.710Z]         '''

[2020-05-12T17:43:27.710Z]         target: test collection rows_count is correct or not with multi threading

[2020-05-12T17:43:27.710Z]         method: create collection and add vectors in it(idmap),

[2020-05-12T17:43:27.710Z]             assert the value returned by count_entities method is equal to length of vectors

[2020-05-12T17:43:27.710Z]         expected: the count is equal to the length of vectors

[2020-05-12T17:43:27.710Z]         '''

[2020-05-12T17:43:27.710Z]         if args["handler"] == "HTTP":

[2020-05-12T17:43:27.710Z]             pytest.skip("Skip test in http mode")

[2020-05-12T17:43:27.710Z]         thread_num = 8

[2020-05-12T17:43:27.710Z]         threads = []

[2020-05-12T17:43:27.710Z]         collection = gen_unique_str()

[2020-05-12T17:43:27.710Z]         param = {'collection_name': collection,

[2020-05-12T17:43:27.710Z]                  'dimension': dim,

[2020-05-12T17:43:27.710Z]                  'index_file_size': index_file_size,

[2020-05-12T17:43:27.710Z]                  'metric_type': MetricType.L2}

[2020-05-12T17:43:27.710Z]         milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"])

[2020-05-12T17:43:27.710Z]         milvus.create_collection(param)

[2020-05-12T17:43:27.710Z]         vectors = gen_vectors(nb, dim)

[2020-05-12T17:43:27.710Z]         def add(thread_i):

[2020-05-12T17:43:27.710Z]             logging.getLogger().info("In thread-%d" % thread_i)

[2020-05-12T17:43:27.710Z]             milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"])

[2020-05-12T17:43:27.710Z]             status, result = milvus.insert(collection, records=vectors)

[2020-05-12T17:43:27.710Z]             assert status.OK()

[2020-05-12T17:43:27.710Z]             status = milvus.flush([collection])

[2020-05-12T17:43:27.710Z]             assert status.OK()

[2020-05-12T17:43:27.710Z]         for i in range(thread_num):

[2020-05-12T17:43:27.710Z]             x = threading.Thread(target=add, args=(i, ))

[2020-05-12T17:43:27.710Z]             threads.append(x)

[2020-05-12T17:43:27.710Z]             x.start()

[2020-05-12T17:43:27.710Z]         for th in threads:

[2020-05-12T17:43:27.710Z]             th.join()

[2020-05-12T17:43:27.710Z]         status, res = milvus.count_entities(collection)

[2020-05-12T17:43:27.710Z] >       assert res == thread_num * nb

[2020-05-12T17:43:27.710Z] E       assert 42000 == 48000

[2020-05-12T17:43:27.710Z] E         -42000

[2020-05-12T17:43:27.710Z] E         +48000

[2020-05-12T17:43:27.710Z] 

[2020-05-12T17:43:27.710Z] test_add_vectors.py:656: AssertionError

[2020-05-12T17:43:27.710Z] ----------------------------- Captured stderr call -----------------------------

[2020-05-12T17:43:27.710Z] _cmd

[2020-05-12T17:43:27.710Z] Request timeout: 

[2020-05-12T17:43:27.710Z] Exception in thread Thread-523:

[2020-05-12T17:43:27.710Z] Traceback (most recent call last):

[2020-05-12T17:43:27.710Z]   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner

[2020-05-12T17:43:27.710Z]     self.run()

[2020-05-12T17:43:27.710Z]   File "/usr/local/lib/python3.6/threading.py", line 864, in run

[2020-05-12T17:43:27.710Z]     self._target(*self._args, **self._kwargs)

[2020-05-12T17:43:27.710Z]   File "/home/jenkins/agent/workspace/milvus-ci_0.9.0/tests/milvus_python_test/test_add_vectors.py", line 644, in add

[2020-05-12T17:43:27.710Z]     milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"])

[2020-05-12T17:43:27.710Z]   File "/home/jenkins/agent/workspace/milvus-ci_0.9.0/tests/milvus_python_test/utils.py", line 33, in get_milvus

[2020-05-12T17:43:27.710Z]     milvus = Milvus(host=host, port=port, handler=handler)

[2020-05-12T17:43:27.710Z]   File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 92, in __init__

[2020-05-12T17:43:27.710Z]     self._pool = ConnectionPool(pool_uri, **pool_kwargs)

[2020-05-12T17:43:27.710Z]   File "/usr/local/lib/python3.6/site-packages/milvus/client/pool.py", line 83, in __init__

[2020-05-12T17:43:27.710Z]     self._check_version()

[2020-05-12T17:43:27.710Z]   File "/usr/local/lib/python3.6/site-packages/milvus/client/pool.py", line 98, in _check_version

[2020-05-12T17:43:27.710Z]     version))

[2020-05-12T17:43:27.710Z] ValueError: Version of python SDK(0.3.15) not match that of serverNone, excepted is 0.9.0.

[2020-05-12T17:43:27.710Z] 

[2020-05-12T17:43:27.710Z] ------------------------------ Captured log call -------------------------------

[2020-05-12T17:43:27.710Z] [16:38:07-INFO-root]: In thread-0 (test_add_vectors.py:643)

[2020-05-12T17:43:27.710Z] [16:38:07-INFO-root]: In thread-1 (test_add_vectors.py:643)

[2020-05-12T17:43:27.710Z] [16:38:07-INFO-root]: In thread-2 (test_add_vectors.py:643)

[2020-05-12T17:43:27.711Z] [16:38:07-INFO-root]: In thread-3 (test_add_vectors.py:643)

[2020-05-12T17:43:27.711Z] [16:38:07-INFO-root]: In thread-4 (test_add_vectors.py:643)

[2020-05-12T17:43:27.711Z] [16:38:07-INFO-root]: In thread-5 (test_add_vectors.py:643)

[2020-05-12T17:43:27.711Z] [16:38:07-INFO-root]: In thread-6 (test_add_vectors.py:643)

[2020-05-12T17:43:27.711Z] [16:38:07-INFO-root]: In thread-7 (test_add_vectors.py:643)

[2020-05-12T17:43:27.711Z] [16:38:08-ERROR-milvus.client.grpc_handler]: _cmd

[2020-05-12T17:43:27.711Z] Request timeout:  (grpc_handler.py:38)
```
**Steps/Code to reproduce behavior**
1.  create collection
2. 8 threads start, and do insert vectors and flush
3. assert row count in collection, get wrong result.

**Expected behavior**

**Environment details**
0.9.0

**Screenshots**

**Additional context**

**Comment by yhmo** [comment] 2020-05-13 08:19
Use the following code, could not reproduce:
```
def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, TABLE_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    if PRINT_VECTOR == True:
        print(vec_list)
    return vec_list

vec_list = gen_vec_list(6000, seed=np.random.RandomState(10))
def add(tb_name):
    milvus = Milvus(host=SERVER_ADDR, port=SERVER_PORT)
    status, result = milvus.insert(collection_name=tb_name, records=vec_list)
    status = milvus.flush(collection_name=tb_name)

def multi_add():
    for k in range(1000):
        print("No.", k)
        # status = MILVUS.drop_collection(collection_name=TABLE_NAME)
        # time.sleep(2)
        tb_name = 'tbl_' + str(k)
        tb_param =  {'collection_name': tb_name, 'dimension': TABLE_DIMENSION, 'index_file_size': 1024, 'metric_type':MetricType.L2}
        status = MILVUS.create_collection(tb_param)

        time_start = time.time()
        threads = []
        for i in range(8):
            x = threading.Thread(target=add, args=(tb_name,))
            threads.append(x)
            x.start()
        for th in threads:
            th.join()
        time_end = time.time()
        print("done", time_end - time_start, 'sec')
        status, row_count = MILVUS.count_entities(collection_name=tb_name)
        if row_count != 48000:
            print('Wrong!=================================================================', row_count, '!= 48000')
```

**Comment by del-zhenwu** [comment] 2020-05-13 09:43
not reproduced with local testing.

**Comment by del-zhenwu** [comment] 2020-05-21 10:44
```
[2020-05-21 18:39:41,819][ERROR][SERVER][EraseFromCache][milvus_server] Empty key cannot be erased from cache
[2020-05-21 18:41:58,534][ERROR][ENGINE][MergeFiles][milvus_server] Failed to get merge files for collection: test_add_KETFWap3
[2020-05-21 18:41:58,534][ERROR][ENGINE][BackgroundMerge][milvus_server] Failed to get merge files for collection: test_add_KETFWap3 reason:Collection test_add_KETFWap3 not found
[2020-05-21 18:42:01,609][ERROR][ENGINE][MergeFiles][milvus_server] Failed to get merge files for collection: test_add_AUWsTT0D
[2020-05-21 18:42:01,609][ERROR][ENGINE][BackgroundMerge][milvus_server] Failed to get merge files for collection: test_add_AUWsTT0D reason:Collection test_add_AUWsTT0D not found

```

**Comment by yhmo** [comment] 2020-05-22 11:20
In pymilvus  client/pool.py, in the _prepare() method, there is a timeout=1
![Selection_128](https://user-images.githubusercontent.com/2282099/82662639-cd194400-9c60-11ea-9fd3-076eca0a74d7.png)
In milvus source code, core/src/db/meta/MySQLConnectionPool.cpp, the MySQL meta connection pool:
![Selection_129](https://user-images.githubusercontent.com/2282099/82662722-f89c2e80-9c60-11ea-88fc-efcfaa96c9e2.png)

If there are too many connection in mysql meta, the pool could sleep 1 second to wait connection decrease, but the pymilvus client only wait 1 second to check server version, this is the reason why sometimes ci failed.

**Comment by yhmo** [comment] 2020-05-23 02:38
fixed by pr2413

**Comment by del-zhenwu** [comment] 2020-05-27 01:51
still re-produced

**Comment by del-zhenwu** [comment] 2020-06-03 03:25
```
        if args["handler"] == "HTTP":
            pytest.skip("Skip test in http mode")
        thread_num = 8
        threads = []
        milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"], try_connect=False)
        vectors = gen_vectors(nb, dim)
        def add(thread_i):
            logging.getLogger().info("In thread-%d" % thread_i)
            # milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"])
            # assert milvus
            status, result = milvus.insert(collection, records=vectors)
            assert status.OK()
            status = milvus.flush([collection])
            assert status.OK()
        for i in range(thread_num):
            x = threading.Thread(target=add, args=(i, ))
            threads.append(x)
            x.start()
        for th in threads:
            th.join()
        status, res = milvus.count_entities(collection)
        assert res == thread_num * nb

```
After define `milvus connection instance` in thread, this issue can not be reproduced.
But we need to find out the reason...

**Comment by del-zhenwu** [comment] 2020-06-03 03:26
```
        if args["handler"] == "HTTP":
            pytest.skip("Skip test in http mode")
        thread_num = 8
        threads = []
        milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"], try_connect=False)
        vectors = gen_vectors(nb, dim)
        def add(thread_i):
            logging.getLogger().info("In thread-%d" % thread_i)
            # milvus = get_milvus(host=args["ip"], port=args["port"], handler=args["handler"])
            # assert milvus
            status, result = milvus.insert(collection, records=vectors)
            assert status.OK()
            status = milvus.flush([collection])
            assert status.OK()
        for i in range(thread_num):
            x = threading.Thread(target=add, args=(i, ))
            threads.append(x)
            x.start()
        for th in threads:
            th.join()
        status, res = milvus.count_entities(collection)
        assert res == thread_num * nb

```
After define `milvus connection instance` in thread, this issue can not be reproduced.
But we need to find out the reason...

**Comment by tinkerlin** [comment] 2020-06-08 01:43
@BossZou

**Comment by BossZou** [comment] 2020-06-11 02:44
Need to try to reproduce.

**Comment by BossZou** [comment] 2020-06-16 06:07
The latest `pymilvus-test` version has enlarged the default timeout value in each RPCs. And this issue need to reproduce.

**Comment by del-zhenwu** [comment] 2020-07-02 03:33
no-produced

**Closed** 2020-07-02 03:32 UTC
Labels: Bug, Bug | Severity | S2, sdk/python
