### ISSUE TITLE
Failed to load index file: boost::filesystem::create_directory: No such file or directory while seaching by milvus

### ISSUE THREAD

**Issue by lengyhua** [milvus-io/milvus#5287] opened 2021-05-18 13:29 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1.While inserting data, the client shows that insert success, howerver, the logs in milvus-writable print error like: [STORAGE][PUTObjectFile][wal_thread] ERROR: File '/var/lib/milvus/db/tables/.../bloom_filter' not exist! (I observed the dir while inserting data, the dir indeed changed when inserting, some dirs just disappear)
2.After insert data into milvus, while search by milvus, milvus client throws exception: Failed to load index file: boost::filesystem::create_directory: No such file or directory: "/var/lib/milvus/db/tables/...."

**Steps/Code to reproduce behavior**
1. First, we prepared data (2000000 totally) to insert into milvus, about 50000 pieces of data each time. PS. the first time, we will create the collection: milvusClient.createCollection(new CollectionMapping.Builder("pvid_xxx", 256).withMetricType(MetricType.IP).withIndexFileSize(256).build());
2. Second, when insert into milvus finished, we picked the sample data to seach in the collection create in step 1

**Expected behavior**

**Method of installation**
- [*] Docker/cpu
- [*] Docker/gpu
- [*] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
GPU: T4
OS: CentOS 

- Milvus version (master or released version)
1.1.0

**Configuration file**

```yaml

```

**Screenshots**
![image](https://user-images.githubusercontent.com/25021079/118659209-b11e9300-b81f-11eb-96b7-aea0c8389bab.png)
![image](https://user-images.githubusercontent.com/25021079/118659272-bda2eb80-b81f-11eb-9825-bfe95cad25f7.png)
![image](https://user-images.githubusercontent.com/25021079/118659567-05297780-b820-11eb-85c1-c00da6179c8b.png)

**Additional context**

**Comment by yhmo** [comment] 2021-05-19 03:08
Hi @lengyhua 
The error log show "GetObject: NoSuchKey" is throw from the S3 wrapper: /home/yhmo/git/milvus/core/src/storage/s3/S3ClientWrapper.cpp

The S3 storage integration is a new feature that we still in testing and not yet officially announce publish. I suppose it will be published in v1.2.0. The error indicated that the bloomfilter file is not correctly persist to S3 storage.

**Comment by lengyhua** [comment] 2021-05-19 03:20
> Hi @lengyhua
> The error log show "GetObject: NoSuchKey" is throw from the S3 wrapper: /home/yhmo/git/milvus/core/src/storage/s3/S3ClientWrapper.cpp
> 
> The S3 storage integration is a new feature that we still in testing and not yet officially announce publish. I suppose it will be published in v1.2.0. The error indicated that the bloomfilter file is not correctly persisted to S3 storage.

Is this a bug? Can I fix this error by modify config files?

PS. When v1.2.0 will be released?

**Comment by yhmo** [comment] 2021-05-19 03:29
I think this is a bug, need C++ code change.
We not yet plan the v1.2.0 release date. Typically, the time gat between two versions is 2 months.

The initial code of this feature is come from https://github.com/milvus-io/milvus/pull/4792
It require open a compile flag MILVUS_WITH_AWS to enable the S3 storage, did you compile milvus by yourself?

**Comment by lengyhua** [comment] 2021-05-19 03:39
> I think this is a bug, need C++ code change.
> We not yet plan the v1.2.0 release date. Typically, the time gap between two versions is 2 months.
> 
> The initial code of this feature is come from #4792
> It require open a compile flag MILVUS_WITH_AWS to enable the S3 storage, did you compile milvus by yourself?

Yes, we compiled from #4792 and enabled the S3 storage.
The file indeed storaged in S3 successfully, but it just occurs the error mentioned above.

**Comment by yhmo** [comment] 2021-05-19 03:43
Your compile it base on which branch? 1.0 or 1.1?

**Comment by lengyhua** [comment] 2021-05-19 04:19
> Your compile it base on which branch? 1.0 or 1.1?

1.1

**Comment by matrixji** [comment] 2021-05-19 11:57
> @lengyhua
> 
> @matrixji is the owner of this feature, let's waiting for his fix. Thank you @matrixji.

After some offline check and testing with @lengyhua, the problem is fixed. PR will be raised later.

The RC is in some condition where Milvus need to access the data in S3, it first creates a local directory that has the same structure as the local disk does. But when this happens on distributed deployment, in some containers the <COLLECTION> folder is missing, and using boost's create_directory with <COLLECTION>/<SEGMENT> will raise an exception. I'd like to change `create_directory` -> `create_directories`, as in Milvus's case, seems create_directories are always more reasonable.

**Comment by shengjun1985** [comment] 2021-05-20 02:48
That PR is merged.
Please pull the branch 1.1 and compile again.
Many thanks to @matrixji and @lengyhua .

**Closed** 2021-05-26 02:16 UTC
Labels: kind/bug, severity/critical
