### ISSUE TITLE
[Bug]: Search or Query may fail if array field of some row has less elements than expression index

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#28293] opened 2023-11-09 03:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: b9bf910
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    any
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Having collection with array field, with max capacity = 10
some element has arr field = `[1, 2 ,3, 4, 5, 6, 7]` , while some has only lesser one say `[]`
search or query with expression `arr[0] op value` returns search failure
```
failed to search collection, err: failed to search: attempt #0: failed to search/query delegator 1 for channel by-dev-rootcoord-dml_0_445513266767593736v0: fail to Search, QueryNode ID=1, reason=worker(1) query failed: UnknownError: Assert "index >= 0 && index < length_" at /home/silverxia/workspace/milvus/internal/core/src/common/Array.h:464
 => index out of range, index=0, length=0: attempt #1: no available shard delegator found: service unavailable
```

### Expected Behavior

if arr index in expression is larger than element length, this line shall be ignored instead of return search error

**Comment by yanliang567** [comment] 2023-11-09 03:08
/assign @NicoYuan1986 
could u please add a scenario for this case?

/assign @xiaocai2333 
/unassign

**Comment by xiaofan-luan** [comment] 2023-11-09 05:18
good catch

**Comment by xiaofan-luan** [comment] 2023-11-09 05:19
@xiaocai2333 
We need more unit test on array data types.
This seems to be a easy but we didn't catch

**Comment by xiaocai2333** [comment] 2023-11-09 06:16
> @xiaocai2333 We need more unit test on array data types. This seems to be a easy but we didn't catch

This is an design mistake, we should align array attribute with json array.
I will fix it.

**Comment by NicoYuan1986** [comment] 2023-11-09 09:36
> /assign @NicoYuan1986 could u please add a scenario for this case?
> 
> /assign @xiaocai2333 /unassign

The test case does exist: `test_search.py::TestCollectionSearchInvalid::test_search_with_expression_invalid_array_one`. And it was an expected behavior then. 

I will modify the case when the fix pr is merged.

**Comment by xiaocai2333** [comment] 2023-11-22 09:01
@NicoYuan1986 this has been fixed, please add test cases for it.

**Comment by NicoYuan1986** [comment] 2023-12-05 09:03
verify fixed. master-20231205-ad1daebc-amd64

**Closed by NicoYuan1986** 2023-12-05 09:03 UTC
Labels: kind/bug, triage/accepted
