### ISSUE TITLE
[Bug]:  failed to load one of collections

### ISSUE THREAD

**Issue by charleskangzq** [milvus-io/milvus#31442] opened 2024-03-20 08:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory:  16C 64G
- GPU:  No
- Others:
```

### Current Behavior

One collection in Milvus cannot be loaded properly. 
When manually load it on the attu page ，status would get stuck at 0% for a period of time, and then become unloaded.

All other collections can be loaded normally and are not affected.

The collection not loaded correctly has two million entities and some scalar fields, other collections have only several thousands entities and no scaler fields.

### Expected Behavior

All collections are loaded normally and can be queried

### Steps To Reproduce

```markdown
Colleague said they performed upsert and flush operations , I don't know the step details.
```

### Milvus Log

**queryCoord：**

[2024/03/20 07:45:37.855 +00:00] [WARN] [task/scheduler.go:801] ["task stale due to leader not found"] [taskID=1710904694733] [collectionID=446465103651979208] [replicaID=448502753263353859] [source=segment_checker]
[2024/03/20 07:45:37.855 +00:00] [INFO] [task/scheduler.go:428] ["failed to promote task"] [taskID=1710904694733] [collectionID=446465103651979208] [replicaID=448502753263353859] [source=segment_checker] [error="failed to get shard delegator: channel=by-dev-rootcoord-dml_0_446465103651979208v0: channel not found"] [errorVerbose="failed to get shard delegator: channel=by-dev-rootcoord-dml_0_446465103651979208v0: channel not found\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrChannelNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:490\n  | [...repeated from below...]\nWraps: (2) failed to get shard delegator\nWraps: (3) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.wrapWithField\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:760\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrChannelNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:488\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).checkSegmentTaskStale\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:802\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).checkStale\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:741\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).check\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:664\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).promote\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:427\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).tryPromoteAll.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:390\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskQueue).Range\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:121\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).tryPromoteAll\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:389\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).schedule\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:529\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).Dispatch\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:445\n  | github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).handleDistResp\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:110\n  | github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:86\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (4) channel=by-dev-rootcoord-dml_0_446465103651979208v0\nWraps: (5) channel not found\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) merr.milvusError"]
[2024/03/20 07:45:37.856 +00:00] [WARN] [task/scheduler.go:394] ["failed to promote task"] [taskID=1710904694733] [error="failed to get shard delegator: channel=by-dev-rootcoord-dml_0_446465103651979208v0: channel not found"] [errorVerbose="failed to get shard delegator: channel=by-dev-rootcoord-dml_0_446465103651979208v0: channel not found\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrChannelNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:490\n  | [...repeated from below...]\nWraps: (2) failed to get shard delegator\nWraps: (3) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.wrapWithField\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:760\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrChannelNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:488\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).checkSegmentTaskStale\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:802\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).checkStale\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:741\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).check\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:664\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).promote\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:427\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).tryPromoteAll.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:390\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskQueue).Range\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:121\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).tryPromoteAll\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:389\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).schedule\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:529\n  | github.com/milvus-io/milvus/internal/querycoordv2/task.(*taskScheduler).Dispatch\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/task/scheduler.go:445\n  | github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).handleDistResp\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:110\n  | github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n  | \t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:86\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (4) channel=by-dev-rootcoord-dml_0_446465103651979208v0\nWraps: (5) channel not found\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) merr.milvusError"]

**dataNode：**

[2024/03/19 14:04:08.081 +00:00] [WARN] [datanode/event_manager.go:175] ["handle put event: new data sync service failed"] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0] [error="stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:515 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:529 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:102 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:272 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetSegmentInfo\n/go/src/github.com/milvus-io/milvus/internal/datanode/broker/datacoord.go:68 github.com/milvus-io/milvus/internal/datanode/broker.(*dataCoordBroker).GetSegmentInfo\n/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:420 github.com/milvus-io/milvus/internal/datanode.newServiceWithEtcdTickler\n/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:131 github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStartWithEtcdTickler\n/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:174 github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:262 github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1: attempt #0: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #1: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #2: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #3: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #4: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #5: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #6: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #7: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #8: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #9: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912)"] [errorVerbose="stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace: attempt #0: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #1: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #2: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #3: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #4: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #5: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #6: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #7: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #8: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #9: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912)\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:515\n  | [...repeated from below...]\nWraps: (2) stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n  | /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:515 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:529 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:102 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n  | /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:272 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetSegmentInfo\n  | /go/src/github.com/milvus-io/milvus/internal/datanode/broker/datacoord.go:68 github.com/milvus-io/milvus/internal/datanode/broker.(*dataCoordBroker).GetSegmentInfo\n  | /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:420 github.com/milvus-io/milvus/internal/datanode.newServiceWithEtcdTickler\n  | /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:131 github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStartWithEtcdTickler\n  | /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:174 github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n  | /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:262 github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\nWraps: (3) attempt #0: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #1: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #2: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #3: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #4: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #5: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #6: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #7: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912): attempt #8: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912)\nWraps: (4) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/retry.Do\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:49\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:429\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:513\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:529\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:102\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetSegmentInfo\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:272\n  | github.com/milvus-io/milvus/internal/datanode/broker.(*dataCoordBroker).GetSegmentInfo\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/broker/datacoord.go:68\n  | github.com/milvus-io/milvus/internal/datanode.newServiceWithEtcdTickler\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:420\n  | github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStartWithEtcdTickler\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:131\n  | github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:174\n  | github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:262\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (5) attempt #9\nWraps: (6) rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (995701238 vs. 536870912)\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.multiErrors (4) *withstack.withStack (5) *errutil.withPrefix (6) *status.Error"]
[2024/03/19 14:04:08.084 +00:00] [INFO] [datanode/event_manager.go:203] ["handle put event: failed to compare version and swap, release flowgraph"] [key=channelwatch/1913/by-dev-rootcoord-dml_0_446465103651979208v0] [state=WatchFailure] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.084 +00:00] [INFO] [datanode/data_node.go:287] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.084 +00:00] [INFO] [datanode/data_node.go:287] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.085 +00:00] [INFO] [datanode/event_manager.go:203] ["handle put event: failed to compare version and swap, release flowgraph"] [key=channelwatch/1913/by-dev-rootcoord-dml_0_446465103651979208v0] [state=ReleaseSuccess] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.085 +00:00] [INFO] [datanode/data_node.go:287] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.085 +00:00] [INFO] [datanode/data_node.go:287] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.087 +00:00] [INFO] [datanode/event_manager.go:210] ["handle put event success"] [key=channelwatch/1913/by-dev-rootcoord-dml_0_446465103651979208v0] [state=ReleaseSuccess] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.088 +00:00] [INFO] [datanode/event_manager.go:112] ["DataNode received a PUT event with an end State"] [state=ReleaseSuccess]
[2024/03/19 14:04:08.095 +00:00] [INFO] [datanode/event_manager.go:126] ["DataNode is handling watchInfo DELETE event"] [key=by-dev/meta/channelwatch/1913/by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.096 +00:00] [INFO] [datanode/data_node.go:287] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.432 +00:00] [WARN] [datanode/services.go:269] ["illegel compaction plan, channel not in this DataNode"] [channelName=by-dev-rootcoord-dml_0_446465103651979208v0]
[2024/03/19 14:04:08.436 +00:00] [WARN] [datanode/services.go:269] ["illegel compaction plan, channel not in this DataNode"] [channelName=by-dev-rootcoord-dml_0_446465103651979208v0]

### Anything else?

What is the reason for this problem? And how can I make this collection load properly?

**Comment by yanliang567** [comment] 2024-03-21 01:14
@charleskangzq Could you please release and reload this collection to reproduce the issue, and then refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? Also share the collection name is helpful for us to find the related logs in the log files.

/assign @charleskangzq

**Comment by xiaofan-luan** [comment] 2024-03-22 21:00
@charleskangzq 
the reason is rpc limited exceed grpc max limit

There are two way to solve the issue:
1. tune grpc parameter and increate the rpc size limit 
2. upgrade to milvus 2.2.12. We add compression on this which reduce the size of each rpc to 10-100 times

**Comment by xiaofan-luan** [comment] 2024-03-22 21:00
/assign @charleskangzq 
but you also need to check why there are so many segments under your use case

**Comment by charleskangzq** [comment] 2024-03-25 07:03
@xiaofan-luan 

I have tried to tune grpc parameter and increate the rpc size limit , but dataCoord can not start up correctly , the dataCoord log indicated that fetch meta from etcd timeout and retry Infinitely .

Upgrading milvus to 2.3.12  works for my case

**Comment by charleskangzq** [comment] 2024-03-25 07:11
@xiaofan-luan 

Users do lots of upsert and flush operations and configure collection consistency level to strong . Is this the reason for the large number of segments?  

If so , please give me some advices to aviod this case 

Thanks for your reply

**Comment by xiaofan-luan** [comment] 2024-03-25 17:10
> @xiaofan-luan
> 
> Users do lots of upsert and flush operations and configure collection consistency level to strong . Is this the reason for the large number of segments?
> 
> If so , please give me some advices to aviod this case
> 
> Thanks for your reply

Avoid doing flush operations manually is key to keep the meta small.

Compaction will eventually solve this problem, but sometimes it doesn't catch up the frequency of flush .

And to be mentioned, you see all data you inserted in strong consistency. Doesn't really make to do flush. The only valid flush use case is when you want to clean shutdown the cluster or rolling upgrade

**Comment by yanliang567** [comment] 2024-04-02 06:25
i'd close this issue for coments above

**Closed by yanliang567** 2024-04-02 06:25 UTC
Labels: kind/bug, triage/needs-information
