### ISSUE TITLE
Disk is still in use after milvus server docker stoped and removed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1266] opened 2020-02-19 04:13 UTC
**Describe the bug**
Disk space is full after vectors added into server table, but disk space is still in use after milvus server docker stoped and removed.

Before `docker stop && docker rm`:
```
/dev/sda4             1716083204  1623881180     4959992 100% /home
```
After `docker stop && docker rm`:
```
/dev/sda4             1.6T   17G  1.6T   2% /home
```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
branch: crud 

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment] 2020-02-25 14:43
Maybe it is caused by not closing after open the file. You can try to reproduce it now.

**Comment by del-zhenwu** [comment] 2020-03-23 02:44
in-regression

**Comment by shengjun1985** [comment] 2020-12-08 01:49
Inactive. Close.

**Closed by shengjun1985** 2020-12-08 01:49 UTC
Labels: Bug, Bug | Severity | S3
