### ISSUE TITLE
Failed in compile process

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2176] opened 2020-04-29 01:40 UTC
**Describe the bug**
```
[2020-04-28T16:22:01.178Z] /home/jenkins/agent/workspace/milvus-ci_master/core/src/metrics/SystemInfo.cpp:18:10: fatal error: fiu-local.h: No such file or directory
[2020-04-28T16:22:01.179Z]  #include <fiu-local.h>
[2020-04-28T16:22:01.180Z]           ^~~~~~~~~~~~~
[2020-04-28T16:22:01.180Z] compilation terminated.
[2020-04-28T16:22:01.180Z] make[2]: *** [src/CMakeFiles/metrics.dir/metrics/SystemInfo.cpp.o] Error 1
[2020-04-28T16:22:01.180Z] make[1]: *** [src/CMakeFiles/metrics.dir/all] Error 2
[2020-04-28T16:22:01.180Z] make[1]: *** Waiting for unfinished jobs....
```

**Steps/Code to reproduce behavior**
http://internal.zilliz.com:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-ci/branches/master/runs/504/nodes/16/steps/147/log/?start=0

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment] 2020-04-29 10:33
Duplicate of #2086

**Closed** 2020-05-07 03:23 UTC
Labels: Bug
