### ISSUE TITLE
python SDK hang up when searching occassionally

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1792] opened 2020-03-28 12:47 UTC
**Describe the bug**
CI or QPS test with pymilvus, sometimes the python client can't connect server. Meanwhile, C++ client never happened before.

**Steps/Code to reproduce behavior**
Use the QPS tool to do the test.

**Comment by JinHai-CN** [comment] 2020-03-28 12:47
@tinkerlin Please provide how to use QPS to reproduce the issue.

**Comment by BossZou** [comment] 2020-03-30 02:15
May you provide more information in details， I need to reproduce ths issue. @tinkerlin

**Comment by tinkerlin** [comment] 2020-03-30 08:37
```
clone https://github.com/tinkerlin/milvus-qps-test.git
python run.py --suite=suites/example_suite.yaml --runs=100 --clients=5
```

**Comment by BossZou** [comment] 2020-04-01 03:20
I try to run qps shell and get output:
```
<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1585708918.370756324","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
[2020-04-01 10:41:58.371193] | [26340] Search done.
[2020-04-01 10:41:58.371210] | [26340] Start search ...
[2020-04-01 10:41:58.371422] | [26337] Search done.
[2020-04-01 10:41:58.371446] | [26337] Start search ...
<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1585708918.371139676","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
```
Then the procedure hand up for searching ...
I doubt that the grpc channel for connection has been broken. And I'll find out the reason further.

**Comment by BossZou** [comment] 2020-04-01 06:37
May the client call stack help:
```
^CProcess Process-27:
Process Process-30:
Process Process-28:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/yhz/Projects/Git/GitHub/milvus-qps-test/milvus_observer/runner.py", line 146, in run_single_query_process
    connect.query(query, search_param["topk"], search_param=search_param)
  File "/home/yhz/Projects/Git/GitHub/milvus-qps-test/milvus_observer/client.py", line 154, in query
    self._milvus.search_vectors(self._collection_name, top_k, query_records=X, params=search_param)
  File "/home/yhz/Environments/qps-env/lib/python3.6/site-packages/milvus/client/stub.py", line 16, in wrapper
    raise NotConnectError('Please connect to the server first')
milvus.client.exceptions.NotConnectError: Please connect to the server first
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yhz/Projects/Git/GitHub/milvus-qps-test/milvus_observer/runner.py", line 131, in run_paralle_process
    data = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
milvus.client.exceptions.NotConnectError: Please connect to the server first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    main.main()
  File "/home/yhz/Projects/Git/GitHub/milvus-qps-test/milvus_observer/main.py", line 111, in main
    run(definition, args.clients, args.runs, args.batch, args.searchonly)
  File "/home/yhz/Projects/Git/GitHub/milvus-qps-test/milvus_observer/runner.py", line 62, in run
    search_params, collection_scheme["collection_name"], connection_num, X_test, run_count, batch)
  File "/home/yhz/Projects/Git/GitHub/milvus-qps-test/milvus_observer/runner.py", line 133, in run_paralle_process
    max_runs = max_runs if max_runs > runs else runs
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 611, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 506, in shutdown
    self._queue_management_thread.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
KeyboardInterrupt
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by BossZou** [comment] 2020-04-07 10:07
In python SDK connectin handler Change to manual release the future of gRPC bying call `future.__del__()`。 During the test, I found error could occur in milvus server either server crash in the situation of (#1832 )[https://github.com/milvus-io/milvus/issues/1832] or gRPC in server stop working and not respond any request (more detail logging above).
-----------------------------------------------------------------------------------------------
This issue will be closed. Please reopen it if any problem here

**Comment by tinkerlin** [comment] 2020-04-07 10:16
need regression test

**Comment by del-zhenwu** [comment] 2020-04-09 13:18
close it

**Closed by del-zhenwu** 2020-04-09 13:18 UTC
Labels: Bug, P2, S2
