### ISSUE TITLE
[Bug]: Milvus Stoped Index building

### ISSUE THREAD

**Issue by akmalmasud96** [milvus-io/milvus#35594] opened 2024-08-20 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Cluster Mode Version 2.3.20 and Standalone Mode Version 2.4.6
- Deployment mode(standalone or cluster): Both
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

I am making diskann index with 256 vector size. This issue is being faced on the cluster mode milvus and also on the standalone milvus. All the cores in index node for the cluster mode are kept in use, however, it stop indexing with the attached error. 
it is working fine for other collections on which I am making with diskann-indexes  for the size of 512 embedding-size. What could be the issue ? What could be the issue ?

### Milvus Log

Milvus Cluster Mode logs
```
20240807 14:06:45.351478    45 ChunkManagers.cpp:112] [SEGCORE][AwsChunkManager][milvus] init AwsChunkManager with parameter[endpoint: '[s3.us-east-1.amazonaws.com:443](http://s3.us-east-1.amazonaws.com:443/)', default_bucket_name:'milvus-cluster-bucket-v2', root_path:'milvus_data', use_secure:'true']
I20240807 14:06:45.351606    45 factory.cc:20] [KNOWHERE][Create][milvus] create knowhere index DISKANN with version 1
I20240807 14:06:45.829555    45 aux_utils.cpp:1160] [KNOWHERE][build_disk_index][milvus] Using Cosine search, so need to pre-process base data into temp file. Please ensure there is additional (nd4) bytes for storing pre-processed base vectors, apart from the intermin indices and final index.
I20240807 14:06:45.831759    45 aux_utils.cpp:1190] [KNOWHERE][build_disk_index][milvus] Starting index build: R=56 L=100 Query RAM budget: 0.000149(GiB) Indexing ram budget: 24.6064(GiB)
I20240807 14:06:45.831789    45 aux_utils.cpp:1208] [KNOWHERE][build_disk_index][milvus] Compressing 256-dimensional data into 128 bytes per vector.
E20240807 14:06:45.833606    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833616    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833618    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833622    45 partition_and_pq.cpp:211] error in copy
I20240807 14:06:45.833458    45 aux_utils.cpp:1249] [KNOWHERE][build_disk_index][milvus] Generating PQ pivots
E20240807 14:06:45.833626    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833628    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833631    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833635    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833638    45 partition_and_pq.cpp:211] error in copy
E20240807 14:06:45.833649    45 partition_and_pq.cpp:211] error in copy
```

Standalone Mode logs,

```
[indexnode/task.go:516] [\"index params are ready\"] [buildID=451892472924565981] [\"index params\"=\"{\\\"build_dram_budget_gb\\\":\\\"125.129562\\\",\\\"dim\\\":\\\"256\\\",\\\"index_type\\\":\\\"DISKANN\\\",\\\"max_degree\\\":\\\"56\\\",\\\"metric_type\\\":\\\"COSINE\\\",\\\"num_build_thread\\\":\\\"32\\\",\\\"num_build_thread_ratio\\\":\\\"1\\\",\\\"pq_code_budget_gb\\\":\\\"0.000178\\\",\\\"pq_code_budget_gb_ratio\\\":\\\"0.125\\\",\\\"search_cache_budget_gb\\\":\\\"0.000143\\\",\\\"search_cache_budget_gb_ratio\\\":\\\"0.100000\\\",\\\"search_list_size\\\":\\\"100\\\"}\"]\n","stream":"stdout","time":"2024-08-17T13:32:47.067386179Z"}
{"log":"I20240817 13:32:47.067938 21587 MinioChunkManager.cpp:225] [SERVER][PreCheck][milvus] start to precheck chunk manager with configuration: [address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=warn, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\n","stream":"stdout","time":"2024-08-17T13:32:47.068092611Z"}
{"log":"I20240817 13:32:47.070744 21587 ChunkManager.cpp:112] [SERVER][AwsChunkManager][milvus] init AwsChunkManager with parameter[endpoint=minio:9000][bucket_name=a-bucket][root_path=files][use_secure=false]\n","stream":"stdout","time":"2024-08-17T13:32:47.070844609Z"}
{"log":"I20240817 13:32:47.071208 21587 index_factory.cc:54] [KNOWHERE][Create][milvus] use key DISKANN_fp32 to create knowhere index DISKANN with version 4\n","stream":"stdout","time":"2024-08-17T13:32:47.071311724Z"}
{"log":"I20240817 13:32:47.115267 21587 aux_utils.cpp:1124] [KNOWHERE][build_disk_index][milvus] Using Cosine search, so need to pre-process base data into temp file. Please ensure there is additional (nd4) bytes for storing pre-processed base vectors, apart from the intermin indices and final index.\n","stream":"stdout","time":"2024-08-17T13:32:47.115462925Z"}
{"log":"I20240817 13:32:47.118752 21587 aux_utils.cpp:1154] [KNOWHERE][build_disk_index][milvus] Starting index build: R=56 L=100 Query RAM budget: 0.000178(GiB) Indexing ram budget: 125.13(GiB)\n","stream":"stdout","time":"2024-08-17T13:32:47.118892311Z"}
{"log":"I20240817 13:32:47.118821 21587 aux_utils.cpp:1172] [KNOWHERE][build_disk_index][milvus] Compressing 256-dimensional data into 127 bytes per vector.\n","stream":"stdout","time":"2024-08-17T13:32:47.118911734Z"}
{"log":"I20240817 13:32:47.123124 21587 aux_utils.cpp:1213] [KNOWHERE][build_disk_index][milvus] Generating PQ pivots\n","stream":"stdout","time":"2024-08-17T13:32:47.123244268Z"}
{"log":"E20240817 13:32:47.123667 21587 partition_and_pq.cpp:209] error in copy\n","stream":"stderr","time":"2024-08-17T13:32:47.123766222Z"}
{"log":"E20240817 13:32:47.123688 21587 partition_and_pq.cpp:209] error in copy\n","stream":"stderr","time":"2024-08-17T13:32:47.123781835Z"}
{"log":"E20240817 13:32:47.123693 21587 partition_and_pq.cpp:209] error in copy\n","stream":"stderr","time":"2024-08-17T13:32:47.12378496Z"}
{"log":"E20240817 13:32:47.123698 21587 partition_and_pq.cpp:209] error in copy\n","stream":"stderr","time":"2024-08-17T13:32:47.123787732Z"
```

**Comment by yanliang567** [comment] 2024-08-20 09:17
/assign @liliu-z 
please help to take a look
/unassign

**Comment by xiaofan-luan** [comment] 2024-08-21 19:10
@akmalmasud96 
what is your index parameter?

Compressing 256-dimensional data into 127 byte
usually it's 128byte

**Comment by xiaofan-luan** [comment] 2024-08-21 19:10
how to you create your index?

**Comment by liliu-z** [comment] 2024-08-22 02:10
/assign @cydrain 

Plz help to take a look

**Comment by cydrain** [comment] 2024-08-22 02:36
working on it

**Comment by cydrain** [comment] 2024-08-22 02:48
Hi @akmalmasud96 ,

Could you show me your script and parameters to create the index ?

**Comment by akmalmasud96** [comment] 2024-08-22 05:29
Hi @cydrain @xiaofan-luan, 
I am using the default parameters for DISKANN with cosine similarity, 

```

 def _create_index(self):
        index_params = {
            "index_type": "DISKANN",
            "metric_type": "COSINE",
            "params": {}
        }

        self.collection.create_index(
            field_name="embeddings",
            index_params=index_params,
            index_name=f"{self.collection_name}_index"
        )
        
```

**Comment by cydrain** [comment] 2024-08-22 09:42
Hi @akmalmasud96 ,

The most likely scenario is that there are illegal values in the inserted vector data.
Although Milvus checks for nan and inf in vector data, it is likely that other illegal data has been overlooked.

Could you show us the inserted vector data ?

**Comment by akmalmasud96** [comment] 2024-08-22 10:51
@cydrain, I have tried the flat index, and it’s working for those vectors. 
I can share the vectors with you—I have them in a standalone Milvus instance. How can I share them with you?

**Comment by cydrain** [comment] 2024-08-22 11:09
Hi @akmalmasud96 , 

Where is the vector data before insert them into Milvus ?
Can you save them into a json (or numpy / parquet) file, and send this file to me ?

**Comment by akmalmasud96** [comment] 2024-08-22 11:21
@cydrain, it’s only available in the milvus.
I am taking inference from the model and storing them into the milvus.

**Comment by xiaofan-luan** [comment] 2024-08-22 20:32
> Compressing 256-dimensional data into 127 bytes per vecto

Compressing 256-dimensional data into 127 bytes per vector -> is that correct?

**Comment by xiaofan-luan** [comment] 2024-08-22 20:32
I thought it will be 128 bytes or something @cydrain

**Comment by akmalmasud96** [comment] 2024-08-22 21:25
@cydrain, I have retrieved the vectors from Milvus and saved them in a NumPy file, which you can access from here. [Drive Link](https://drive.google.com/file/d/131qEilUPgg5ZdWW1gKCYRVu4qG9Ayxh2/view?usp=sharing)

**Comment by cydrain** [comment] 2024-08-23 02:16
> @cydrain, I have retrieved the vectors from Milvus and saved them in a NumPy file, which you can access from here. [Drive Link](https://drive.google.com/file/d/131qEilUPgg5ZdWW1gKCYRVu4qG9Ayxh2/view?usp=sharing)

get it

**Comment by cqy123456** [comment] 2024-08-23 06:41
diskann uses pq_code_budget_gb(0.000178GB) to generate pq codes size. The calculated pq code may be slightly different if this value is too small(cluster uses 128 bytes and standalone uses 127 bytes in this case).

**Comment by cydrain** [comment] 2024-08-23 09:08
Hi @akmalmasud96 ,

It's confirmed that this issue is caused by illegal vector data, like following
```
E20240823 15:18:31.059731 3338202 partition_and_pq.cpp:209] error in copy, (50, 254) -nan vs. -nan (0xffc00000)
E20240823 15:18:31.059739 3338202 partition_and_pq.cpp:209] error in copy, (50, 255) -nan vs. -nan (0xffc00000)
E20240823 15:18:31.060035 3338202 partition_and_pq.cpp:209] error in copy, (968, 0) -nan vs. -nan (0xffc00000)
E20240823 15:18:31.060052 3338202 partition_and_pq.cpp:209] error in copy, (968, 1) -nan vs. -nan (0xffc00000)
```

**Comment by cydrain** [comment] 2024-08-23 10:26
This issue is caused by the different interpretation of float value (0xffc00000) between C++ and go.

According to the definition of float type in IEEE 754 standard, 0 bit are sign bit, 1~8 bits refer to exponent bits, and 9~31 bits are fraction bits.
The definition of some special values is as follows:
NaN (Not a Number): When the exponent bits are all 1 and the fraction bits are not all 0, it represents NaN. NaN represents undefined or unrepresentative numerical values.

According to the above definition, C++ interprets 0xffc00000 to nan, and for the value of nan, it satisfies "nan != nan".
That's why we see "error in copy" in partition_and_pq.cpp:209.

But in go language, float32 0xffc00000 is interpreted as 0, so it passed the check of API VerifyFloat() in float_util.go

**Comment by cydrain** [comment] 2024-08-23 10:40
> @cydrain How are you defining the vectors to be illegal ? Are there nan values in the vectors ?

Hi @akmalmasud96 , 
Based on the definition of IEEE 754 standard, 0xffc00000 is interpreted as Nan for float data type.
in the file vectors.npy, I see following rows are all with value 0xffc00000 (line No. 50, 968, 1395, 1771, ...... )

**Comment by akmalmasud96** [comment] 2024-08-23 11:40
@cydrain 
All these indices are 0.0 values for all 256 np.float32 dimensions in this numpy format. Though I will check what is the reason why model is giving 0.0. 
But I dont think that this should be issue for indexing, or these values should be said as nan.

**Comment by xiaofan-luan** [comment] 2024-08-23 22:13
> float_util.go

<img width="1292" alt="image" src="https://github.com/user-attachments/assets/7f07f1f3-a84b-47e4-98b6-ed98db413fa3">

**Comment by xiaofan-luan** [comment] 2024-08-23 22:14
0xffc00000 is a invalid float in go as well

**Comment by xiaofan-luan** [comment] 2024-08-23 22:39
I guess this is a file bulkinserted from json format or csv format and it lacks of nan check

**Comment by xiaofan-luan** [comment] 2024-08-25 17:36
this could be potentially fixed by #35683 by adding some check.

But we still need this to be fixed by index side

**Comment by cydrain** [comment] 2024-08-26 05:02
Make corr

**Comment by cydrain** [comment] 2024-08-26 09:36
the backtrace of float vector validation check is as following:
![Screenshot from 2024-08-26 17-35-18](https://github.com/user-attachments/assets/1815d06c-7c1e-4325-bda8-5aa74d84b113)

**Comment by akmalmasud96** [comment] 2024-08-26 11:32
> I guess this is a file bulkinserted from json format or csv format and it lacks of nan check

@xiaofan-luan I want to mention here that the bulk insert is not used.

**Comment by xiaofan-luan** [comment] 2024-08-26 22:40
> > I guess this is a file bulkinserted from json format or csv format and it lacks of nan check
> 
> @xiaofan-luan I want to mention here that the bulk insert is not used.

Cydrain find with all 0 embeddings we get into same issue because try to normalize an all 0 embeddings will cause nan

**Comment by akmalmasud96** [comment] 2024-08-27 12:14
Hi @cydrain @xiaofan-luan,

I figured out that why zero was coming in the embeddings. Those are the part of our pipeline that for some scenarios zeros will be the embeddings. 
I also want to raise another thing that if there is some issue in the index-building in any one of the collection, then the indexing got stopped for all the collections.
I faced this issue in the production environment, in cluster mode.

**Comment by xiaofan-luan** [comment] 2024-08-27 18:14
> Hi @cydrain @xiaofan-luan,
> 
> I figured out that why zero was coming in the embeddings. Those are the part of our pipeline that for some scenarios zeros will be the embeddings. I also want to raise another thing that if there is some issue in the index-building in any one of the collection, then the indexing got stopped for all the collections. I faced this issue in the production environment, in cluster mode.

You need to drop this index or cancel the current index building task.

Because index is first in first out so the blocking might happen I guess. We can not handle it manually (If stop retry then we lost some data I guess)

**Comment by cydrain** [comment] 2024-08-28 03:03
diskann repo has removed this check
![Screenshot from 2024-08-28 11-02-48](https://github.com/user-attachments/assets/02a1c3f0-123d-480b-ab4d-2cb3da62f64f)

**Comment by cydrain** [comment] 2024-09-27 09:21
/assign @yanliang567 
this issue has been fixed, please verify and close it

**Comment by yanliang567** [comment] 2024-09-27 09:29
@cydrain do we have test to cover this scenario in knowhere?

**Closed** 2024-09-27 13:22 UTC
Labels: kind/bug, needs-triage
