### ISSUE TITLE
[FEATURE]Print error log when run coverage.sh

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/milvus#446] opened 2019-11-21 02:51 UTC
**Is your feature request related to a problem? Please describe.**
Currently we only print debug log while running coverage.sh, it's difficult for us to figure out where the problem is when coverage.sh failed.

**Describe the solution you'd like**
Look how debug log is printed, using the same way to print error log

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ZhifengZhang-CN** [comment] 2019-11-21 02:59
Duplicate of #427

**Comment by JinHai-CN** [comment] 2020-03-01 06:20
Duplicate

**Closed** 2020-03-01 06:20 UTC
Labels: good first issue
