### ISSUE TITLE
[Bug]: [Nightly]Search failed with an unexpected error 'User Field(int64) is not loaded'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22910] opened 2023-03-22 02:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: f2ffb5d
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed with an unexpected error 'User Field(int64) is not loaded'.
```
[2023-03-21T19:28:41.312Z] [2023-03-21 19:17:01 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 3 failed, reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:625
[2023-03-21T19:28:41.312Z]  err %!w(<nil>))>, <Time:{'RPC start': '2023-03-21 19:17:00.693876', 'RPC error': '2023-03-21 19:17:01.025728'}> (decorators.py:108)
[2023-03-21T19:28:41.312Z] [2023-03-21 19:17:01 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-21T19:28:41.312Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-21T19:28:41.312Z]     res = func(*args, **_kwargs)
[2023-03-21T19:28:41.312Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-21T19:28:41.312Z]     return func(*arg, **kwargs)
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 660, in search
[2023-03-21T19:28:41.312Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-21T19:28:41.312Z]     raise e
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-21T19:28:41.312Z]     return func(*args, **kwargs)
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-21T19:28:41.312Z]     ret = func(self, *args, **kwargs)
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-03-21T19:28:41.312Z]     raise e
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-21T19:28:41.312Z]     return func(self, *args, **kwargs)
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
[2023-03-21T19:28:41.312Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
[2023-03-21T19:28:41.312Z]     raise pre_err
[2023-03-21T19:28:41.312Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
[2023-03-21T19:28:41.313Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-03-21T19:28:41.313Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 3 failed, reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:625
[2023-03-21T19:28:41.313Z]  err %!w(<nil>))>
[2023-03-21T19:28:41.313Z]  (api_request.py:39)
[2023-03-21T19:28:41.313Z] [2023-03-21 19:17:01 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 3 failed, reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:6...... (api_request.py:40)
```

### Expected Behavior

succeed

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/318/pipeline/155
2. log: [artifacts-milvus-distributed-kafka-nightly-318-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/318/artifact/artifacts-milvus-distributed-kafka-nightly-318-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_fOBYmzWj
4. failed time: [2023-03-21T19:17:02.061Z] [gw2] [ 87%] FAILED testcases/test_search.py::TestCollectionRangeSearch::test_range_search_with_expression[128-False-float <= 4**5/2 && float > 500-1 && float != 500/2+260]

**Comment by NicoYuan1986** [comment] 2023-03-22 02:22
The other two errors seem to be for the same reason.

1. cluster-pulsar:
[2023-03-21T19:00:50.852Z] [gw4] [ 70%] FAILED testcases/test_search.py::TestSearchPagination::test_search_pagination_with_index_partition[100-True-True-11] 
```
[2023-03-21T19:35:11.886Z] self = <pymilvus.client.asynch.ChunkedSearchFuture object at 0x7fd1c53da340>
[2023-03-21T19:35:11.886Z] response = [status {
[2023-03-21T19:35:11.886Z]   error_code: UnexpectedError
[2023-03-21T19:35:11.886Z]   reason: "fail to search on all shard leaders, err=fail to Search, QueryNode ...aded\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:491\n err %!w(<nil>)"
[2023-03-21T19:35:11.886Z] }
[2023-03-21T19:35:11.886Z] ]
[2023-03-21T19:35:11.886Z] 
[2023-03-21T19:35:11.886Z]     def on_response(self, response):
[2023-03-21T19:35:11.886Z]         for raw in response:
[2023-03-21T19:35:11.886Z]             if raw.status.error_code != 0:
[2023-03-21T19:35:11.886Z] >               raise MilvusException(raw.status.error_code, raw.status.reason)
[2023-03-21T19:35:11.886Z] E               pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=6, reason=Search 6 failed, reason [UnexpectedError] Assert "User Field(int64) is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:491
[2023-03-21T19:35:11.887Z] E                err %!w(<nil>))>
```

3. standalone:
[2023-03-21T18:44:46.913Z] [gw2] [ 60%] FAILED testcases/test_search.py::TestSearchBase::test_search_ip_after_index[DISKANN-params6] 
```
[2023-03-21T19:34:26.923Z] [2023-03-21 18:44:46 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "User Field(int64) is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:491
[2023-03-21T19:34:26.923Z]  err %!w(<nil>))>, <Time:{'RPC start': '2023-03-21 18:44:45.744277', 'RPC error': '2023-03-21 18:44:46.135306'}> (decorators.py:108)
[2023-03-21T19:34:26.923Z] [2023-03-21 18:44:46 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-21T19:34:26.923Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-21T19:34:26.923Z]     res = func(*args, **_kwargs)
[2023-03-21T19:34:26.923Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-21T19:34:26.923Z]     return func(*arg, **kwargs)
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 660, in search
[2023-03-21T19:34:26.923Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-21T19:34:26.923Z]     raise e
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-21T19:34:26.923Z]     return func(*args, **kwargs)
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-21T19:34:26.923Z]     ret = func(self, *args, **kwargs)
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-03-21T19:34:26.923Z]     raise e
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-21T19:34:26.923Z]     return func(self, *args, **kwargs)
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
[2023-03-21T19:34:26.923Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
[2023-03-21T19:34:26.923Z]     raise pre_err
[2023-03-21T19:34:26.923Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
[2023-03-21T19:34:26.923Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-03-21T19:34:26.923Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "User Field(int64) is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:491
[2023-03-21T19:34:26.923Z]  err %!w(<nil>))>
[2023-03-21T19:34:26.923Z]  (api_request.py:39)
[2023-03-21T19:34:26.923Z] [2023-03-21 18:44:46 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "User Field(int64) is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:491
[2023-03-21T19:34:26.923Z]  err %!w(<n...... (api_request.py:40)
```

**Comment by binbinlv** [comment] 2023-03-22 03:06
This maybe duplicate of issue #22902

**Closed** 2023-03-24 02:32 UTC
Labels: kind/bug
