### ISSUE TITLE
Create index failed with type: HNSW

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1232] opened 2020-02-15 10:34 UTC
**Describe the bug**
```

[2020-02-15T10:21:30.183Z] ip_table = 'test_5MwQ4AYM'

[2020-02-15T10:21:30.183Z] get_simple_index_params = {'index_type': <IndexType: HNSW>, 'nlist': 1024}

[2020-02-15T10:21:30.183Z] 

[2020-02-15T10:21:30.183Z]     def test_drop_index(self, connect, ip_table, get_simple_index_params):

[2020-02-15T10:21:30.183Z]         '''

[2020-02-15T10:21:30.183Z]         target: test drop index interface

[2020-02-15T10:21:30.183Z]         method: create table and add vectors in it, create index, call drop index

[2020-02-15T10:21:30.183Z]         expected: return code 0, and default index param

[2020-02-15T10:21:30.183Z]         '''

[2020-02-15T10:21:30.183Z]         index_params = get_simple_index_params

[2020-02-15T10:21:30.183Z]         status, mode = connect._cmd("mode")

[2020-02-15T10:21:30.183Z]         assert status.OK()

[2020-02-15T10:21:30.183Z]         # status, ids = connect.add_vectors(ip_table, vectors)

[2020-02-15T10:21:30.183Z]         status = connect.create_index(ip_table, index_params)

[2020-02-15T10:21:30.183Z]         if str(mode) == "GPU" and (index_params["index_type"] == IndexType.IVF_PQ):

[2020-02-15T10:21:30.183Z]             assert not status.OK()

[2020-02-15T10:21:30.183Z]         else:

[2020-02-15T10:21:30.183Z] >           assert status.OK()

[2020-02-15T10:21:30.183Z] E           AssertionError: assert False

[2020-02-15T10:21:30.183Z] E            +  where False = <bound method Status.OK of Status(code=8, message='Invalid index type: 11. Make sure the index type is in IndexType list.')>()

[2020-02-15T10:21:30.183Z] E            +    where <bound method Status.OK of Status(code=8, message='Invalid index type: 11. Make sure the index type is in IndexType list.')> = Status(code=8, message='Invalid index type: 11. Make sure the index type is in IndexType list.').OK
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment] 2020-02-18 04:31
I guess you have used milvus server compiled from crud branch, and this branch do not support index `HNSW`.

The issue is closing. Reopen if you have other question.

**Closed by BossZou** 2020-02-18 04:31 UTC
Labels: sdk/python, type/bug
