### ISSUE TITLE
[Bug]: Load failed after upgrading milvus cluster

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#13616] opened 2021-12-17 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: RC8 --> bf6405c
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.0rc8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
  File "scripts/action_after_upgrade.py", line 35, in <module>
    task_2()
  File "scripts/action_after_upgrade.py", line 27, in task_2
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 140, in load_and_search
    c.load()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 448, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 325, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 813, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=some partitions [429844918879649794] of collection 429844918879649793 has been loaded into QueryNode, please release partitions firstly)>
```

### Expected Behavior

all operations work well

### Steps To Reproduce

```markdown
You can check this link https://github.com/zhuwenxing/milvus/runs/4557732055?check_suite_focus=true for more information

first deployment

 helm repo add milvus https://milvus-io.github.io/milvus-helm
  helm repo update
  
  # if the task is reinstall, install milvus with latest image in repo milvusdb/milvus-dev
  if [ upgrade == "reinstall" ]; then helm install --wait --timeout 720s deploy-testing milvus/milvus -f cluster-values.yaml; fi
  
  # if the task is upgrade, install milvus with latest rc image in repo milvusdb/milvus
  if [ upgrade == "upgrade" ]; then helm install --wait --timeout 720s deploy-testing milvus/milvus --set image.all.repository=milvusdb/milvus --set image.all.tag=latest -f cluster-values.yaml; fi
  kubectl get pods
  sleep 20s
  kubectl get pods
  kubectl port-forward service/deploy-testing-milvus 19530 >/dev/null 2>&1 &
  sleep 20s
  # check whether port-forward success
  nc -vz 127.0.0.1 19530
  
  # first test
  if [ upgrade == "reinstall" ]; then python scripts/action_before_reinstall.py; fi
  if [ upgrade == "upgrade" ]; then python scripts/action_before_upgrade.py; fi
  
  
  # uninstall milvus
  if [[ $(date +%w) -eq 0 || $(data +%w) -eq 6 ]]; then sleep 1800s; fi
  helm uninstall deploy-testing
```

second deployment
```
 helm install --wait --timeout 720s deploy-testing milvus/milvus -f cluster-values.yaml
  kubectl get pods
  sleep 20s
  kubectl get pods
  ps aux|grep forward|grep -v grep|awk '{print $2}'|xargs kill -9
  kubectl port-forward service/deploy-testing-milvus 19530 >/dev/null 2>&1 &
  sleep 20s
  # check whether port-forward success
  nc -vz 127.0.0.1 19530
  
  # second test
  if [ upgrade == "reinstall" ]; then python scripts/action_after_reinstall.py; fi
  if [ upgrade == "upgrade" ]; then python scripts/action_after_upgrade.py; fi
```

### Anything else?
```
task_2:
    before upgrade: create collection, insert data and create index
    after upgrade: get collection, load, search, insert data, create index, load, and search
log:
https://github.com/zhuwenxing/milvus/suites/4688576765/artifacts/127878314
```

**Comment by yanliang567** [comment] 2021-12-20 02:49
@czs007 could you please help to double check whether it was caused by the expected incompatibility changes on latest master?

/assign @czs007 
/unassign

**Comment by yanliang567** [comment] 2022-01-04 03:46
@zhuwenxing shall wen close this issue as preGa was release?
/unassign @czs007 
/assign @zhuwenxing

**Closed** 2022-01-25 12:23 UTC
Labels: kind/bug, triage/accepted
