### ISSUE TITLE
[Bug]: Querynode panic when running test_e2e with kafka mq

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25053] opened 2023-06-21 03:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230620-4d370ff3
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load failed because querynode all panic
```
[2023-06-21T01:57:34.065Z] [2023-06-21 01:55:27 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-06-21T01:57:34.065Z] [2023-06-21 01:57:27 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__Vy9gOPGw)>, <Time:{'RPC start': '2023-06-21 01:55:27.593900', 'RPC error': '2023-06-21 01:57:27.728010'}> (decorators.py:108)

[2023-06-21T01:57:34.065Z] [2023-06-21 01:57:27 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-06-21T01:57:34.065Z] [2023-06-21 01:57:27 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__Vy9gOPGw)>, <Time:{'RPC start': '2023-06-21 01:55:27.583011', 'RPC error': '2023-06-21 01:57:27.728765'}> (decorators.py:108)

[2023-06-21T01:57:34.065Z] [2023-06-21 01:57:27 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-21T01:57:34.065Z]     return func(self, *args, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 791, in load_collection

[2023-06-21T01:57:34.065Z]     self.wait_for_loading_collection(collection_name, timeout, isRefresh=_refresh)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-21T01:57:34.065Z]     raise e

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-21T01:57:34.065Z]     return func(*args, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-21T01:57:34.065Z]     ret = func(self, *args, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-21T01:57:34.065Z]     raise e

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-21T01:57:34.065Z]     return func(self, *args, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 813, in wait_for_loading_collection

[2023-06-21T01:57:34.065Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-06-21T01:57:34.065Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__Vy9gOPGw)>

[2023-06-21T01:57:34.065Z] 

[2023-06-21T01:57:34.065Z] The above exception was the direct cause of the following exception:

[2023-06-21T01:57:34.065Z] 

[2023-06-21T01:57:34.065Z] Traceback (most recent call last):

[2023-06-21T01:57:34.065Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-21T01:57:34.065Z]     res = func(*args, **_kwargs)

[2023-06-21T01:57:34.065Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-21T01:57:34.065Z]     return func(*arg, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 376, in load

[2023-06-21T01:57:34.065Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-21T01:57:34.065Z]     raise e

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-21T01:57:34.065Z]     return func(*args, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-21T01:57:34.065Z]     ret = func(self, *args, **kwargs)

[2023-06-21T01:57:34.065Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-06-21T01:57:34.065Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-06-21T01:57:34.065Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__Vy9gOPGw)>

[2023-06-21T01:57:34.065Z]  (api_request.py:39)
```

![image](https://github.com/milvus-io/milvus/assets/12268675/b468cd65-5dfd-400b-a022-596f1c9a91e6)

panic log:
```
[2023/06/21 01:30:55.187 +00:00] [INFO] [querynode/segment_loader.go:732] ["All data has been read, there is no more data"] [collectionID=442318411159569234] [channel=by-dev-rootcoord-dml_0] [msgID="AAAAAAAAAAA="]
[2023/06/21 01:30:55.187 +00:00] [INFO] [querynode/segment_loader.go:758] ["from dml check point load done"] [subName=querynode-delta-loader-12-442318411159569234-7177148418081579067] [timeTake=44.055753ms]
[2023/06/21 01:30:55.187 +00:00] [INFO] [msgstream/mq_msgstream.go:182] ["start to close mq msg stream"] ["producer num"=0] ["consumer num"=1]
[2023/06/21 01:30:55.226 +00:00] [INFO] [kafka/kafka_consumer.go:126] ["close consumer "] [topic=by-dev-rootcoord-dml_0] [groupID=querynode-delta-loader-12-442318411159569234-7177148418081579067]
panic: close of closed channel

goroutine 863 [running]:
github.com/confluentinc/confluent-kafka-go/kafka.(*Consumer).Close(0xc000674840)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/consumer.go:421 +0x2c
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*Consumer).Close.func1()
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:229 +0x45
sync.(*Once).doSlow(0xc003586de8?, 0x1507f08?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*Consumer).Close(0x41b4907?)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:226 +0x45
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close(0xc00111e700)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:198 +0x33c
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).Close(0xc00111e700)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:662 +0x32
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).FromDmlCPLoadDelete.func1()
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:628 +0x138
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).FromDmlCPLoadDelete(0xc0007ecea0, {0x4655150, 0xc000898780?}, 0x6236e405ec80352, 0xc0017a07e0, {0xc00101c298, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:759 +0x1e4e
github.com/milvus-io/milvus/internal/querynode.(*loadSegmentsTask).Execute.func2()
	/go/src/github.com/milvus-io/milvus/internal/querynode/load_segment_task.go:105 +0xe5
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

### Milvus Log

failed job: 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/5205/pipeline

log:
[artifacts-querynode-pod-failure-5205-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/11811854/artifacts-querynode-pod-failure-5205-server-logs.2.tar.gz)
[artifacts-querynode-pod-failure-5205-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11811855/artifacts-querynode-pod-failure-5205-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment] 2023-06-21 03:34
/assign @congqixia 
PTAL

**Comment by congqixia** [comment] 2023-06-21 03:41
@zhuwenxing caused by recent pr
patch shall be #25049 #25051

**Comment by zhuwenxing** [comment] 2023-06-21 04:01
introduced by https://github.com/milvus-io/milvus/pull/24997

**Comment by congqixia** [comment] 2023-07-07 08:20
/assign @zhuwenxing 
could you please verify whether this issue still persists after path merged

**Closed** 2023-07-14 01:46 UTC
Labels: kind/bug, priority/critical-urgent, severity/critical, triage/accepted
