### ISSUE TITLE
[Bug]: failed to connect **:53100

### ISSUE THREAD

**Issue by gaoyuan5251** [milvus-io/milvus#26754] opened 2023-08-31 06:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Upgrade from 2.2.12 to 2.3.0

### Steps To Reproduce

```markdown
1.docker-compose down
2.update docker-compose.yml 
3.repull and update milvus.yml& from offcial website
4.docker-compose up -d
```

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/12482790/milvus.log)

### Anything else?

[milvus.txt](https://github.com/milvus-io/milvus/files/12482823/milvus.txt)
[docker-compose.txt](https://github.com/milvus-io/milvus/files/12482826/docker-compose.txt)

github don't allow upload *.yml, if u want to test can use those and replace suffix

**Comment by xiaofan-luan** [comment] 2023-08-31 06:21
milvus-standalone  | I20230830 08:05:52.014195     8 MinioChunkManager.cpp:125] [SEGCORE][InitSDKAPI][milvus] init aws with log level:error
milvus-standalone  | I20230830 08:05:53.023169     8 MinioChunkManager.cpp:96] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-08-30 08:05:53.023 CurlHttpClient [140361393328704] Curl returned error code 28 - Timeout was reached
milvus-standalone  | I20230830 08:05:53.023279     8 MinioChunkManager.cpp:96] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-08-30 08:05:53.023 EC2MetadataClient [140361393328704] Http request to retrieve credentials failed
milvus-standalone  | I20230830 08:05:54.023780     8 MinioChunkManager.cpp:96] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-08-30 08:05:54.023 CurlHttpClient [140361393328704] Curl returned error code 28 - Timeout was reached
milvus-standalone  | I20230830 08:05:54.023859     8 MinioChunkManager.cpp:96] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-08-30 08:05:54.023 EC2MetadataClient [140361393328704] Http request to retrieve credentials failed
milvus-standalone  | I20230830 08:05:54.023886     8 MinioChunkManager.cpp:96] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-08-30 08:05:54.023 EC2MetadataClient [140361393328704] Can not retrieve resource from http://169.254.169.254/latest/meta-data/placement/availability-zone
milvus-standalone  | I20230830 08:05:54.024120     8 MinioChunkManager.cpp:285] [SEGCORE][MinioChunkManager][milvus] init MinioChunkManager with parameter[endpoint: 'minio:9000', default_bucket_name:'a-bucket', use_secure:'false']
milvus-standalone  | I20230830 08:06:15.333519    75 Collection.cpp:66] [SEGCORE][parseIndexMeta][milvus] index meta info : maxRowCount : {59594} FieldId : {101 IndexParams : { index_type : IVF_FLAT, metric_type : L2, nlist : 512,  }TypeParams : {dim : 512, }}
milvus-standalone  | I20230830 08:06:15.333952    21 Collection.cpp:66] [SEGCORE][parseIndexMeta][milvus] index meta info : maxRowCount : {18485} FieldId : {103 IndexParams : { M : 8, efConstruction : 64, index_type : HNSW, metric_type : L2,  }TypeParams : {dim : 1536, }}

**Comment by xiaofan-luan** [comment] 2023-08-31 06:22
/assign @zhagnlu 
could you help on investigate the reason?

**Comment by zhagnlu** [comment] 2023-08-31 06:54
![image](https://github.com/milvus-io/milvus/assets/11935707/aa8bf654-2eb5-4315-97ea-0a2267b3411d)
from log, these is a coredump, this stack pointer to StartSpan interface 
![image](https://github.com/milvus-io/milvus/assets/11935707/7380f9a3-2b3d-4018-9b0e-59ded7effbfa)

**Comment by zhagnlu** [comment] 2023-08-31 06:55
/assign @MrPresent-Han  
help locate core reason

**Comment by zhagnlu** [comment] 2023-08-31 06:55
https://github.com/milvus-io/milvus/pull/26688

**Comment by zhagnlu** [comment] 2023-08-31 06:59
https://github.com/milvus-io/milvus/issues/26277

**Comment by gaoyuan5251** [comment] 2023-08-31 09:15
bro, could it have something to do with etcd? @zhagnlu

**Comment by zhagnlu** [comment] 2023-08-31 11:04
> bro, could it have something to do with etcd? @zhagnlu

It seems no relation with etcd, bro @MrPresent-Han is focus on finding reason

**Comment by MrPresent-Han** [comment] 2023-08-31 12:22
Hello, @gaoyuan5251, we found sth error about tracer in the log file provided. And inside the milvus.yaml, I found the following mount options:

**Comment by gaoyuan5251** [comment] 2023-08-31 12:42
> > bro, could it have something to do with etcd? @zhagnlu
> 
> It seems no relation with etcd, bro @MrPresent-Han is focus on finding reason

but i found etcd was unhealthy status 

milvus-etcd         quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   etcd                3 hours ago         Up 2 hours (unhealthy)   2379-2380/tcp

**Comment by MrPresent-Han** [comment] 2023-08-31 12:47
> > > bro, could it have something to do with etcd? @zhagnlu
> > 
> > 
> > It seems no relation with etcd, bro @MrPresent-Han is focus on finding reason
> 
> but i found etcd was unhealthy status @zhagnlu
> 
> milvus-etcd quay.io/coreos/etcd:v3.5.5 "etcd -advertise-cli…" etcd 3 hours ago Up 2 hours (unhealthy) 2379-2380/tcp
> 
> docker-compose logs etcd | grep "error" milvus-etcd | {"level":"warn","ts":1693474706.6439664,"caller":"fileutil/fileutil.go:57","msg":"check file permission","error":"directory "/etcd" exist, but the permission is "drwxr-xr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data"}
I think this info simply imply that the directory for etcd has so high privilege, the etcd directory on my laptop is also "drwxr-xr-x", but it runs as expected

**Comment by gaoyuan5251** [comment] 2023-08-31 12:57
bro, have you reproduced the problem? @MrPresent-Han

**Comment by MrPresent-Han** [comment] 2023-08-31 13:01
@gaoyuan5251 , I tested on my laptop and changed the trace.exporter to "", and then the problem you issued appeared right away and the container crushed. I suspect it is still sth to do with the milvus config file. 

Anyway, you helped us find a very delicate point of milvus, it's very helpful.

**Comment by MrPresent-Han** [comment] 2023-09-02 13:52
> @MrPresent-Han now , i removed milvus.yaml cofig, milvus still can't up
> 
> * /home/gaoyuan/module/milvus/milvus.yaml:/milvus/configs/milvus.yaml
> 
> docker-compose logs standalone | grep "error" milvus-standalone | [2023/08/31 12:59:00.356 +00:00] [WARN] [grpcclient/client.go:147] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] milvus-standalone | [2023/08/31 12:59:00.356 +00:00] [WARN] [client/client.go:133] ["ClientBase ReCall grpc first call get error "] [role=rootcoord] [address=] [error="err: find no available rootcoord, check rootcoord state\n, /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:378 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:133 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.wrapGrpcCall[...]\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:147 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/componentutil/componentutil.go:34 github.com/milvus-io/milvus/internal/util/componentutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:40 github.com/milvus-io/milvus/pkg/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/componentutil/componentutil.go:58 github.com/milvus-io/milvus/internal/util/componentutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/componentutil/componentutil.go:73 github.com/milvus-io/milvus/internal/util/componentutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:531 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:355 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n"]

hi, @gaoyuan5251 , this error indicates that the rootcoord cannot be launched correctly, maybe you can provide the detailed milvus.log

**Comment by MrPresent-Han** [comment] 2023-09-02 13:53
And also, the pr regarding this flaw has been merged, and I have testified your case on my macOS. It should work out now.

**Comment by gaoyuan5251** [comment] 2023-09-04 01:57
> And also, the pr regarding this flaw has been merged, and I have testified your case on my macOS. It should work out now.

When will this fix be released?

**Comment by MrPresent-Han** [comment] 2023-09-05 06:06
> > And also, the pr regarding this flaw has been merged, and I have testified your case on my macOS. It should work out now.
> 
> When will this fix be released? bro @MrPresent-Han

If you use source project of milvus to launch, just update local code and the fix will be included. Otherwise, the fix will be 
released along with 2.3.1

**Comment by MrPresent-Han** [comment] 2023-09-08 01:55
8th in September

**Comment by gaoyuan5251** [comment] 2023-09-11 01:54
> 



> 8th in September

hi,bro Is there any reason why 2.3.1 was not released?
@MrPresent-Han

**Comment by MrPresent-Han** [comment] 2023-09-18 03:11
@gaoyuan5251 , hello, bro, sorry for overlooking this issue for a week,  I'm afraid that version 2.3.1 has been put off for some reasons and if you want to obtain the latest docker images of milvus out of source code. I recommend you to find in the 
docker hub: https://hub.docker.com/r/milvusdb/milvus/tags
commitID: e51cb739
use this commitID to get the image you want
good luck

**Comment by gaoyuan5251** [comment] 2023-09-25 02:27
Was this issue fixed in version 2.3.1? I still can't upgrade directly from 2.2.12 to 2.3.x

@MrPresent-Han @jiaoew1991 

[log.txt](https://github.com/milvus-io/milvus/files/12710549/log.txt)

**Comment by MrPresent-Han** [comment] 2023-09-25 03:21
[33mmilvus-standalone |[0m [2023/09/25 02:16:31.780 +00:00] [ERROR] [querynode/service.go:127] ["QueryNode init error: "] [error="UnexpectedError: Error:DirExist:Operation not permitted"] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:127\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:223\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
[33mmilvus-standalone |[0m [2023/09/25 02:16:31.780 +00:00] [ERROR] [components/query_node.go:55] ["QueryNode starts error"] [error="UnexpectedError: Error:DirExist:Operation not permitted"] [stack="github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:55\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
[33mmilvus-standalone |[0m panic: UnexpectedError: Error:DirExist:Operation not permitted

it seems that the query node data dir has insufficient permission:

pay attention to the option in milvus.yaml
localStorage.path

**Comment by gaoyuan5251** [comment] 2023-09-25 03:30
<img width="796" alt="image" src="https://github.com/milvus-io/milvus/assets/38758293/d641f445-24b2-4a78-9977-0bd34d150092">
⬆️What does this parameter mean?

<img width="845" alt="image" src="https://github.com/milvus-io/milvus/assets/38758293/78b56015-f1bb-4730-ac18-2ef6c2d5b6a3">

@MrPresent-Han

**Comment by gaoyuan5251** [comment] 2023-09-25 03:31
<img width="724" alt="image" src="https://github.com/milvus-io/milvus/assets/38758293/626939d8-b808-4e2b-9311-010f51adbd15">

⬆️What does this parameter mean?

**Comment by MrPresent-Han** [comment] 2023-09-25 03:49
this is the local dir used as local disk cache for milvus. If you use milvus with docker, you may need to mount an available path for the milvus process inside container

**Comment by gaoyuan5251** [comment] 2023-09-25 04:07
@MrPresent-Han  Is it consistent with this?

<img width="785" alt="image" src="https://github.com/milvus-io/milvus/assets/38758293/322a4b14-80ac-4d07-ae7c-27d84aab6bb7">

**Comment by gaoyuan5251** [comment] 2023-09-25 04:37
[log.txt](https://github.com/milvus-io/milvus/files/12711086/log.txt)
[milvus.txt](https://github.com/milvus-io/milvus/files/12711101/milvus.txt)
[docker-compose.txt](https://github.com/milvus-io/milvus/files/12711103/docker-compose.txt)

@MrPresent-Han

**Comment by MrPresent-Han** [comment] 2023-09-25 05:57
@LoveEachDay, is this related to docker directory?

**Comment by gaoyuan5251** [comment] 2023-09-25 06:00
@MrPresent-Han I removed this param and it still won't start

**Comment by LoveEachDay** [comment] 2023-09-25 08:06
> @LoveEachDay, is this related to docker directory?

This can be any directory with an absolute path.

**Comment by MrPresent-Han** [comment] 2023-09-25 08:23
@gaoyuan5251 , can you change the first param to:
/home/data/volumes/milvus:/var/lib/milvus/data

and check the permission of the doctor:"/home/data/volumes/milvus"

**Comment by gaoyuan5251** [comment] 2023-09-25 08:45
[root@xxxxx volumes]# pwd
/home/data/volumes
[root@xxxxx volumes]# ll
drwxr-xr-x 3 root root 20 Sep 25 16:32 etcd
drwxr-xr-x 2 root root  6 Sep 25 16:35 milvus
drwxr-xr-x 4 root root 40 Sep 25 16:32 minio

[log (2).txt](https://github.com/milvus-io/milvus/files/12713081/log.2.txt)
@MrPresent-Han  ❌

**Comment by gaoyuan5251** [comment] 2023-09-25 08:56
bro,did we test this feature before 2.3.1 was released?
@MrPresent-Han

**Comment by MrPresent-Han** [comment] 2023-09-25 09:11
![iF5mzVuioo](https://github.com/milvus-io/milvus/assets/116052805/b922c0b4-5905-442d-a3b2-eec7813d677b)

the permission is root, did you launch docker idle process using root user?
if you use other user start docker, and this may encounter permission problem

**Comment by gaoyuan5251** [comment] 2023-09-25 09:28
> ![iF5mzVuioo](https://user-images.githubusercontent.com/116052805/270290609-b922c0b4-5905-442d-a3b2-eec7813d677b.jpg)
> 
> the permission is root, did you launch docker idle process using root user? if you use other user start docker, and this may encounter permission problem

yeah, I am currently the root user

**Comment by gaoyuan5251** [comment] 2023-09-25 09:28
> ![iF5mzVuioo](https://user-images.githubusercontent.com/116052805/270290609-b922c0b4-5905-442d-a3b2-eec7813d677b.jpg)
> 
> the permission is root, did you launch docker idle process using root user? if you use other user start docker, and this may encounter permission problem

@MrPresent-Han yeah, I am currently the root user

**Comment by MrPresent-Han** [comment] 2023-09-25 09:48
https://github.com/milvus-io/milvus/issues/26717
there is another issue with same problems, it seems that milvus 2.3.x really has this issue in some cases and currently, colleagues in devops haven't reproduce the problem and locate the root cause

**Comment by gaoyuan5251** [comment] 2023-09-26 02:09
> #26717 there is another issue with same problems, it seems that milvus 2.3.x really has this issue in some cases and currently, colleagues in devops haven't reproduce the problem and locate the root cause

bro, Didn't the repair work this time?

**Comment by gaoyuan5251** [comment] 2023-10-12 07:26
> #26717 there is another issue with same problems, it seems that milvus 2.3.x really has this issue in some cases and currently, colleagues in devops haven't reproduce the problem and locate the root cause

@MrPresent-Han bro,haven't colleagues in devops reproduce the problem yet？

**Comment by LoveEachDay** [comment] 2023-10-23 08:50
@gaoyuan5251 Could you try to add a `security_opt` like this:
```
 standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined 
```
https://github.com/milvus-io/milvus/issues/27028 has fixed the `Operation not permitted` error by adding `security_opt`.

**Comment by gaoyuan5251** [comment] 2023-10-23 09:04
> seccomp

@LoveEachDay  What does this parameter mean?

**Comment by LoveEachDay** [comment] 2023-10-23 09:06
`seccomp` (Secure computing mode) is a Linux kernel feature. It can be used to limit which `systemcalls` can be issued from the docker application. 

Read more from: https://docs.docker.com/engine/security/seccomp/

**Comment by gaoyuan5251** [comment] 2023-10-23 09:06
> @gaoyuan5251 Could you try to add a `security_opt` like this:
> 
> ```
>  standalone:
>     container_name: milvus-standalone
>     image: milvusdb/milvus:v2.3.0
>     command: ["milvus", "run", "standalone"]
>     security_opt:
>     - seccomp:unconfined 
> ```
> 
> #27028 has fixed the `Operation not permitted` error by adding `security_opt`.

@LoveEachDay ,ok,I'll try it sometime

**Comment by gaoyuan5251** [comment] 2023-10-23 10:15
The issue is solved. Thank you very much for your support. Thank you very much.
@LoveEachDay @MrPresent-Han @zhagnlu  @xiaofan-luan

**Comment by yanliang567** [comment] 2023-10-24 01:09
close the issue as comments above

**Closed by yanliang567** 2023-10-24 01:09 UTC
Labels: kind/bug, triage/accepted

**Comment by fushun1990** [comment] 2024-02-04 06:13
@yanliang567 

image: milvusdb/milvus:v2.3.3-gpu 还是存在这个问题。

并且是在重启之后，还在链接53100。感觉是在链接客户端。

**Comment by yanliang567** [comment] 2024-02-04 06:52
@fushun1990 please try to file a new issue with full logs attached.
