### ISSUE TITLE
[BUG] Search result id=0 sometimes when nprobe set 512 on version-0.5.2

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#331] opened 2019-11-14 08:33 UTC
**Describe the bug**
Not re-produced with server version 0.5.3
Test on dataset: ann-glove-200

**Steps/Code to reproduce behavior**
Search with params:
top-k: 100
nq: 10000
nrpobe: 512
index_type: IVF_FLAT/IVF_SQ8

**Expected behavior**
No result id equals 0

**Environment details**
server-servion: 0.5.2
dataset: glove-200
pymilvus: 0.2.3

**Screenshots**
null

**Additional context**
null

**Comment by JinHai-CN** [comment] 2019-11-14 08:35
If 0.5.3 can't reproduce this issue, we will regard it as fixed.

**Comment by cydrain** [comment] 2019-11-14 15:16
try many times, cannot reproduce

**Comment by cydrain** [comment] 2019-11-18 02:47
If this issue can be re-produced in 0.6.0, we need check it; otherwise, close it.

**Comment by del-zhenwu** [comment] 2019-11-25 03:52
Re-produced in 0.6.0

**Comment by cydrain** [comment] 2019-11-28 11:47
With following settings, this issue can be re-produced steadly.
      index_types: ['ivf_sq8']
      nlists: [16384]
      search_param:
        nprobes: [512]
        top_ks: [100]
        nqs: [10000]

This issue is because FAISS limitation reached.
We can see ERROR in Milvus logs.
2019-11-28 19:38:18,952 | ERROR | default | [WRAPPER] Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 4096000000 bytes (error 2 out of memory)
2019-11-28 19:38:18,952 | ERROR | default | [ENGINE] Search error

Close this issue.

**Comment by cydrain** [comment] 2019-12-02 01:28
fixed

**Closed by cydrain** 2019-12-02 01:28 UTC
Labels: type/bug
