### ISSUE TITLE
[Bug]: Part of the data is lost when inserting concurrently

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#11438] opened 2021-11-08 09:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0rc8
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc8
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I use 8 processes to insert data into Milvus concurrently, each process inserts 10000 vectors each time, a total of 10000000 are inserted. After inserting, then I use collection.count_entities() to get the number of vectors in the collection, it returns 9932409.

During the insertion process, I found that the pulsar broker restarted 9 time， and there have 5 errors as follows in the insert log:

<img width="1154" alt="截屏2021-11-08 下午6 01 19" src="https://user-images.githubusercontent.com/53458891/140722283-13cdc490-14f0-4049-9df1-bb009a347647.png">

### Expected Behavior

collection.count_entities()  should return 10000000.

### Steps To Reproduce

```markdown
1. Start a Milvus cluster with 4 proxy pods, 4 datanode pods and 2 pulsar broker. The rest is the default configuration.
2. The test script i used: https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/concurrent-test/multi_process_insert.py
3. Change the parameters in the script: SHARD_NUM = 8, PROCESS_NUM = 8.
4. run the script:
   Create collection: `python multi_process_insert.py -n test_1 -c`
   Insert data: `python multi_process_insert.py -n test_1 -i`
```

**Comment by yanliang567** [comment] 2021-11-09 01:09
@sunby please help to check whether pulsar service is the bottleneck in this case? Also how to deliver this message to the users so that they could fix issue by themselves

/assign @sunby 
/unassign

**Comment by Bennu-Li** [comment] 2021-11-11 02:53
I deploy a new Milvus cluster, and test again. This time, all services are running normally. But it still lost part of data.

And then i call collection.load(). After the load ends, the total number of entities in the collection is not equal to the number of load entities.

<img width="720" alt="截屏2021-11-11 上午10 52 39" src="https://user-images.githubusercontent.com/53458891/141228901-57140def-e74c-4bcb-b96c-d18bd0b9f11e.png">

**Comment by sunby** [comment] 2021-11-16 07:10
I need the pulsar log. If you insert rows during pulsar crash, it will timeout and you should retry.

**Comment by sunby** [comment] 2021-11-16 07:10
@yanliang567 it's not a bug.

**Comment by xiaofan-luan** [comment] 2021-11-24 12:23
we will close this issue if this is not accepted

**Comment by yanliang567** [comment] 2021-11-26 04:05
> @yanliang567 it's not a bug.

@sunby could you  please explain more about how it happens?

**Comment by xiaofan-luan** [comment] 2021-11-28 14:11
> > @yanliang567 it's not a bug.
> 
> @sunby could you please explain more about how it happens?

I guess it is just because of the timeout is not handled by python sdk

**Comment by xiaofan-luan** [comment] 2021-11-30 02:04
close for now, need to review pulsar memory configs

**Closed by xiaofan-luan** 2021-11-30 02:04 UTC
Labels: kind/bug, priority/urgent, triage/needs-information
