### ISSUE TITLE
Segment size and segment count is not expected in some case

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4293] opened 2020-11-25 08:38 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create collection, set `segment_row_limit`=1000000
2. insert 100000 entities per request, flush, loop insert for 10 times
3. after flush, we found the number of final segment files > 1
User need to insert another entities, to make sure the row count of segment file = 1000000 exactly, the merge strategy may be need to upgrade.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment] 2020-11-26 01:50
Insert action could not trigger merge all entities into one segment, since the merge strategy need to consider continually insert action. The merge strategy is described in this article: https://zhuanlan.zhihu.com/p/148106312

Invoke create_index can merge all entities into one segment.

**Comment by yhmo** [comment] 2020-11-28 02:12
Not a bug, won't fix.

**Closed** 2020-12-01 06:20 UTC
Labels: wontfix
