### ISSUE TITLE
vector search error

### ISSUE THREAD

**Issue by lidachuan211** [milvus-io/milvus#4086] opened 2020-10-24 11:08 UTC
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
we user three fields as filter condition ，there are about 20 vectors after filtering，if we set topk = 20 in search params，then report error：
io.milvus.client.exception.ClientSideMilvusException: dns:///10.111.20.104:19530: null

but，if we  set topk= 10,  sucess！

**Expected behavior**
 the filterd vectors is less than  tokp，then response filter vecotrs

**Method of installation**
- [ ] cpu only, docker
- [ ] image:milvusdb/milvus:0.11.0-cpu-d101620-4c44c0

- Milvus version (master or released version)
0.11

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment] 2020-10-24 13:25
This is a known bug in Java SDK: when search result is less than topK, the Client will throw an error.

It will be fixed in 0.9.1.

**Comment by sahuang** [comment] 2020-10-29 08:33
@lidachuan211 This has been fixed in 0.9.1 release. Can you check it the issue is resolved?

**Closed** 2020-11-03 07:59 UTC
Labels: Bug | Severity | S2, sdk/java
