### ISSUE TITLE
delete vector by id, then add vector back, flush, search with the old id again, results not expected

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1170] opened 2020-02-12 06:20 UTC
**Describe the bug**
see the two scenarios in comments area

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by youny626** [comment] 2020-02-12 11:21
I couldn't reproduce it :/

**Comment by liangliu** [comment] 2020-02-13 08:14
steps:

1, create table and init data
2, search_by_id (here use **id_100** to name it)
3, delete_by_id([**id_100**]), but **NO flush**
4, add same vectors to table and **NO flush**
5, search_by_id(**id_100**)

expected: in returned result, only result[0] distance == 0
actual: all ids in result == -1 (means not found)

**Comment by liangliu** [comment] 2020-02-13 08:49
another scenario

steps:

1, create table and init data
2, search_by_id (here use id_100 to name it)
3, delete_by_id([id_100]), but NO flush
4, add same vectors to table and sleep 10s (make auto flush take effect)
5, search_by_id(id_100)

expected: in returned result, all ids in result == -1 (means not found since id_100 is deleted)
actual: see the first 2 of the result, one is the old id (id_100), the other is the new generated id ('cause same vector added and flushed), these 2 result's distance is 0.0, the rest is common related search results

NOTICE: if you use manual flush in step 4th above, the result is shown as expected, seems difference between manual flush and auto flush

**Comment by youny626** [comment] 2020-02-13 09:19
Problem seems to be caused by auto flush. It didn't apply deletes correctly. Manual flush does not have these problems.

**Comment by JinHai-CN** [comment] 2020-02-24 16:07
@youny626 Any update?

**Comment by youny626** [comment] 2020-02-25 06:41
> @youny626 Any update?

@JinHai-CN Already fixed

**Comment by JinHai-CN** [comment] 2020-02-25 10:46
@del-zhenwu Please check if is fixed. If so, close it.

**Comment by del-zhenwu** [comment] 2020-02-27 01:53
close

**Closed by del-zhenwu** 2020-02-27 01:53 UTC
Labels: type/bug
