### ISSUE TITLE
[Bug]: Insert data with duplicate primary key

### ISSUE THREAD

**Issue by MichaelZhe** [milvus-io/milvus#33353] opened 2024-05-24 04:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.3
- OS(Ubuntu or CentOS): MacOS 14.4.1
- CPU/Memory: M1 Pro/16G
- GPU: M1 Pro
- Others:
```

### Current Behavior

`

    client = MilvusClient(uri='http://127.0.0.1:19530')
    hasFaceCollection = client.has_collection("face_collection")
    hasOtherCollection = client.has_collection("other_collection")
    print("hasFaceCollection", hasFaceCollection)
    print("hasOtherCollection", hasOtherCollection)

    if not hasFaceCollection:
        schema = MilvusClient.create_schema(
            auto_id=False,
            enable_dynamic_field=True,
        )
        schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True)
        schema.add_field(field_name="user_id", datatype=DataType.INT32)
        schema.add_field(field_name="face_features", datatype=DataType.FLOAT_VECTOR, dim=256)

        index_params = client.prepare_index_params()
        index_params.add_index(field_name="id")
        index_params.add_index(
            field_name="face_features",
            index_type="AUTOINDEX",
            metric_type="L2", 
        )
        client.create_collection(collection_name="face_collection", schema=schema, index_params=index_params)

    data = [
        {"id": 0, "user_id": 0, "face_features": test_vectors.test_vector_0},
        {"id": 1, "user_id": 1, "face_features": test_vectors.test_vector_1},
    ]

    res = client.insert(collection_name="face_collection", data=data)

    print("插入新数据:", res)
`

I referenced the official code to implement a segment of code for inserting data. After executing it for the first time, I used a conditional query to search with `client.query(collection_name="face_collection", ids=[0, 1], output_fields=["id", "user_id"])`, and I was able to retrieve the two entries I had just inserted. When I executed the data insertion code again (inserting duplicate data with primary keys 0 and 1), and then performed `client.query(collection_name="face_collection", ids=[0, 1], output_fields=["id", "user_id"])` again, I could only retrieve the entity with id 0. However, when I set the ids parameter to [1], I could retrieve the entity with id 1. Is this a BUG, or is there something wrong with how I am using it?

**Comment by xiaofan-luan** [comment] 2024-05-24 06:32
Milvus doesn't guarantee primary key dedup.
If both key is retrieved, new will overwrite old. but we don't guarantee this over write happens. 
so user has to ensure there is no over write happens

**Comment by MichaelZhe** [comment] 2024-05-24 06:56
Whether or not it overwrites the old data, I think it's still within a logically controllable range. However, if a mistake is made by inserting the same primary key, as in my previous issue, when I query again using ids=[0,1], it only returns the data for id==0. Yet, the data for id==1 actually exists in the database (as it can be retrieved using ids=[1]). This seems to make the database's behavior strange and uncontrollable.

**Comment by MichaelZhe** [comment] 2024-05-24 06:56
> Milvus doesn't guarantee primary key dedup. If both key is retrieved, new will overwrite old. but we don't guarantee this over write happens. so user has to ensure there is no over write happens

Whether or not it overwrites the old data, I think it's still within a logically controllable range. However, if a mistake is made by inserting the same primary key, as in my previous issue, when I query again using ids=[0,1], it only returns the data for id==0. Yet, the data for id==1 actually exists in the database (as it can be retrieved using ids=[1]). This seems to make the database's behavior strange and uncontrollable.

**Comment by xiaofan-luan** [comment] 2024-05-24 07:12
> > Milvus doesn't guarantee primary key dedup. If both key is retrieved, new will overwrite old. but we don't guarantee this over write happens. so user has to ensure there is no over write happens
> 
> Whether or not it overwrites the old data, I think it's still within a logically controllable range. However, if a mistake is made by inserting the same primary key, as in my previous issue, when I query again using ids=[0,1], it only returns the data for id==0. Yet, the data for id==1 actually exists in the database (as it can be retrieved using ids=[1]). This seems to make the database's behavior strange and uncontrollable.

because the data can be in different segment and milvus don't have the information there is a duplicate pk. this is by design and so far we can not do anything.

if you know the pk exist, you can use upsert to delete old one and insert a new one

**Comment by MichaelZhe** [comment] 2024-05-24 07:30
> > > Milvus doesn't guarantee primary key dedup. If both key is retrieved, new will overwrite old. but we don't guarantee this over write happens. so user has to ensure there is no over write happens
> > 
> > 
> > Whether or not it overwrites the old data, I think it's still within a logically controllable range. However, if a mistake is made by inserting the same primary key, as in my previous issue, when I query again using ids=[0,1], it only returns the data for id==0. Yet, the data for id==1 actually exists in the database (as it can be retrieved using ids=[1]). This seems to make the database's behavior strange and uncontrollable.
> 
> because the data can be in different segment and milvus don't have the information there is a duplicate pk. this is by design and so far we can not do anything.
> 
> if you know the pk exist, you can use upsert to delete old one and insert a new one

OK ，Thanks

**Comment by yanliang567** [comment] 2024-05-24 10:03
I'd close this issue, and please free to file a new one if you met any new issues

**Closed by yanliang567** 2024-05-24 10:03 UTC
Labels: kind/bug, help wanted
