### ISSUE TITLE
[Bug]: nlist parameter does not take effect when create collection by restful api

### ISSUE THREAD

**Issue by cnlkl** [milvus-io/milvus#36365] opened 2024-09-19 09:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.5
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): RESTful API
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When creating a Collection through the HTTP REST API and creating IVF_FLAT index at the same time, the `nlist` parameter does not take effect.

### Expected Behavior

Success create collection and index with specify nlist

### Steps To Reproduce

```markdown
It can be reproduced by  using the example in the official documentation.


export MILVUS_URI="localhost:19530"

curl --location --request POST "http://${MILVUS_URI}/v2/vectordb/collections/create" \
--header "Content-Type: application/json" \
--data-raw '{
    "collectionName": "custom_setup_indexed",
    "schema": {
        "autoId": false,
        "enabledDynamicField": false,
        "fields": [
            {
                "fieldName": "my_id",
                "dataType": "Int64",
                "isPrimary": true
            },
            {
                "fieldName": "my_vector",
                "dataType": "FloatVector",
                "elementTypeParams": {
                    "dim": "5"
                }
            }
        ]
        
    },
    "indexParams": [
        {
            "fieldName": "my_vector",
            "metricType": "COSINE",
            "indexName": "my_vector",
            "params": {
                "index_type": "IVF_FLAT",
                "nlist": "1024"
            }
        },
        {
            "fieldName": "my_id",
            "indexName": "my_id",
            "params": {
                "index_type": "STL_SORT"
            }            
        }
    ]
}'

```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by yanliang567** [comment] 2024-09-20 02:19
sounds like a known issue for now.
/assign @smellthemoon 
/unassign

**Comment by xiaofan-luan** [comment] 2024-09-21 14:39
@yanliang567 
There is no test about the restful API? this seems to be a stupid problem

**Comment by zhuwenxing** [comment] 2024-10-11 05:34
@cnlkl 
Hi, I want to know how you determine that nlist is not taking effect? I tried passing indexParams and the corresponding nlist when creating a collection, and then checked the index's params through the PyMilvus interface, and the parameter values are exactly what I passed in.

```
    c = Collection(name)
    index_info = [index.to_dict() for index in c.indexes]
```

```
[2024-10-11 13:31:20 - INFO - ci_test]: create collection custom_setup_indexed with payload: {'collectionName': 'custom_setup_indexed', 'schema': {'autoId': False, 'enabledDynamicField': False, 'fields': [{'fieldName': 'my_id', 'dataType': 'Int64', 'isPrimary': True}, {'fieldName': 'my_vector', 'dataType': 'FloatVector', 'elementTypeParams': {'dim': '5'}}]}, 'indexParams': [{'fieldName': 'my_vector', 'metricType': 'COSINE', 'indexName': 'my_vector', 'params': {'index_type': 'IVF_FLAT', 'nlist': '1024'}}, {'fieldName': 'my_id', 'indexName': 'my_id', 'params': {'index_type': 'STL_SORT'}}]} (test_index_operation.py:72)
[2024-10-11 13:31:21 - DEBUG - urllib3.connectionpool]: Starting new HTTP connection (1): 10.104.33.221:19530 (connectionpool.py:246)
[2024-10-11 13:31:21 - DEBUG - urllib3.connectionpool]: http://10.104.33.221:19530 "POST /v2/vectordb/collections/create HTTP/1.1" 200 20 (connectionpool.py:475)
[2024-10-11 13:31:21 - DEBUG - ci_test]: 
method: post, 
url: http://10.104.33.221:19530/v2/vectordb/collections/create, 
cost time: 0.061990976333618164, 
header: {'Content-Type': 'application/json', 'Authorization': 'Bearer None', 'RequestId': '0bb4e996-8792-11ef-b592-acde48001122'}, 
payload: {
    "collectionName": "custom_setup_indexed",
    "schema": {
        "autoId": false,
        "enabledDynamicField": false,
        "fields": [
            {
                "fieldName": "my_id",
                "dataType": "Int64",
                "isPrimary": true
            },
            {
                "fieldName": "my_vector",
                "dataType": "FloatVector",
                "elementTypeParams": {
                    "dim": "5"
                }
            }
        ]
    },
    "indexParams": [
        {
            "fieldName": "my_vector",
            "metricType": "COSINE",
            "indexName": "my_vector",
            "params": {
                "index_type": "IVF_FLAT",
                "nlist": "1024"
            }
        },
        {
            "fieldName": "my_id",
            "indexName": "my_id",
            "params": {
                "index_type": "STL_SORT"
            }
        }
    ],
    "params": {
        "consistencyLevel": "Strong"
    }
}, 
response: {"code":0,"data":{}} (milvus.py:77)
[2024-10-11 13:31:21 - INFO - ci_test]: rsp: {'code': 0, 'data': {}} (test_index_operation.py:74)
[2024-10-11 13:31:21 - DEBUG - urllib3.connectionpool]: Starting new HTTP connection (1): 10.104.33.221:19530 (connectionpool.py:246)
[2024-10-11 13:31:21 - DEBUG - urllib3.connectionpool]: http://10.104.33.221:19530 "POST /v2/vectordb/collections/describe HTTP/1.1" 200 705 (connectionpool.py:475)
[2024-10-11 13:31:21 - DEBUG - ci_test]: 
method: post, 
url: http://10.104.33.221:19530/v2/vectordb/collections/describe, 
cost time: 0.031009912490844727, 
header: {'Content-Type': 'application/json', 'Authorization': 'Bearer None', 'RequestId': '0bb4e996-8792-11ef-b592-acde48001122'}, 
payload: {
    "collectionName": "custom_setup_indexed"
}, 
response: {"code":0,"data":{"aliases":[],"autoId":false,"collectionID":453147083140405071,"collectionName":"custom_setup_indexed","consistencyLevel":"Strong","description":"","enableDynamicField":false,"fields"...ctor","indexName":"my_vector","metricType":"COSINE"},{"fieldName":"my_id","indexName":"my_id","metricType":""}],"load":"LoadStateLoading","partitionsNum":1,"properties":[],"shardsNum":1},"message":""} (milvus.py:77)
[2024-10-11 13:31:21 - INFO - ci_test]: rsp: {'code': 0, 'data': {'aliases': [], 'autoId': False, 'collectionID': 453147083140405071, 'collectionName': 'custom_setup_indexed', 'consistencyLevel': 'Strong', 'description': '', 'enableDynamicField': False, 'fields': [{'autoId': False, 'description': '', 'id': 100, 'name': 'my_id', 'partitionKey': False, 'primaryKey': True, 'type': 'Int64'}, {'autoId': False, 'description': '', 'id': 101, 'name': 'my_vector', 'params': [{'key': 'dim', 'value': '5'}], 'partitionKey': False, 'primaryKey': False, 'type': 'FloatVector'}], 'indexes': [{'fieldName': 'my_vector', 'indexName': 'my_vector', 'metricType': 'COSINE'}, {'fieldName': 'my_id', 'indexName': 'my_id', 'metricType': ''}], 'load': 'LoadStateLoading', 'partitionsNum': 1, 'properties': [], 'shardsNum': 1}, 'message': ''} (test_index_operation.py:76)
[2024-10-11 13:31:21 - INFO - ci_test]: index_info: [{'collection': 'custom_setup_indexed', 'field': 'my_id', 'index_name': 'my_id', 'index_param': {'metric_type': '', 'index_type': 'STL_SORT'}}, {'collection': 'custom_setup_indexed', 'field': 'my_vector', 'index_name': 'my_vector', 'index_param': {'metric_type': 'COSINE', 'index_type': 'IVF_FLAT', 'nlist': '1024'}}] (test_index_operation.py:80)
```

**Comment by cnlkl** [comment] 2024-10-12 04:15
@zhuwenxing I create collection through restful api, and then check collection info by attu, the `nlist` param was not shown in the collection info page, but if I create index through attu gui, it shows correctly

**Comment by zhuwenxing** [comment] 2024-10-12 07:08
@cnlkl 
thanks for your information. Using this method can indeed reproduce the results.


@smellthemoon 

By comparing the index info created by Restful and Pymilvus, it can be seen that the position of the nlist parameter has not been passed correctly.

index info when index is creatde by **pymilvus** and can be shown in attu

{'collection': 'test_collection_2024_10_11_12_00_02_737118pMhzhiss', 'field': 'book_intro', 'index_name': 'demo', 'index_param': {'index_type': 'IVF_FLAT', 'metric_type': 'L2', **'params': {'nlist': 19530}**}}


index info when index is created by **restful** and can not be shown in attu

{'collection': 'test_collection_2024_10_11_12_00_02_737118pMhzhiss', 'field': 'book_intro', 'index_name': 'demo', 'index_param': {'metric_type': 'L2', 'index_type': 'IVF_FLAT', **'nlist': '19530'**}}

**Comment by smellthemoon** [comment] 2024-10-12 09:47
I adjusted the parameter format of indexParams in #36790 
In the new version, we will accept the request format like
`"indexParams": [
        {
            "fieldName": "my_vector",
            "metricType": "COSINE",
            "indexName": "my_vector",
            "indexType": "IVF_FLAT",
            "params": {
                "nlist": "1024"
            }
        },
        {
            "fieldName": "my_id",
            "indexName": "my_id",
            "params": {
                "index_type": "STL_SORT"
            }            
        }
    ]`
which is consistent with the behavior of pymilvus. And the 'nlist' parameter will also work well. Thanks for your contribution! @cnlkl  this change will be available in the next version(v2.4.14).

**Comment by yanliang567** [comment] 2024-10-15 06:41
/assign @zhuwenxing 
please help to verify the fix

**Comment by zhuwenxing** [comment] 2024-10-21 02:58
verified and fixed in `master-2e76709-20241019`
2.4 branch needs https://github.com/milvus-io/milvus/pull/36885 to be merged, then i can verify

**Comment by smellthemoon** [comment] 2024-10-22 06:57
> verified and fixed in `master-2e76709-20241019`
> 2.4 branch needs #36885 to be merged, then i can verify

2.4 branch pr has merged now.

**Comment by zhuwenxing** [comment] 2024-10-25 07:18
https://github.com/milvus-io/milvus/pull/36790
@smellthemoon 
This PR only fixes the issue where the index parameter in create collection is not taking effect, but the problem still exists if you use the index/create interface directly.

**Comment by smellthemoon** [comment] 2024-11-12 06:38
/assign @zhuwenxing 
create index has also adjust it with #37235 , could you help to verify it?

**Closed** 2024-11-16 01:54 UTC
Labels: kind/bug, triage/accepted
