### ISSUE TITLE
[Bug]: [Nightly]Milvus kafka failed to install for many pods kept restarting reporting `Invalid sasl.kerberos.kinit.cmd value`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#30917] opened 2024-02-29 03:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: df16bf6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus kafka failed to install for many pods kept restarting reporting `Invalid sasl.kerberos.kinit.cmd value`.
Both 2.3 and master branch report the error.

2.3: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.3/114/pipeline/
master: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/663/pipeline

The failure may be caused by one of these pr:
![image](https://github.com/milvus-io/milvus/assets/109071306/6b98fd53-5af5-4634-ad5e-9ac7b39f0039)

### Expected Behavior

install successfully

### Milvus Log

err msg:
```
2024-02-29T02:05:55.568621532+08:00 stdout F [2024/02/28 18:05:55.568 +00:00] [DEBUG] [config/refresher.go:71] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[mdk-663-n-etcd:2379]"]
2024-02-29T02:05:56.964485811+08:00 stderr F panic: Failed to create producer by-dev-rootcoord-dml_0, error = Invalid sasl.kerberos.kinit.cmd value: Property not available: "sasl.kerberos.keytab"
2024-02-29T02:05:56.964508601+08:00 stderr F
2024-02-29T02:05:56.964514925+08:00 stderr F goroutine 258 [running]:
2024-02-29T02:05:56.964521567+08:00 stderr F panic({0x4b11d00, 0xc001214020})
2024-02-29T02:05:56.964526237+08:00 stderr F    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001cf5390 sp=0xc001cf52d0 pc=0x1b47ddb
2024-02-29T02:05:56.964530231+08:00 stderr F github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).AsProducer(0xc00125e380, {0xc0012146d0?, 0x1, 0x1b0f7cc?})
2024-02-29T02:05:56.964540219+08:00 stderr F    /go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mq_msgstream.go:147 +0x219 fp=0xc001cf5468 sp=0xc001cf5390 pc=0x3942379
2024-02-29T02:05:56.964553144+08:00 stderr F github.com/milvus-io/milvus/internal/rootcoord.newDmlChannels({0x58d4a50?, 0xc0019e8000}, {0x7fd1f0834420, 0xc0019e0d80}, {0xc0001243c0, 0x14}, 0x10)
2024-02-29T02:05:56.964568888+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:201 +0x472 fp=0xc001cf5788 sp=0xc001cf5468 pc=0x475a6d2
2024-02-29T02:05:56.964573003+08:00 stderr F github.com/milvus-io/milvus/internal/rootcoord.newTimeTickSync({0x58d4a50?, 0xc0019e8000}, 0x9, {0x7fd1f0834420, 0xc0019e0d80}, 0xc001588400?)
2024-02-29T02:05:56.964581237+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:121 +0xd5 fp=0xc001cf5958 sp=0xc001cf5788 pc=0x47bec75
2024-02-29T02:05:56.964585607+08:00 stderr F github.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal(0xc001982300)
2024-02-29T02:05:56.964590064+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476 +0x1ae fp=0xc001cf5b58 sp=0xc001cf5958 pc=0x47915ae
2024-02-29T02:05:56.964594728+08:00 stderr F github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2()
2024-02-29T02:05:56.96459817+08:00 stderr F     /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:551 +0x26 fp=0xc001cf5b78 sp=0xc001cf5b58 pc=0x4792526

```
log: [artifacts-milvus-distributed-kafka-nightly-114-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.3/114/artifact/artifacts-milvus-distributed-kafka-nightly-114-pymilvus-e2e-logs.tar.gz)

**Comment by yanliang567** [comment] 2024-02-29 06:28
/assign @yhmo 
is it caused by #30466 ? please help to check
/unassign

**Comment by yhmo** [comment] 2024-03-07 06:47
The #30924 and #30925 already merged. The error should be ok now.

**Comment by yanliang567** [comment] 2024-03-13 01:07
the nightly is running against kafka pipelines now. close

**Closed by yanliang567** 2024-03-13 01:07 UTC
Labels: kind/bug, triage/accepted
