### ISSUE TITLE
[Bug]: collection fail to load

### ISSUE THREAD

**Issue by UsernameJasonJinIsNotAvailable** [milvus-io/milvus#34673] opened 2024-07-15 05:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: L40S
- Others:
```

### Current Behavior

I tried to migrate my milvus data by **copying the whole "volumes" folder** to a new directory (new standalone from docker-compose). I changed the volumes path in docker-compose so that the container volumes are mapped to the copied "volumes" folder.
The service started fine and my collections are detected. However, I cannot load collections, and the error message is shown as follows:
`MilvusException: (code=2001, message=show collection failed: At LoadSegment: => failed to Deserialize index: raft inner error)`

p.s. release_collection and list_collections work just fine.

### Expected Behavior

I would expect the collections to be loaded when I call load_collection function

### Steps To Reproduce

```markdown
1. copy an existing volumes folder in the host machine to a new place
2. download docker-compose.yml from official website
3. configure the $DOCKER_VOLUME_DIRECTORY to the parent directory of copied volumes folder
4. docker compose up -d
5. build connection with pymilvus (MilvusClient)
6. load a collection
```

**Comment by yanliang567** [comment] 2024-07-16 01:53
let me try to reproduce it in house...

**Comment by xiaofan-luan** [comment] 2024-07-16 07:23
seems that the data deserdes failed.
are you using raft index?
did you which file failed? if original raw data exist, maybe you can try to drop index

**Comment by UsernameJasonJinIsNotAvailable** [comment] 2024-07-17 01:08
What is raft index? I dropped the index and recreated them, and the data can now be accessed. Thanks.

**Comment by yanliang567** [comment] 2024-07-17 02:44
great to hear that. @UsernameJasonJinIsNotAvailable 
When I try to reproduce this issue, if I search immediately after docker compose up, I got an error saying "channel not available[channel=by-dev-rootcoord-dml_4_451196870901785916v0", the failure is expected because I think Milvus is still trying to load the data into memory, but the msg is a bit confusing. After a few seconds, I can do search and query successfully. So we'd try to improve the msg.
anyway, I'd close this issue if you don't mind.

**Closed by yanliang567** 2024-07-17 02:44 UTC
Labels: kind/bug, needs-triage
