### ISSUE TITLE
[Bug]: [Nightly]Kafka failed to build with rootcoord panic 'invalid memory address'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25677] opened 2023-07-17 12:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 74ad7c4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev81
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Kafka failed to build with rootcoord panic 'invalid memory address'.
![img_v2_51935488-eaca-4653-a6f7-61443039d9ag](https://github.com/milvus-io/milvus/assets/109071306/af497e6b-7597-4456-970c-c86f9f60c78a)

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/435/pipeline/87
2. log: [artifacts-milvus-distributed-kafka-nightly-435-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/435/artifact/artifacts-milvus-distributed-kafka-nightly-435-pymilvus-e2e-logs.tar.gz)

**Comment by xiaofan-luan** [comment] 2023-07-17 14:15
/assign @NicoYuan1986 
the zstd usage is from day one we support kafka.

**Comment by yanliang567** [comment] 2023-07-18 01:23
/assign @jaime0815 
could you please also take a look? I don't think we updated any configurations for kafka pipeline recently.

**Comment by jaime0815** [comment] 2023-07-18 03:10
[ERROR] [kafka/kafka_client.go:113] ["create sync kafka producer failed"] [error="Unsupported value \"zstd\" for configuration property \"compression.codec\": libzstd not available at build time"] 
 it seems caused by https://github.com/milvus-io/milvus/pull/25538,  the pre-built librdkafka doesn't support zstd

**Comment by yanliang567** [comment] 2023-07-22 08:00
@jaime0815 any fix plan for it?

**Comment by jaime0815** [comment] 2023-07-26 08:33
fixed by https://github.com/milvus-io/milvus/pull/25792

**Closed by jaime0815** 2023-07-26 08:33 UTC
Labels: kind/bug, triage/accepted
