### ISSUE TITLE
[Bug]: datacoord abnormal restart, followed by continuous restart by all datanode

### ISSUE THREAD

**Issue by xiaozhuang-a** [milvus-io/milvus#25267] opened 2023-07-01 07:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.10
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When the collection data continues to increase, currently at 3k, and the number of entities is very small, the datacoord does not know why it will restart abnormally. Afterwards, the datanode will continue to restart, and the above problem will recur every period of time

## datacoord

[2023/07/01 07:23:56.510 +00:00] [ERROR] [datacoord/handler.go:369] ["datacoord ServerHandler HasCollection finally failed"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*ServerHandler).HasCollection\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/handler.go:369\ngithub.com/milvus-io/milvus/internal/datacoord.(*ServerHandler).CheckShouldDropChannel\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/handler.go:396\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).isMarkedDrop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:874\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).CleanupAndReassign\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:815\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).processAck\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:638\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).watchChannelStatesLoop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:680"]
[2023/07/01 07:23:56.510 +00:00] [FATAL] [logutil/logutil.go:134] [panic] [recover="\"datacoord ServerHandler HasCollection finally failed\""] [stack="github.com/milvus-io/milvus/internal/util/logutil.LogPanic\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/logutil.go:134\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:838\ngithub.com/milvus-io/milvus/internal/datacoord.(*ServerHandler).HasCollection\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/handler.go:370\ngithub.com/milvus-io/milvus/internal/datacoord.(*ServerHandler).CheckShouldDropChannel\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/handler.go:396\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).isMarkedDrop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:874\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).CleanupAndReassign\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:815\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).processAck\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:638\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).watchChannelStatesLoop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:680"]

## dataNode
```bash
:00] [INFO] [datanode/channel_meta.go:435] ["Successfully load pk stats"] [segmentID=442508822576174980] [time=7.25618ms] [size=12]
[2023/07/01 07:34:38.571 +00:00] [INFO] [datanode/channel_meta.go:217] ["adding segment"] [type=Flushed] [segmentID=442508822576253842] [collectionID=442508822576253786] [partitionID=442508822576253787] [channel=by-dev-rootcoord-dml_4_442508822576253786v1] [startPosition=<nil>] [endPosition=<nil>] [recoverTs=442550673594384447] [importing=false]
[2023/07/01 07:34:38.571 +00:00] [INFO] [datanode/channel_meta.go:374] ["begin to init pk bloom filter"] [segmentID=442508822576253842] [statsBinLogsLen=1]
time="2023-07-01T07:34:38Z" level=error msg="[Failed to create consumer]" consumerID=1607 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=jmpmn subscription=by-dev-dataNode-706-by-dev-rootcoord-dml_4_442531371927515286v1 topic="persistent://public/default/by-dev-rootcoord-dml_4"
time="2023-07-01T07:34:38Z" level=error msg="[Failed to create consumer]" consumerID=1607 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=jmpmn subscription=by-dev-dataNode-706-by-dev-rootcoord-dml_4_442531371927515286v1 topic="persistent://public/default/by-dev-rootcoord-dml_4"
[2023/07/01 07:34:38.571 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
panic: Failed to create consumer by-dev-rootcoord-dml_4, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 6989315 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc0254e1400, {0xc03a0e8490?, 0x1, 0x3?}, {0xc012cb9a00, 0x3f}, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:651 +0x285
github.com/milvus-io/milvus/internal/datanode.newDmInputNode({0x4651790, 0xc004be3e80}, 0xc0177c9020, 0xc0279405a0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:52 +0x2af
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc0261d9420, 0xc06cb3dad0, 0xc01670f320)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:291 +0x1b05
github.com/milvus-io/milvus/internal/datanode.newDataSyncService({0x4651790?, 0xc0004fc140?}, 0xc01caa3000, 0xc01670f4a0, {0x467b7f0, 0xc00711c780}, {0x4647700?, 0xc0682eba20}, {0x7f0794aed3d8, 0xc0004e6810}, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:112 +0x3d3
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc0004fc380, 0xc000fefc20, 0xc06cb3dad0, 0x1?, 0x1?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:113 +0x3ba
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc000fefc20, 0xc0279aeeb0, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:406 +0x365
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1()
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:72 +0x128
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run

```

### Anything else?

This issue is very frustrating for us. It didn't happen when the number of collections was very small. It's strange. Is there a problem with our usage posture? Currently, most of the more than 3k collections are in a loaded state, and there is no active release in the code. Will this have an impact

**Comment by xiaozhuang-a** [comment] 2023-07-03 03:27
@yanliang567 @jiaoew1991  Hello, this issue is still bothering us. Would you like to ask if there are any directions or ideas for solving this? Currently, the consensus for datanodes here is_ Tt_ Lag has been increasing

**Comment by jiaoew1991** [comment] 2023-07-04 01:55
@xiaozhuang-a Can you please send the complete log? Based on the current log fragments, it appears that two datanode nodes have subscribed to the same channel, which is very strange.

**Comment by xiaozhuang-a** [comment] 2023-07-04 07:56
@jiaoew https://github.com/xiaozhuang-a/demo/blob/main/milvus-datanode-585fbf6dc8-csz94.log
Is this error message sufficient? If there is any other information, I am available at any time. thanks

**Comment by xiaozhuang-a** [comment] 2023-07-04 07:59
Currently, reboots occur every 20 minutes or so

**Comment by xiaofan-luan** [comment] 2023-07-04 10:19
from the log the error is: Exclusive consumer is already connected 

by-dev-dataNode-2102-by-dev-rootcoord-dml_13_442508822576695897v0 

To fix this issue temporarily you could use pulsarctl to https://pulsar.apache.org/docs/2.10.x/pulsar-admin/ and unubscrie the channel manually.

**Comment by xiaozhuang-a** [comment] 2023-07-04 13:44
Thank you for your answer。
But every time the datanode restarts, the topic reported is different, which looks like many by-dev-dataNode-2102-by-dev-rootcoord-dml_13_442508822576695897v0, is there a better method

**Comment by xiaozhuang-a** [comment] 2023-07-04 13:44
> 从日志中的错误是： 独占消费者已连接
> 
> by-dev-dataNode-2102-by-dev-rootcoord-dml_13_442508822576695897v0
> 
> 要暂时解决此问题，您可以使用 pulsarctl 访问https://pulsar.apache.org/docs/2.10.x/pulsar-admin/并手动取消频道。

Thank you for your answer。
But every time the datanode restarts, the topic reported is different, which looks like many by-dev-dataNode-2102-by-dev-rootcoord-dml_13_442508822576695897v0, is there a better method

**Comment by xiaofan-luan** [comment] 2023-07-04 14:01
then you have to figure out why pulsar can not do unsubscribe.
our pulsar configuration automatically purge subscriptions. Did you deploy with helm or operator or you own pulsar?

**Comment by xiaozhuang-a** [comment] 2023-07-04 14:19
> 那么你必须弄清楚为什么 pulsar 不能取消订阅。 我们的 pulsar 配置会自动清除订阅。你是用舵手或操作员部署的还是你自己的脉冲星？

使用的是helm部署的，这个项目https://github.com/milvus-io/milvus-helm

**Comment by LoveEachDay** [comment] 2023-07-04 14:24
@xiaozhuang-a Could you provide helm chart version using `helm list`?

**Comment by xiaofan-luan** [comment] 2023-07-04 14:27
/assign @SimFG 
could you investigate on this issue?
Maybe we should simply change pulsar to shared mode rather than exclusive mode

**Comment by xiaozhuang-a** [comment] 2023-07-04 14:27
> @xiaozhuang-a您能提供使用的 helm 图表版本吗`helm list`？
![image](https://github.com/milvus-io/milvus/assets/61875985/4862bafb-bc59-4bf8-abe5-390acd62c679)

chart version: milvus-4.0.25

**Comment by xiaozhuang-a** [comment] 2023-07-04 14:33
> > 那么你必须弄清楚为什么 pulsar 不能取消订阅。 我们的 pulsar 配置会自动清除订阅。你是用舵手或操作员部署的还是你自己的脉冲星？
> 
> Deployed using helm, this project https://github.com/milvus-io/milvus-helm

This is the valus of the milvus charts I used, and the pulsar in the sub charts has not been changed

```bash

  bookkeeper:
    replicaCount: 5
    volumes:
      journal:
        name: journal
        size: 100Gi
      ledgers:
        name: ledgers
        size: 200Gi
    resources:
      requests:
        memory: 16000Mi
        cpu: 8
    configData:
      PULSAR_MEM: >
        -Xms16000m
        -Xmx16000m
        -XX:MaxDirectMemorySize=32000m
      PULSAR_GC: >
        -Dio.netty.leakDetectionLevel=disabled
        -Dio.netty.recycler.linkCapacity=1024
        -XX:+UseG1GC -XX:MaxGCPauseMillis=10
        -XX:+ParallelRefProcEnabled
        -XX:+UnlockExperimentalVMOptions
        -XX:+DoEscapeAnalysis
        -XX:ParallelGCThreads=32
        -XX:ConcGCThreads=32
        -XX:G1NewSizePercent=50
        -XX:+DisableExplicitGC
        -XX:-ResizePLAB
        -XX:+ExitOnOutOfMemoryError
        -XX:+PerfDisableSharedMem
        -XX:+PrintGCDetails
      nettyMaxFrameSizeBytes: "104867840"
    pdb:
      usePolicy: false

  broker:
    component: broker
    podMonitor:
      enabled: false
    replicaCount: 3
    resources:
      requests:
        memory: 4096Mi
        cpu: 1.5
    configData:
      PULSAR_MEM: >
        -Xms16g
        -Xmx16g
        -XX:MaxDirectMemorySize=16g
      PULSAR_GC: >
        -Dio.netty.leakDetectionLevel=disabled
        -Dio.netty.recycler.linkCapacity=1024
        -XX:+ParallelRefProcEnabled
        -XX:+UnlockExperimentalVMOptions
        -XX:+DoEscapeAnalysis
        -XX:ParallelGCThreads=32
        -XX:ConcGCThreads=32
        -XX:G1NewSizePercent=50
        -XX:+DisableExplicitGC
        -XX:-ResizePLAB
        -XX:+ExitOnOutOfMemoryError
      maxMessageSize: "104857600"
      defaultRetentionTimeInMinutes: "10080"
      defaultRetentionSizeInMB: "-1"
      backlogQuotaDefaultLimitGB: "8"
      ttlDurationDefaultInSeconds: "259200"
      subscriptionExpirationTimeMinutes: "30"
      backlogQuotaDefaultRetentionPolicy: producer_exception
    pdb:
      usePolicy: false

  autorecovery:
    resources:
      requests:
        memory: 512Mi
        cpu: 1

  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
    resources:
      requests:
        memory: 8000Mi
        cpu: 4
    service:
      type: ClusterIP
    ports:
      pulsar: 6650
    configData:
      PULSAR_MEM: >
        -Xms8000m -Xmx8000m
      PULSAR_GC: >
        -XX:MaxDirectMemorySize=8000m
      httpNumThreads: "100"
    pdb:
      usePolicy: false

  pulsar_manager:
    service:
      type: ClusterIP


```

**Comment by LoveEachDay** [comment] 2023-07-04 14:45
The `subscriptionExpirationTimeMinutes: "30"` config for pulsar broker will automatically remove a subscription without a consumer.

**Comment by xiaozhuang-a** [comment] 2023-07-04 14:48
> The `subscriptionExpirationTimeMinutes: "30"` config for pulsar broker will automatically remove a subscription without a consumer.

Yes, but there seems to be a problem

**Comment by xiaozhuang-a** [comment] 2023-07-04 14:54
This issue was replicated in the testing environment, and the replication process is as follows:

1. 6000 collections were inserted, with 2000 entities in each collection
2. Traverse the collection for async load
3. It was found that the execution timeout occurs when the load reaches 1000-2000

**Comment by jaime0815** [comment] 2023-07-05 02:37
> https://github.com/xiaozhuang-a/demo/blob/main/milvus-datanode-585fbf6dc8-csz94.log

Hi， @xiaozhuang-a  Please upload complete datanode log,  the log fragment cann't help us to investigate this issue

**Comment by jaime0815** [comment] 2023-07-05 02:48
I guess too many collections lead to datanode recovery timeout, and some consumer connections are not closed due to flowgraph initialization failed

**Comment by SimFG** [comment] 2023-07-05 03:59
@yanliang567 Can you try to reproduce this problem in our test environment?

**Comment by xiaozhuang-a** [comment] 2023-07-05 06:27
> > https://github.com/xiaozhuang-a/demo/blob/main/milvus-datanode-585fbf6dc8-csz94.log
> 
> Hi， @xiaozhuang-a Please upload complete datanode log, the log fragment cann't help us to investigate this issue

This is a complete log, which is a bit large. I compressed it a bit. thanks
https://github.com/xiaozhuang-a/demo/blob/main/datanode-previous-0705.log.zip

**Comment by jaime0815** [comment] 2023-07-05 07:54
```
time="2023-07-05T05:37:40Z" level=error msg="[received too big frame size=1210079233 maxFrameSize=104867840]" local_addr="10.4.109.32:45236" remote_addr="pulsar://milvus-pulsar-proxy:6650"
time="2023-07-05T05:37:40Z" level=error msg="[Discarding corrupted message]" consumerID=878 msgID="ledgerId:1557270 entryId:239 partition:-1 " name=cdukd subscription=by-dev-dataNode-2268-by-dev-rootcoord-dml_10_442508822576345891v1 topic="persistent://public/default/by-dev-rootcoord-dml_10" validationError=ChecksumMismatch
time="2023-07-05T05:37:40Z" level=error msg="[handle message Id:  ledgerId:1557270 entryId:239 partition:-1 ]" consumerID=878 error="checksum mismatch received: 0x1dfd3fcd computed: 0x362c9389" local_addr="10.4.109.32:45236" remote_addr="pulsar://milvus-pulsar-proxy:6650"

time="2023-07-05T05:37:40Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://milvus-pulsar-proxy:6650"
time="2023-07-05T05:37:40Z" level=info msg="[TCP connection established]" local_addr="10.4.109.32:53754" remote_addr="pulsar://milvus-pulsar-proxy:6650"
time="2023-07-05T05:37:40Z" level=info msg="[Connection is ready]" local_addr="10.4.109.32:53754" remote_addr="pulsar://milvus-pulsar-proxy:6650"

time="2023-07-05T05:37:40Z" level=info msg="[Connected consumer]" consumerID=1362 name=qfdnc subscription=by-dev-dataNode-2268-by-dev-rootcoord-dml_0_442508822576532892v1 topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2023-07-05T05:37:40Z" level=info msg="[Reconnected consumer to broker]" consumerID=1362 name=qfdnc subscription=by-dev-dataNode-2268-by-dev-rootcoord-dml_0_442508822576532892v1 topic="persistent://public/default/by-dev-rootcoord-dml_0"


[2023/07/05 05:45:19.595 +00:00] [INFO] [datanode/data_sync_service.go:180] ["begin to init data sync service"] [collection=442508822576425374] [Chan=by-dev-rootcoord-dml_0_442508822576425374v1] [unflushed="[]"] [flushed="[]"]
time="2023-07-05T05:45:19Z" level=error msg="[Failed to create consumer]" consumerID=2766 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=lgrns subscription=by-dev-dataNode-2268-by-dev-rootcoord-dml_0_442508822576532892v1 topic="persistent://public/default/by-dev-rootcoord-dml_0"
```

it seems Pulsar doesn't work well, I see `Discarding corrupted message` from the Pulsar client, the connections are reconnected after checking the checksum failed. The error `Exclusive consumer is already connected` is because the consumers don't unsubscribe before reconnecting.

**Comment by jaime0815** [comment] 2023-07-05 08:20
> from the log the error is: Exclusive consumer is already connected
> 
> by-dev-dataNode-2102-by-dev-rootcoord-dml_13_442508822576695897v0
> 
> To fix this issue temporarily you could use pulsarctl to https://pulsar.apache.org/docs/2.10.x/pulsar-admin/ and unubscrie the channel manually.

@xiaozhuang-a  finding the issued channels from the log and using pulsarctl to unsubscribe them.

**Comment by SimFG** [comment] 2023-07-05 09:39
@xiaozhuang-a can you provide all nodes' log, and I will analyze this issue further

**Comment by xiaozhuang-a** [comment] 2023-07-05 10:02
> @xiaozhuang-a能否提供一下所有节点的日志，我会进一步分析这个问题

This is the log of all the last restarts of the current four datanode nodes. I don’t know if it meets your requirements.
https://github.com/xiaozhuang-a/demo/blob/main/datanode_all_log.zip

**Comment by xiaozhuang-a** [comment] 2023-07-05 10:11
> > 从日志中的错误是： 独占消费者已连接
> > by-dev-dataNode-2102-by-dev-rootcoord-dml_13_442508822576695897v0
> > 要暂时解决此问题，您可以使用 pulsarctl 访问https://pulsar.apache.org/docs/2.10.x/pulsar-admin/并手动取消频道。
> 
> @xiaozhuang-a 从日志中找到已发布的频道并使用 pulsarctl 取消订阅它们。

The datanode is constantly restarting, and each time the subscription needs to be unsubscribed is different, so this treatment should not solve the problem.
In the case of a small amount of collection or a small amount of load, there is no problem. This is very strange. What component problem or bottleneck caused this error?

**Comment by SimFG** [comment] 2023-07-05 11:11
@xiaozhuang-a i want to the all nodes' log, like datacoord, rootcoord

**Comment by xiaozhuang-a** [comment] 2023-07-05 13:06
> @xiaozhuang-a i want to the all nodes' log, like datacoord, rootcoord

https://github.com/xiaozhuang-a/demo/commit/dce61c40e2cb7a6637df2b4e8c8fc16eb1a01d48

**Comment by xiaofan-luan** [comment] 2023-07-05 13:44
> @xiaozhuang-a Thank you for providing the logs. Before we proceed, please consider trying the following steps:
> 
> 1. Stop the Milvus service for 30 minutes to allow all subscriptions to expire.
> 2. Restart Milvus and check if it works normally.
> 
> Currently, our investigation has revealed that the Pulsar service is unstable. To address this issue, Milvus will implement measures to mitigate the impact of such instability in the future.

is there a way to unsubscribe all pulsar channels at once?

**Comment by SimFG** [comment] 2023-07-05 14:00
I will write a bash script to do this tomorrow

**Comment by SimFG** [comment] 2023-07-06 06:31
There is a bash script to unsubscribe all pulsar channels.

- Stop the milvus server
- Enter the terminal of the pulsar server and change to the directory where the `pulsar-admin` binary is located
- Run these two commands

```bash
echo '#!/bin/bash\n\nPULSAR_ADMIN=./pulsar-admin\nNAMESPACE=public/default\n\ntopics=$($PULSAR_ADMIN topics list $NAMESPACE)\n\nfor topic in $topics\ndo\n    topic=${topic//\"/}\n    echo $topic\n    subscriptions=$($PULSAR_ADMIN topics subscriptions $topic)\n\n    for sub in $subscriptions\n    do\n        sub=${sub//\"/}\n        echo $sub\n        $PULSAR_ADMIN topics unsubscribe $topic -f -s $sub\n    done\ndone' > unsubscribe-all.sh
```

```bash
/bin/bash unsubscribe-all.sh
```

**Comment by xiaozhuang-a** [comment] 2023-07-06 10:34
> > @xiaozhuang-a感谢您提供日志。在继续之前，请考虑尝试以下步骤：
> > 
> > 1. 停止 Milvus 服务 30 分钟，让所有订阅过期。
> > 2. 重启 Milvus 并检查是否正常。
> > 
> > 目前，我们的调查显示 Pulsar 服务不稳定。为了解决这个问题，Milvus 将在未来采取措施减弱这种不稳定的影响。
> 
> 我会尝试。感谢你的回复

I tried the above, but it still didn't work.

But after stopping the service for 30 minutes, I changed the number of replicas of querynode and datanode to 1, and the datanode node will no longer restart.

**Comment by SimFG** [comment] 2023-07-06 11:10
@xiaozhuang-a please give me the full data node log

**Comment by SimFG** [comment] 2023-07-06 12:00
okok, thank your feedback. And i will improve it when the pulsar server is unstable.
If there isn't other problem, please help me close the issue

**Closed** 2023-07-06 15:38 UTC
Labels: kind/bug, triage/accepted
