### ISSUE TITLE
[Bug]: [benchmark][cluster]Milvus search failed , datanode crash and client side reported: "InactiveRpcError of RPC that terminated"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22694] opened 2023-03-10 08:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230309-130ab6da
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

case: test_concurrent_locust_100m_hnsw_ddl_dql_filter_kafka_cluster
argo task : fouramf-concurrent-wlp9h

server:
```
fouramf-concurrent-wlp9h-1-etcd-0                                 1/1     Running            0                 15h     10.104.4.53     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-etcd-1                                 1/1     Running            0                 15h     10.104.9.71     4am-node14   <none>           <none>
fouramf-concurrent-wlp9h-1-etcd-2                                 1/1     Running            0                 15h     10.104.5.65     4am-node12   <none>           <none>
fouramf-concurrent-wlp9h-1-kafka-0                                1/1     Running            2 (15h ago)       15h     10.104.4.52     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-kafka-1                                1/1     Running            1 (15h ago)       15h     10.104.9.69     4am-node14   <none>           <none>
fouramf-concurrent-wlp9h-1-kafka-2                                1/1     Running            2 (15h ago)       15h     10.104.5.63     4am-node12   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-datacoord-77477c57dd-fpgn4      1/1     Running            15 (5m48s ago)    15h     10.104.4.40     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-datanode-85c9c4466c-pk8sk       0/1     CrashLoopBackOff   117 (4m54s ago)   15h     10.104.4.42     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-indexcoord-559fc86544-tt6mg     1/1     Running            0                 15h     10.104.4.43     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-indexnode-7954bd777-kkw94       1/1     Running            0                 15h     10.104.4.45     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-proxy-67f9f4f678-d8gwf          1/1     Running            0                 15h     10.104.4.39     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-querycoord-6799b7547-r5fr9      1/1     Running            0                 15h     10.104.4.44     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-querynode-97c86b8bf-gg8k6       1/1     Running            0                 15h     10.104.4.41     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-querynode-97c86b8bf-qqmvh       1/1     Running            0                 15h     10.104.5.55     4am-node12   <none>           <none>
fouramf-concurrent-wlp9h-1-milvus-rootcoord-6f9ddcf9f-2wxhl       1/1     Running            0                 15h     10.104.4.38     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-minio-0                                1/1     Running            0                 15h     10.104.4.51     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-minio-1                                1/1     Running            0                 15h     10.104.9.64     4am-node14   <none>           <none>
fouramf-concurrent-wlp9h-1-minio-2                                1/1     Running            0                 15h     10.104.5.58     4am-node12   <none>           <none>
fouramf-concurrent-wlp9h-1-minio-3                                1/1     Running            0                 15h     10.104.1.119    4am-node10   <none>           <none>
fouramf-concurrent-wlp9h-1-zookeeper-0                            1/1     Running            0                 15h     10.104.4.50     4am-node11   <none>           <none>
fouramf-concurrent-wlp9h-1-zookeeper-1                            1/1     Running            0                 15h     10.104.9.68     4am-node14   <none>           <none>
fouramf-concurrent-wlp9h-1-zookeeper-2                            1/1     Running            0                 15h     10.104.5.64     4am-node12   <none>           <none>
```

client error log:
![image](https://user-images.githubusercontent.com/48523564/224262754-051ebf86-b475-44d2-acea-b764636eff45.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

**Comment by soothing-rain** [comment] 2023-03-10 08:58
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/69466447/224270662-163f0ada-9d6a-4ec8-9ec5-88776634b115.png">

```
2023-03-10 11:43:53 | /go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6993 +0x138
-- | --
  |   | 2023-03-10 11:43:53 | github.com/milvus-io/milvus/internal/proto/datapb._DataNode_GetMetrics_Handler({0x3d3dbe0?, 0xc0005c7680}, {0x424be38, 0xc000db7440}, 0xc0008a3860, 0xc000db6f00)
  |   | 2023-03-10 11:43:53 | /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
  |   | 2023-03-10 11:43:53 | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x424be38, 0xc000db7440}, {0x3c91700, 0xc000891b80}, 0xc000579af0?, 0x3a90c80?)
  |   | 2023-03-10 11:43:53 | /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
  |   | 2023-03-10 11:43:53 | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x424be38?, 0xc000db7440?}, {0x3c91700?, 0xc000891b80?})
  |   | 2023-03-10 11:43:53 | /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
  |   | 2023-03-10 11:43:53 | github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x424be38, 0xc000db7440}, {0x3c91700, 0xc000891b80}, 0xc00088e340?, 0xc00088e360)
  |   | 2023-03-10 11:43:53 | /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
  |   | 2023-03-10 11:43:53 | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x424be38?, 0xc0010ded20?}, {0x3c91700?, 0xc000891b80?})
  |   | 2023-03-10 11:43:53 | /go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
  |   | 2023-03-10 11:43:53 | github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x424be38?, 0xc0010ded20?}, {0x3c91700, 0xc000891b80}, 0x42360c0?, 0xc0007eda88)
  |   | 2023-03-10 11:43:53 | /go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6991 +0x78
  |   | 2023-03-10 11:43:53 | github.com/milvus-io/milvus/internal/proto/datapb._DataNode_GetMetrics_Handler.func1({0x424be38, 0xc0010dedb0}, {0x3c91700?, 0xc000891b80})
  |   | 2023-03-10 11:43:53 | /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:366 +0x2b
  |   | 2023-03-10 11:43:53 | github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).GetMetrics(0xf?, {0x424be38?, 0xc0010dedb0?}, 0xf?)
  |   | 2023-03-10 11:43:53 | /go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:768 +0xa76
  |   | 2023-03-10 11:43:53 | github.com/milvus-io/milvus/internal/datanode.(*DataNode).GetMetrics(0xc0013de000, {0x424be38, 0xc0010dedb0}, 0xc000891b80)
  |   | 2023-03-10 11:43:53 | goroutine 308 [running]:
  |   | 2023-03-10 11:43:53 |  
  |   | 2023-03-10 11:43:53 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2940c76]
  |   | 2023-03-10 11:43:53 | panic: runtime error: invalid memory address or nil pointer dereference
```

/unassign
/assign @yah01

**Comment by xiaofan-luan** [comment] 2023-03-10 09:06
@SimFG seems to be working on the same issue

**Comment by SimFG** [comment] 2023-03-10 09:14
@xiaofan-luan it will be fixed in recent days

**Comment by elstic** [comment] 2023-03-14 02:31
This issue still exists.

server:
```
fouramf-lqngv-73-5064-etcd-0                                      1/1     Running            0                14h     10.104.4.238    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-etcd-1                                      1/1     Running            0                14h     10.104.9.251    4am-node14   <none>           <none>
fouramf-lqngv-73-5064-etcd-2                                      1/1     Running            0                14h     10.104.6.230    4am-node13   <none>           <none>
fouramf-lqngv-73-5064-kafka-0                                     1/1     Running            0                14h     10.104.4.241    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-kafka-1                                     1/1     Running            0                14h     10.104.9.252    4am-node14   <none>           <none>
fouramf-lqngv-73-5064-kafka-2                                     1/1     Running            0                14h     10.104.6.228    4am-node13   <none>           <none>
fouramf-lqngv-73-5064-milvus-datacoord-6ccdb7cd78-7q4zw           1/1     Running            9 (20m ago)      14h     10.104.6.224    4am-node13   <none>           <none>
fouramf-lqngv-73-5064-milvus-datanode-78c85ddf88-95cqp            0/1     CrashLoopBackOff   88 (70s ago)     14h     10.104.4.232    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-milvus-indexcoord-9889ff7fc-bbmt9           1/1     Running            0                14h     10.104.4.229    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-milvus-indexnode-8977cc848-ff62j            1/1     Running            0                14h     10.104.6.225    4am-node13   <none>           <none>
fouramf-lqngv-73-5064-milvus-proxy-6967456cbc-5hc87               1/1     Running            0                14h     10.104.4.228    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-milvus-querycoord-6d7748b87d-g9jtq          1/1     Running            0                14h     10.104.4.231    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-milvus-querynode-687d79c8fb-dhf6x           1/1     Running            0                14h     10.104.4.233    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-milvus-querynode-687d79c8fb-dp9bt           1/1     Running            0                14h     10.104.9.245    4am-node14   <none>           <none>
fouramf-lqngv-73-5064-milvus-rootcoord-689dc56794-tl665           1/1     Running            0                14h     10.104.4.230    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-minio-0                                     1/1     Running            0                14h     10.104.4.239    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-minio-1                                     1/1     Running            0                14h     10.104.9.3      4am-node14   <none>           <none>
fouramf-lqngv-73-5064-minio-2                                     1/1     Running            0                14h     10.104.6.233    4am-node13   <none>           <none>
fouramf-lqngv-73-5064-minio-3                                     1/1     Running            0                14h     10.104.5.11     4am-node12   <none>           <none>
fouramf-lqngv-73-5064-zookeeper-0                                 1/1     Running            0                14h     10.104.4.240    4am-node11   <none>           <none>
fouramf-lqngv-73-5064-zookeeper-1                                 1/1     Running            0                14h     10.104.9.247    4am-node14   <none>           <none>
fouramf-lqngv-73-5064-zookeeper-2                                 1/1     Running            0                14h     10.104.6.231    4am-node13   <none>           <none>
```

client err log:
![image](https://user-images.githubusercontent.com/48523564/224877242-dcc66759-c2e0-41b0-aa73-fcfc61eee7ab.png)

**Comment by SimFG** [comment] 2023-03-14 02:52
@elstic is it the image of master branch? if it is, the fix hasn't cherry pick to master

**Comment by elstic** [comment] 2023-03-14 02:54
> @elstic is it the image of master branch? if it is, the fix hasn't cherry pick to master

@SimFG  image is for the 2.2.0 branch, image is 2.2.0-20230313-99af846b .

**Comment by soothing-rain** [comment] 2023-03-14 02:55
Turns out there's a DataCoord OOM issue:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/69466447/224881213-7632c143-beec-4122-8d2a-fe298a32799a.png">

https://grafana-4am.zilliz.cc/d/uLf5cJ3Gz/milvus-2-2?orgId=1&var-datasource=prometheus&var-app_name=milvus&var-namespace=qa-milvus&var-instance=fouramf-lqngv-73-5064&var-collection=All&var-pod=fouramf-lqngv-73-5064-milvus-datacoord-6ccdb7cd78-7q4zw&var-component=&editPanel=123133

**Comment by elstic** [comment] 2023-03-14 02:57
@soothing-rain  Don't put up intranet links

**Comment by soothing-rain** [comment] 2023-03-14 09:30
Related to TT delay issue:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/69466447/224956864-8e2d0cab-f7ab-4b27-a8d7-7fb4e055f15c.png">

Could be related to: https://github.com/milvus-io/milvus/issues/22605

**Comment by xiaofan-luan** [comment] 2023-03-14 10:48
> @elstic is it the image of master branch? if it is, the fix hasn't cherry pick to master

pls make sure it fixed on both master and 2.2

**Comment by xiaofan-luan** [comment] 2023-03-14 10:49
> 



> @soothing-rain Don't put up intranet links

Is this contantly reproducible?

**Comment by elstic** [comment] 2023-03-14 11:31
> > 
> 
> > @soothing-rain Don't put up intranet links
> 
> Is this contantly reproducible?


Do you want to ask if this case is mandatory or occasional? It is a sure thing.
If you're asking about the datacoord phenomenon, it starts to grow in cpu and mem after about 5 hours, and there is an OOM.


When this case was executed about 4 days ago:
![image](https://user-images.githubusercontent.com/48523564/224980542-61799017-0709-4969-8afb-2d8cf63751b3.png)

When I run this case yesterday : 
![image](https://user-images.githubusercontent.com/48523564/224982182-c22e2f96-8631-49d3-9704-b4fb71919e80.png)

**Comment by elstic** [comment] 2023-03-15 03:05
@SimFG  

There is a strange phenomenon that this problem still exists in the 2.0 branch, but not in the master branch.
Validation date: March 14, 2011
Verify image: 
```
2.2.0 branch: 2.2.0-20230314-65f54000
master branch: master-20230313-c12bcbe1
```

**Comment by SimFG** [comment] 2023-03-15 03:10
@elstic I don't fix the oom problem. And the `nil point` problem about the session has been fixed.
There are two problems, which are `nil point` and `oom`.

**Comment by xiaofan-luan** [comment] 2023-03-15 10:31
OOM is due to TT Lag

**Comment by elstic** [comment] 2023-03-20 02:34
set [dataNode.memory.forceSyncEnable](https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml#L316) to flase , test passed

**Closed** 2023-03-20 02:40 UTC
Labels: kind/bug, priority/critical-urgent, triage/accepted, test/benchmark
