### ISSUE TITLE
[BUG] Search on gpu hung up

### ISSUE THREAD

**Issue by lym777** [milvus-io/milvus#471] opened 2019-11-21 10:25 UTC
**Describe the bug**
index_tpe: ivf_flat
search_resource: gpu0,gpu1,gpu2,gpu3
index_file_size:2048

<_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1574317835.484430425","description":"Error received from peer ipv4:0.0.0.0:19530","file":"src/core/lib/surface/c.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"
>

docker logs:
Faiss assertion 'deviceData_->size() + lengthInBytes <= (size_t) std::numeric_limits<int>::max()' failed in void faiss::gpu::IVFFlat::copyCodeVectorsFromCpu(const float*, const long int*, const std::vector<long unsigned int>&) at gpu/impl/IVFFlat.cu:72
./start_server.sh: line 3:     7 Aborted                 (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf

**Comment by tinkerlin** [comment] 2019-11-22 02:49
The main reason of this bug caused by config index_file_size: 2048.
You can use 1024 instead. I will fix it soon.

**Comment by JinHai-CN** [comment] 2019-11-23 01:28
Why index_file_size 2048 will cause this fault?

**Comment by XuPeng-SH** [comment] 2019-11-25 05:49
In faiss IVFlat gpu impl, when the dim * bytesPerVector * rows >= int32::max, faiss will throw this exception. For example, for dimension 128, the max rows for a file should be 4194303. We need some error protection for this kind of exception.

**Comment by XuPeng-SH** [comment] 2019-11-25 06:54
Only GPU search with internal Faiss affected.

**Comment by JinHai-CN** [comment] 2019-11-25 08:07
It's fixed in 0.6.0. I will close it, if it happen again, please reopen it. @lym777

**Closed by JinHai-CN** 2019-11-25 08:07 UTC
Labels: type/bug
