### ISSUE TITLE
Result ids and distance are zero for all the events after the first result. 

### ISSUE THREAD

**Issue by bigmb** [milvus-io/milvus#7014] opened 2021-08-04 20:15 UTC
Hello,
I get results when I use randomly generated data from:
`vectors = [[random.random() for _ in range(160)] for _ in range(len(t1))]  #t1 = 300K approx
`But when I change my data. I don't get any results apart from the first event.
#### Steps/Code to reproduce:
```
    event_id_field = FieldSchema(name="event_id", dtype=DataType.INT64, description="event_id_field",is_primary=True)
    field = FieldSchema(name=field_name, dtype=DataType.FLOAT_VECTOR, dim=160)
    schema = CollectionSchema(fields=[event_id_field,field],auto_id=False,description="event_munet UM Model collection")
    #schema = CollectionSchema(fields=[field],description="event_munet UM Model collection")
    collection = Collection(name=collection_name, schema=schema)
    print('new collection created')
    list_of_collections = pymilvus_orm.utility.get_connection().list_collections()
    print('list of collections : {}'.format(list_of_collections))
    #path_f_l = [path_features]
    t1_event_id_l = list(t1_event_id_all) ##event_id_list
    entities = [t1_event_id_l,path_features]
    #entities = [path_features]
    mr = collection.insert(entities)
    print(mr)
    print(mr.primary_keys[:10])
    pymilvus_orm.utility.get_connection().flush([collection_name])
    index_param = {
            "metric_type":"L2",
            "index_type":"IVF_FLAT",
            "params":{"nlist":1024}
            }
    collection.create_index(field_name=field_name, index_params=index_param)
    print(collection.index().params)
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
    collection.load()
i=0
xbc = []
for i in range(len(t1)):
    xbc.append(path_features[i])
    #xbc.append(vectors[i])
print('Starting Search')
results = collection.search(xbc[:20],field_name,param=search_params,limit=6,expr=None)
print(results[0].ids)
print(results[0].distances)
print(results[1].ids)
print(results[1].distances)
print(results[8].ids)
print(results[8].distances)
```
#### Expected result:
Ids and distances according to the results of the search.
#### Actual results:
Getting distance results as zero for all events after the first one and also the ids in a random manner.
#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 2.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus2.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:
- GPU:
- Others:
#### Configuration file:
Original file.
#### Additional context:
Used to work in milvus1.

Added 3 files. 
original vectors - 1000 events
event ids - 1000 events
vector generated randoms - 1000 events

Files need Pickle to load.
[events_1000.txt](https://github.com/milvus-io/milvus/files/6934152/events_1000.txt)
[path_features_1000.txt](https://github.com/milvus-io/milvus/files/6934153/path_features_1000.txt)
[vectors_1000.txt](https://github.com/milvus-io/milvus/files/6934154/vectors_1000.txt)

**Comment by jaelgu** [comment] 2021-08-09 02:47
Use IP instead of L2 will get non-zero distances & properly sorted results.

```
Starting Search
[244296, 239510, 246396, 211240, 254366, 229311]
[52.97913360595703, 47.512115478515625, 47.512115478515625, 47.512115478515625, 47.512115478515625, 47.51210021972656]
[244296, 239510, 246396, 211240, 254366, 229311]
[44.40361785888672, 40.299949645996094, 40.299949645996094, 40.299949645996094, 40.299949645996094, 40.299930572509766]
[244296, 211240, 246396, 239510, 254366, 229311]
[47.87858581542969, 43.503204345703125, 43.503204345703125, 43.503204345703125, 43.503204345703125, 43.5031852722168]
```

**Comment by bigmb** [comment] 2021-08-09 03:01
Yes, it does provide me non-zero distance. 
But why are all the ids which are getting searched for, not even on the list? 
results[0].ids should start with 31. ( shouldn't the first result be the id itself?) 
results[1] with 833 and results[8] with 6132.

**Comment by jaelgu** [comment] 2021-08-09 03:55
Duplicate vectors with different ids in original data. Sample code to check:

L2 milvus search results[1]: 
[205259, 97985, 242406, 197964, 166597, 199380]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

```
def get_i_by_val(test_list, v):
    for x, y in enumerate(test_list):
        if y == v:
            return x
        
def check_equal(x, y):
    if path_features[x] == path_features[y]:
        return True
    else:
        return False

x = get_i_by_val(t1_event_id_l, 205259)
print(check_equal(1, x))
```

**Comment by yhmo** [comment] 2021-08-17 06:25
Duplicate vectors with different ids in original data. Caused by dataset, not a bug. Close it.

**Closed by yhmo** 2021-08-17 06:25 UTC
Labels: kind/support
