### ISSUE TITLE
[Bug]: Every nightly pipeline runs much slowly and will be killed for 6h timeout

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#30793] opened 2024-02-23 08:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 16b4c9a
- Deployment mode(standalone or cluster):standalone && cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Every nightly pipeline runs much slowly and will be killed for 6h timeout.

no panic

The root cause may be one of the following pr:
![image](https://github.com/milvus-io/milvus/assets/109071306/435187f8-269a-40dd-83fc-e9301807b8ce)

### Expected Behavior

run fast

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/654/pipeline/
2. log: [artifacts-milvus-distributed-kafka-nightly-654-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/654/artifact/artifacts-milvus-distributed-kafka-nightly-654-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment] 2024-02-23 08:48
Every time flush or load, it till take 3-5s. It seems a little slow.

**Comment by yanliang567** [comment] 2024-02-23 09:10
it cost ~120mins on 2/19, while it cost 300+ mins since 2/20. @congqixia please help  to take a look
/assign @congqixia 
/unassign

**Comment by congqixia** [comment] 2024-03-01 04:37
just check the main difference between these two run, the most likely issue might be the hybrid search tests cases added by #29830
@yanliang567 @NicoYuan1986 @binbinlv

**Comment by yanliang567** [comment] 2024-03-01 05:07
@binbinlv please help to estimate how much time the new tests woud add

**Comment by binbinlv** [comment] 2024-03-04 02:48
I tested it locally, about 1 hour.

**Comment by xiaofan-luan** [comment] 2024-03-09 19:00
can we close this issue?

**Comment by yanliang567** [comment] 2024-03-11 02:55
we are still trying to narrow the root cause of the issue.

**Comment by NicoYuan1986** [comment] 2024-03-11 07:25
It still failed for 6 hours timeout after skipping some cases.  @xiaofan-luan @congqixia

**Comment by congqixia** [comment] 2024-03-12 06:19
After some digging, the case which consumed the most running time was `testcases/test_search.py::TestCollectionSearch.test_search_after_different_index_with_params`
It tested the case locally and find some case stuck in create index step with error:
```
[DEBUG] [indexnode/indexnode_service.go:187] ["querying index build task"] [traceID=c68ccaca55b36e77c396bb0b1fa5ca8a] [clusterID=by-dev] [indexBuildID=448323900004769440] [state=Retry] [reason="failed to create index, C Runtime Exception: invalid data type to build disk index: VECTOR_FLOAT16\n: segcore error[segcoreCode=2001]"]
```
The root cause was that DISKANN is not supported on BF16 & FP16 vector type yet

@cqy123456 is working on the DISKANN supporting BF16 & FP16 issue

Skip DISKANN index type for quick fix

**Comment by laozhu1900** [comment] 2024-03-12 11:51
> FP16

bin/milvus run standalone, it report:  use key DISKANN_fp32 to create knowhere index DISKANN with version 1, SIGSEGV: segmentation violation, Service is not running, it stop. why? = =

**Comment by yanliang567** [comment] 2024-03-13 00:56
> > FP16
> 
> bin/milvus run standalone, it report: use key DISKANN_fp32 to create knowhere index DISKANN with version 1, SIGSEGV: segmentation violation, Service is not running, it stop. why? = =

please file a new issue with reproduce step and milvus logs for investigation

**Comment by laozhu1900** [comment] 2024-03-13 00:56
邮件已收到，谢谢

**Comment by congqixia** [comment] 2024-03-14 04:14
I assume the running time is normal now
/unassign 
/assign @NicoYuan1986

**Closed** 2024-03-18 02:10 UTC
Labels: kind/bug, priority/critical-urgent, severity/critical, triage/accepted, ci/e2e
