### ISSUE TITLE
[BUG] If partition tag is similar, wrong partition is searched

### ISSUE THREAD

**Issue by youny626** [milvus-io/milvus#776] opened 2019-12-16 09:34 UTC
It will still search all partitions.

**Comment by yhmo** [comment] 2019-12-19 07:34
reproduce:
partition 1 tag = 'abc'
partition 2 tag = 'abcd'

search with tag = 'abc', milvus will search in both partitions.

The root cause is in partition tag match function, we use std::regex_search to match tag, this method weill return true if two string is similar. To fix this, instead use std::match method.

**Comment by yhmo** [comment] 2020-03-13 02:09
Fixed in 0.7.0

**Closed by yhmo** 2020-03-13 02:09 UTC
Labels: type/bug
