### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#6895] opened 2021-07-30 02:33 UTC
#### Expected result:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6893/1/pipeline/76/

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6551/33/pipeline
#### Actual results:
```
2021-07-29T12:39:36.135Z] =================================== FAILURES ===================================
[2021-07-29T12:39:36.135Z] __________________ TestQueryBase.test_query_empty_collection ___________________
[2021-07-29T12:39:36.135Z] [gw1] linux -- Python 3.6.8 /usr/local/bin/python3
[2021-07-29T12:39:36.135Z] [gw1] linux -- Python 3.6.8 /usr/local/bin/python3[gw1] linux -- Python 3.6.8 /usr/local/bin/python3
[2021-07-29T12:39:36.135Z] 
[2021-07-29T12:39:36.135Z] self = <test_query.TestQueryBase object at 0x7f9335fa94e0>
[2021-07-29T12:39:36.135Z] 
[2021-07-29T12:39:36.135Z]     @pytest.mark.tags(CaseLabel.L1)
[2021-07-29T12:39:36.135Z]     def test_query_empty_collection(self):
[2021-07-29T12:39:36.135Z]         """
[2021-07-29T12:39:36.135Z]         target: test query empty collection
[2021-07-29T12:39:36.135Z]         method: query on a empty collection
[2021-07-29T12:39:36.135Z]         expected: empty result
[2021-07-29T12:39:36.135Z]         """
[2021-07-29T12:39:36.135Z]         c_name = cf.gen_unique_str(prefix)
[2021-07-29T12:39:36.135Z]         collection_w = self.init_collection_wrap(name=c_name)
[2021-07-29T12:39:36.135Z]         collection_w.load()
[2021-07-29T12:39:36.135Z]         res, _ = collection_w.query(default_term_expr)
[2021-07-29T12:39:36.135Z] >       assert len(res) == 0
[2021-07-29T12:39:36.135Z] E       TypeError: object of type 'NoneType' has no len()
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment] 2021-07-31 03:32
the root cause could be sdk return null instead of an error, #6878

**Comment by yanliang567** [comment] 2021-08-02 06:01
verified this was fixed in orm rc3dev15

**Closed by yanliang567** 2021-08-02 06:01 UTC
Labels: kind/bug, needs-triage, triage/duplicate
