### ISSUE TITLE
[BUG] ivfsq8h search result unusual

### ISSUE THREAD

**Issue by Yukikaze-CZR** [milvus-io/milvus#413] opened 2019-11-19 11:01 UTC
**Describe the bug**
When searching with ivfsq8h, query elapsed time drop at nq=2000, spending around 2s less than nq = 1800. The gpu_search_threshold now is 1200.

**Steps/Code to reproduce behavior**
Using milvus_benchmark to do the query on server.

**Expected behavior**
Query elapsed time keeps increasing with nq.

**Environment details**
- Hardware/Softward conditions : Poseidon
- Method of installation : Docker
- Milvus version (v0.5.3)
- Milvus configuration :
  cpu_cache_capacity: 150
  gpu_cache_capacity: 6
  use_blas_threshold: 1100
  gpu_search_threshold: 1200
  search_resources: cpu, gpu0, gpu1

**Screenshots**
![Screenshot from 2019-11-19 18-59-54](https://user-images.githubusercontent.com/48198922/69141076-e1885280-0afe-11ea-8b12-90ae58328f69.png)

**Comment by fishpenguin** [comment] 2019-11-22 11:02
This bug cannot be reproduced in 0.6.0, and it seems the reason is that CPU TO GPU jitter performance, so I close it.

**Closed by fishpenguin** 2019-11-22 11:02 UTC
Labels: type/bug
