### ISSUE TITLE
Search time instability with the almost the same search params

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1765] opened 2020-03-26 11:36 UTC
**Describe the bug**
Search time instability with the almost the same search params, the response time ranges from 1ms ~ 30+ms

```
020-03-26 19:28:59,401 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.003034 second [3.034380 ms])
2020-03-26 19:28:59,405 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001752 second [1.752341 ms])
2020-03-26 19:28:59,409 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.003358 second [3.357553 ms])
2020-03-26 19:28:59,413 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001709 second [1.709213 ms])
2020-03-26 19:28:59,416 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001768 second [1.768456 ms])
2020-03-26 19:28:59,419 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001756 second [1.756436 ms])
2020-03-26 19:28:59,422 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001666 second [1.666483 ms])
2020-03-26 19:28:59,427 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.003346 second [3.345926 ms])
2020-03-26 19:28:59,430 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001779 second [1.778926 ms])
2020-03-26 19:28:59,493 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.034304 second [34.304363 ms])
2020-03-26 19:28:59,530 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.035043 second [35.043148 ms])
2020-03-26 19:28:59,567 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.035197 second [35.197464 ms])
2020-03-26 19:28:59,577 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.009054 second [9.053689 ms])
2020-03-26 19:28:59,613 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.033600 second [33.599502 ms])
2020-03-26 19:28:59,648 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.033743 second [33.742721 ms])
2020-03-26 19:28:59,687 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.037585 second [37.584980 ms])
2020-03-26 19:28:59,722 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.033238 second [33.237654 ms])
2020-03-26 19:28:59,758 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.033970 second [33.969992 ms])
2020-03-26 19:28:59,782 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.022658 second [22.658450 ms])
2020-03-26 19:28:59,785 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001709 second [1.708769 ms])
2020-03-26 19:28:59,794 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.007131 second [7.131132 ms])
2020-03-26 19:28:59,802 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.005820 second [5.819517 ms])
2020-03-26 19:28:59,809 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.005954 second [5.954146 ms])
2020-03-26 19:28:59,812 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001627 second [1.627494 ms])
2020-03-26 19:28:59,816 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001678 second [1.677769 ms])
2020-03-26 19:28:59,825 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.007401 second [7.400877 ms])
2020-03-26 19:28:59,828 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001705 second [1.704890 ms])
2020-03-26 19:28:59,832 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001684 second [1.683770 ms])
2020-03-26 19:28:59,835 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001686 second [1.686025 ms])
2020-03-26 19:28:59,841 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.003956 second [3.956274 ms])
2020-03-26 19:28:59,844 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001717 second [1.717094 ms])
2020-03-26 19:28:59,847 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001623 second [1.623159 ms])
2020-03-26 19:28:59,850 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001579 second [1.578906 ms])
2020-03-26 19:28:59,853 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001701 second [1.701089 ms])
2020-03-26 19:28:59,856 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001676 second [1.675636 ms])
2020-03-26 19:28:59,859 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001633 second [1.632641 ms])
2020-03-26 19:28:59,862 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001562 second [1.561647 ms])
2020-03-26 19:28:59,865 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001584 second [1.583851 ms])
2020-03-26 19:28:59,868 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001611 second [1.611042 ms])
2020-03-26 19:28:59,871 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001584 second [1.583590 ms])
2020-03-26 19:28:59,874 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001742 second [1.741743 ms])
2020-03-26 19:28:59,877 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001575 second [1.575439 ms])
2020-03-26 19:28:59,880 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001614 second [1.613718 ms])
2020-03-26 19:28:59,884 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001733 second [1.732972 ms])
2020-03-26 19:28:59,887 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001652 second [1.652429 ms])
2020-03-26 19:28:59,890 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001623 second [1.622973 ms])
2020-03-26 19:28:59,925 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.033585 second [33.584887 ms])
2020-03-26 19:28:59,952 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.025709 second [25.708772 ms])
2020-03-26 19:28:59,988 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.034421 second [34.421324 ms])
```

part of log:
```
2020-03-26 19:43:19,445 | DEBUG | default | [KNOWHERE] IVF search cost: 300.717, quantization cost: 0.140869, data search cost: 0.15918
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: query done (0.000348 second [0.347800 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [ENGINE] get uids 950000 from index /var/lib/milvus/db/tables/sift_128_euclidean/1585218595349328000/1585218600262217000
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: map uids 10 (0.000028 second [0.027775 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] DoSearch file id:96: job 185933 nq 1 topk 10, do search (0.000419 second [0.418734 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] DoSearch file id:96: job 185933 nq 1 topk 10, reduce topk (0.000016 second [0.016050 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] SearchJob 185933 finish index file: 96
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] SearchJob 185933 all done
2020-03-26 19:43:19,445 | DEBUG | default | [ENGINE] Unmark ongoing file:1585218600262217000 refcount:0
2020-03-26 19:43:19,445 | DEBUG | default | [ENGINE] Unmark ongoing file:1585219223098924000 refcount:0
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] Engine query totally cost (0.001406 second [1.405588 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] [CACHE CPU] [item count]: 2, [usage] 145MB, [capacity] 4096MB
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): query vectors from engine (0.001766 second [1.765896 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): construct result (0.000015 second [0.015036 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.001906 second [1.906462 ms])
2020-03-26 19:43:19,445 | DEBUG | default | [SERVER] DoSearch file id:96: totally cost (0.000611 second [0.610649 ms])
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] SearchRequest pre-execute(table=sift_128_euclidean): totally cost (0.000003 second [0.003376 ms])
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): check validation (0.000118 second [0.117879 ms])
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Collect files from table: sift_128_euclidean
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Collect 2 to-search files
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] [CACHE CPU] [item count]: 2, [usage] 145MB, [capacity] 4096MB
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Mark ongoing file:1585218600262217000 refcount:1
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Mark ongoing file:1585219223098924000 refcount:1
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Engine query begin, index file count: 2
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] SearchJob 185934 add index file: 96
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] SearchJob 185934 add index file: 97
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] EngineFactory index type: 3
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Index params: {"dim":128,"gpu_id":0,"metric_type":"L2","nlist":16384}
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] EngineFactory index type: 3
2020-03-26 19:43:19,447 | DEBUG | default | [ENGINE] Index params: {"dim":128,"gpu_id":0,"metric_type":"L2","nlist":16384}
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] FallbackPass!
2020-03-26 19:43:19,447 | DEBUG | default | [SERVER] FallbackPass!
2020-03-26 19:43:19,448 | DEBUG | default | [SERVER] Search task load file id:97 DISK2CPU file type:3 size:7633361 bytes from location: /var/lib/milvus/db/tables/sift_128_euclidean/1585218597577652000/1585219223098924000 totally cost (0.000007 second [0.006963 ms])
2020-03-26 19:43:19,448 | DEBUG | default | [SERVER] Search task load file id:96 DISK2CPU file type:3 size:145013261 bytes from location: /var/lib/milvus/db/tables/sift_128_euclidean/1585218595349328000/1585218600262217000 totally cost (0.000005 second [0.005406 ms])
2020-03-26 19:43:19,448 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: query prepare (0.000004 second [0.003581 ms])
2020-03-26 19:43:19,485 | DEBUG | default | [KNOWHERE] IVF search cost: 36831.4, quantization cost: 2.26099, data search cost: 34.5691
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: query done (0.036903 second [36.903500 ms])
2020-03-26 19:43:19,485 | DEBUG | default | [ENGINE] get uids 50000 from index /var/lib/milvus/db/tables/sift_128_euclidean/1585218597577652000/1585219223098924000
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: map uids 10 (0.000034 second [0.033720 ms])
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] DoSearch file id:97: job 185934 nq 1 topk 10, do search (0.036961 second [36.961118 ms])
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] DoSearch file id:97: job 185934 nq 1 topk 10, reduce topk (0.000015 second [0.015471 ms])
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] SearchJob 185934 finish index file: 97
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] DoSearch file id:97: totally cost (0.037002 second [37.001549 ms])
2020-03-26 19:43:19,485 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: query prepare (0.000004 second [0.003525 ms])
2020-03-26 19:43:19,511 | DEBUG | default | [KNOWHERE] IVF search cost: 26432.1, quantization cost: 6.12598, data search cost: 20.304
2020-03-26 19:43:19,511 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: query done (0.026511 second [26.510793 ms])
2020-03-26 19:43:19,511 | DEBUG | default | [ENGINE] get uids 950000 from index /var/lib/milvus/db/tables/sift_128_euclidean/1585218595349328000/1585218600262217000
2020-03-26 19:43:19,511 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: map uids 10 (0.000075 second [0.074585 ms])
2020-03-26 19:43:19,511 | DEBUG | default | [SERVER] DoSearch file id:96: job 185934 nq 1 topk 10, do search (0.026637 second [26.636766 ms])
2020-03-26 19:43:19,511 | DEBUG | default | [SERVER] DoSearch file id:96: job 185934 nq 1 topk 10, reduce topk (0.000044 second [0.044103 ms])
2020-03-26 19:43:19,511 | DEBUG | default | [SERVER] SearchJob 185934 finish index file: 96
2020-03-26 19:43:19,511 | DEBUG | default | [SERVER] SearchJob 185934 all done
2020-03-26 19:43:19,512 | DEBUG | default | [ENGINE] Unmark ongoing file:1585218600262217000 refcount:0
2020-03-26 19:43:19,512 | DEBUG | default | [ENGINE] Unmark ongoing file:1585219223098924000 refcount:0
2020-03-26 19:43:19,512 | DEBUG | default | [SERVER] Engine query totally cost (0.064362 second [64.362414 ms])
2020-03-26 19:43:19,512 | DEBUG | default | [SERVER] [CACHE CPU] [item count]: 2, [usage] 145MB, [capacity] 4096MB
2020-03-26 19:43:19,512 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): query vectors from engine (0.064845 second [64.844598 ms])
2020-03-26 19:43:19,512 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): construct result (0.000049 second [0.048679 ms])
2020-03-26 19:43:19,512 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): totally cost (0.065052 second [65.052199 ms])
2020-03-26 19:43:19,512 | DEBUG | default | [SERVER] DoSearch file id:96: totally cost (0.027117 second [27.116603 ms])
2020-03-26 19:43:19,513 | DEBUG | default | [SERVER] SearchRequest pre-execute(table=sift_128_euclidean): totally cost (0.000004 second [0.003613 ms])
2020-03-26 19:43:19,514 | DEBUG | default | [SERVER] SearchRequest execute(table=sift_128_euclidean, nq=1, k=10): check validation (0.000192 second [0.192211 ms])
2020-03-26 19:43:19,514 | DEBUG | default | [ENGINE] Collect files from table: sift_128_euclidean
2020-03-26 19:43:19,514 | DEBUG | default | [ENGINE] Collect 2 to-search files
2020-03-26 19:43:19,514 | DEBUG | default | [SERVER] [CACHE CPU] [item count]: 2, [usage] 145MB, [capacity] 4096MB
2020-03-26 19:43:19,514 | DEBUG | default | [ENGINE] Mark ongoing file:1585218600262217000 refcount:1
2020-03-26 19:43:19,514 | DEBUG | default | [ENGINE] Mark ongoing file:1585219223098924000 refcount:1
2020-03-26 19:43:19,514 | DEBUG | default | [ENGINE] Engine query begin, index file count: 2
2020-03-26 19:43:19,515 | DEBUG | default | [SERVER] SearchJob 185935 add index file: 96
2020-03-26 19:43:19,515 | DEBUG | default | [SERVER] SearchJob 185935 add index file: 97
2020-03-26 19:43:19,515 | DEBUG | default | [ENGINE] EngineFactory index type: 3
2020-03-26 19:43:19,515 | DEBUG | default | [ENGINE] Index params: {"dim":128,"gpu_id":0,"metric_type":"L2","nlist":16384}
2020-03-26 19:43:19,515 | DEBUG | default | [ENGINE] EngineFactory index type: 3
2020-03-26 19:43:19,515 | DEBUG | default | [ENGINE] Index params: {"dim":128,"gpu_id":0,"metric_type":"L2","nlist":16384}
2020-03-26 19:43:19,515 | DEBUG | default | [SERVER] FallbackPass!
```
**Steps/Code to reproduce behavior**
```
import time
import random
import string
from locust import Locust, TaskSet, task, between
from milvus import Milvus, IndexType, MetricType

from gevent import monkey

monkey.patch_all()


dim = 128
top_k = 10
nprobe = 16
nq = 1
m = Milvus()
m.connect(host="192.168.1.197", port=19530)


def gen_uniq_str():
    return "".join(random.choice(string.ascii_letters + string.digits) for _ in range(8))


class MyTaskSet(TaskSet):
    table_name = "sift_128_euclidean"
    i = 0
    counter = {"passed": 0, "failed": 0}
    print("In taskset")

    def setup(self):
        print("Start .......................")

    @task
    def task_search(self):
        print("In task")
        self.i = self.i + 1
        query_records = [[random.random() for i in range(dim)] for i in range(nq)]
        print("After connect")
        status, result = m.search_vectors(self.table_name, top_k, query_records, params={"nprobe": nprobe})
        print("After search")
        if status.OK():
            self.counter["passed"] += 1
        else:
            print(status)
            self.counter["failed"] += 1

    def teardown(self):
        print("Stop .......................")
        print(self.counter)
        print(self.i)
        m.disconnect()


class MyLocust(Locust):
    task_set = MyTaskSet
    wait_time = between(0.5, 1)
```

run cmd:
`
locust -f locust_test.py --no-web -c 1000 -r 100 --run-time 4m --step-load --step-clients 300 --step-time 1m
`
**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment] 2020-04-30 12:05
Longer query will last for a very short period of time.
I guess there are some background threads wake up intermittently to occupy the cpu.
Would you please limit the omp / openblase thread num and test it again?

**Comment by del-zhenwu** [comment] 2020-05-08 08:52
use_blas: 20
opm_thread_num: 4
```
[2020-05-08 16:47:06,839][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.001972 second [1.971648 ms])
[2020-05-08 16:47:06,843][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.001436 second [1.436358 ms])
[2020-05-08 16:47:06,845][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.001378 second [1.377863 ms])
[2020-05-08 16:47:06,852][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.001655 second [1.654811 ms])
[2020-05-08 16:47:06,856][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002565 second [2.564726 ms])
[2020-05-08 16:47:06,859][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.001517 second [1.517224 ms])
[2020-05-08 16:47:06,895][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.034586 second [34.586407 ms])
[2020-05-08 16:47:06,900][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002585 second [2.585286 ms])
[2020-05-08 16:47:06,903][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.001572 second [1.572139 ms])
[2020-05-08 16:47:06,972][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.065129 second [65.128717 ms])
[2020-05-08 16:47:07,024][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.051007 second [51.006672 ms])
[2020-05-08 16:47:07,028][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002060 second [2.059877 ms])
[2020-05-08 16:47:07,032][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002884 second [2.883538 ms])
[2020-05-08 16:47:07,092][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.058428 second [58.428216 ms])
[2020-05-08 16:47:07,096][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002901 second [2.900971 ms])

```
omp_thread_num no set:
```
[2020-05-08 16:41:06,445][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002162 second [2.162343 ms])
[2020-05-08 16:41:06,449][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002251 second [2.250844 ms])
[2020-05-08 16:41:06,452][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002396 second [2.396323 ms])
[2020-05-08 16:41:06,458][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002788 second [2.787750 ms])
[2020-05-08 16:41:06,462][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.002565 second [2.564910 ms])
[2020-05-08 16:41:06,468][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.003572 second [3.571870 ms])
[2020-05-08 16:41:06,473][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.003702 second [3.702324 ms])
[2020-05-08 16:41:06,483][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.005396 second [5.396366 ms])
[2020-05-08 16:41:06,491][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.005917 second [5.917479 ms])
[2020-05-08 16:41:06,500][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.007401 second [7.401308 ms])
[2020-05-08 16:41:06,511][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.007880 second [7.880127 ms])
[2020-05-08 16:41:06,521][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.008485 second [8.484976 ms])
[2020-05-08 16:41:06,533][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.008782 second [8.781786 ms])
[2020-05-08 16:41:06,544][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.008136 second [8.135643 ms])
[2020-05-08 16:41:06,554][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.007939 second [7.939431 ms])
[2020-05-08 16:41:06,565][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.008730 second [8.730098 ms])
[2020-05-08 16:41:06,577][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] [search][0] SearchRequest execute(collection=sift_128_euclidean, nq=1, k=10): totally cost (0.008059 second [8.058904 ms])

```
```

**Comment by shengjun1985** [comment] 2020-07-25 03:20
issue #1734 (merged on Mar 24) will combine similar queries.
So, the instability search time is not a bug.

**Comment by yhmo** [comment] 2021-08-13 03:14
Inactive

**Closed by yhmo** 2021-08-13 03:14 UTC
Labels: kind/bug, priority/awaiting-more-evidence, severity/minor, kind/improvement
